openshift/osde2e

- glide.lock
- glide.yaml
- pkg/osd/cluster.go
- setup.go
This PR:
* upgrades to uhc-sdk-go to [v0.1.11](https://github.com/openshift-online/uhc-sdk-go/releases/tag/v0.1.11)
* silences any failures in the `AfterSuite` if they are related to setup issues
> Upgrade UHC & skip AfterSuite when setup has failed

- e2e.go
- glide.lock
- glide.yaml
- pkg/osd/versions.go
- setup.go
PR checks UHC versions for available versions and chooses the latest nightly that exists.
> Use latest nightly when CLUSTER_VERSION is not specified

- e2e_test.go
- pkg/helper/clientsets.go
- pkg/helper/helper.go
- pkg/helper/pods.go
- pkg/helper/projects.go
- test/openshift/openshift.go
- test/openshift/pod.go
- test/openshift/results.go
This PR adds running the [OpenShift extended test suite](https://github.com/openshift/origin/tree/master/test/extended) as part of osde2e. The tests are run out of Pod using the ImageStream 'tests' that the cluster is deployed with.
Closes #8
> Run openshift-tests as part of suite

- Makefile
- pkg/osd/versions.go
- setup.go
This change uses the newest rc available for tests.
> Use latest available rc by default

- Makefile
- glide.lock
- glide.yaml
This PR:
- Bumps github.com/openshift-online/uhc-sdk-go to `v0.1.14`. It has changes which redact tokens.
- Enables DEBUG_OSD for periodic builds
Closes #9
> Enable OSD debug logs

- Makefile
Currently docker containers after use stopped but not deleted.
This may prevent obsoleted docker images to be garbage collected, because they are referenced by stopped container.
That in turn leads to disk full situation for jenkins.
> remove docker containers after use

- pkg/osd/cluster.go
This patch changes the tests so that they always set an
`expiration_timestamp` for the created clusters. That way even if the
tests crash or forget to delete the cluster for whatever the reason the
cluster will be automatically removed after eight hours.
> Set cluster expiration timestamp

- ci/upgrade_events.sh
- e2e.go
- pkg/config/config.go
- pkg/config/load.go
- pkg/testgrid/latest.go
- pkg/testgrid/testgrid_test.go
This change:
- add environment variable `CLEAN_RUNS` which species the number of passing runs with the same build-version
- removes `NEW_ONLY` which functionality can be accomplished with `CLEAN_RUNS=1`
- sets osde2e to run with `CLEAN_RUNS=3`
> Require at least 3 CLEAN_RUNS, remove NEW_ONLY

- pkg/testgrid/builds.go
- pkg/testgrid/junit.go
- pkg/testgrid/junit_test.go
- pkg/testgrid/testgrid_test.go
This change:
- adds method to `TestGrid` to collect JUnit testsuites for builds
> Support retrieving JUnit results for a build

- e2e.go
- pkg/config/config.go
- pkg/osd/environments.go
- pkg/osd/osd.go
This change:
- Adds new option `OSD_ENV` to specify which environment should be tested.
- Supports integration environment
- Deprecrates `USE_PROD`
> Support integration environment

- e2e.go
- pkg/config/config.go
- pkg/config/testgrid.go
- pkg/osd/cluster.go
- pkg/osd/logs.go
- setup.go
This PR:
- includes the testing configuration (including name) in TestGrid metadata
- extends the cluster up timeout to longer than the threshold where alerts are triggered in stage
- stops truncating log output and instead gets as much as possible
> Produce more debug information

- e2e.go
- glide.lock
- glide.yaml
- pkg/config/config.go
- pkg/osd/cluster.go
- pkg/osd/osd.go
- pkg/osd/quota.go
This change:
- Adds new OSD methods for checking if the current environment has enough quota to run the suite
- Enables checking on new test runs
- Adds a temporary client to access the resource_summary endpoint of the accounts API
> Check if enough quota exists for a test

- e2e.go
- pkg/config/config.go
- pkg/config/load.go
- pkg/osd/versions.go
- setup.go
- version.go
This change:
- Creates new `TARGET_MAJOR` and `TARGET_MINOR` config to launch with a specific version of nightly
- Defaults to a shorter name to be under OSD's 60 character limit
- Adds support for loading `int64` config variables
> Allow specifying specific nightlies

- Makefile
Allow NO_DESTROY environment variable to be used by default in the Makefile target for docker-test. If unset, cluster will continue to be destroyed as it currently is.
In practice, this considerably reduces the amount of times I accidentally delete a test cluster while doing iterative tests (I can source a file with cluster details and NO_DESTROY=true).
Signed-off-by: Christopher Collins <collins.christpher@gmail.com>
> take NO_DESTROY env for docker-test runs

- pkg/osd/versions.go
- pkg/upgrade/releases.go
- pkg/upgrade/upgrade.go
- version.go
stage and prod test pipelines will now use Cincinnati instead of the
release-controller.
> SDAR-22. Modify stage and prod to use Cincinnati.

- test/operators/dedicatedadmin.go
Condensed tests into single Describe block and labelled with [OSD] to denote our group responsibility.
> renamed main tests to better label responsible group

- test/operators/dedicatedadmin.go
Moved poller timeouts to single global setting for pollers; increased to 60m.  OLM in normal operation takes ~15 minutes to be installed and begin installing operators, so the previous 20m timeout left little wiggle room for any other latency.
> Increase olm grace period

- ci/upgrade_events.sh
CLEAN_RUNS have been removed from upgrade tests so that upgrade tests
run more regularly.
> SDAR-30. Remove CLEAN_RUNS from upgrade tests.

- pkg/config/config.go
- setup.go
After tests complete (successfully or otherwise), wait one hour to allow
for any active debugging.
Note: The lack of env/sect for time.Duration is intended, as apparently the doc generation barfs otherwise.
> SDAR-31. Add an hour wait after test completion.

- Makefile
- README.md
The test timeout has been increased to 4 hours to accommodate for the
hour long bake time after tests have been run.
> SDAR-31. Increase test.timeout to 4h.

- glide.lock
- glide.yaml
- pkg/helper/clientsets.go
Adding a clientset from operator-framework/operator-lifecycle-manager to work with Operator resources (eg, clusterserviceversion, subscription, etc)
> adding operator-lifecycle-manager clientsets

- Makefile
- docs/Options.md
- e2e_test.go
- pkg/config/config.go
- setup.go
The debug sleep thing kind of hurts doing local testing/development because the clusters linger around. So, being able to toggle it with an env var seemed appropriate.
Also this PR comments out the dedicatedadmin test while we try to achieve some cleaner signal and I try to optimize its testing 
/cc @clcollins 
> Remove operator testing, make debug sleep optional

- version.go
The DefaultVersion in OSD is now used instead of the PreviousVersion for
upgrades.
Note: Haven't tested this yet, as I'm waiting on the PR to fix the dedicatedadmin.go syntax issues.
> SDAR-36. Use DefaultVersion instead of PreviousVersion for upgrades.

- version.go
The `if` statements were ordered in such a way that it was possible for TargetStream to not be honored.
> Fix condition where targetstream would not be honored

- e2e.go
We should fail when no quota is available. With this, we'll be able to
more accurately identify how often we're running out of quota, and
justify further quota increases if needed.
Note: Verified the test fails when there's no quota.
> SDAR-34. Fail when no quota is available.

- pkg/upgrade/releases.go
- setup.go
- version.go
Clusters are expecting versions (from streams) to have `openshift-v`. This looks to see if the returned version contains the string and, if not, prepends it. Tested extensively locally with great success~
Also sneaking in a 300s wait time between cluster-install and tests. 
/assign @meowfaceman @clcollins
> Look for version prefix expected by cluster

- pkg/osd/versions.go
When building a list of available versions, only use versions that have been enabled in the API.
Resolves [SDAR-44](https://jira.coreos.com/browse/SDAR-44)
> Resolve SDAR-44 - only use an enabled version

- pkg/upgrade/upgrade.go
To install, you're required to set the full version to have `openshift-v` prepended. The same is not true when setting the version for an upgrade. This ensures that the prefix is stripped before submitting the version for upgrade.
> SDAR-51 - Don't send verbose version to upgrade

- Makefile
- pkg/upgrade/upgrade.go
- setup.go
Addresses [SDAR-46](https://jira.coreos.com/browse/SDAR-46)
While there, noticed two small quick fixes:
- Cluster Name wasn't being passed to the container 
- The install-to-action buffer was set to 300ms not 300s.
> SDAR-46 - Bump upgrade acknowledgement timeout to 5min

- docs/Options.md
- pkg/config/config.go
- pkg/upgrade/releases.go
- version.go
The source Openshift version pulls from Cincinnati for integration
upgrade tests. This is done to support 4.1 -> 4.1 upgrades.
There are several reasons for doing this:
* The current 4.1 nightly is set as default in integration OSD. This
means that the upgrade version is set to the current default in OSD.
This, in turn, falls back on the logic to go to the previous enabled
version to upgrade from.
* The previous version selected is also a nightly, which means the
delta between the two images isn't relevant from a user perspective.
* The 4-stable stream in the release controller includes 4.2, which
means the latest version selected as a source version doesn't make sense
for a 4.1 -> 4.2 upgrade. In other words, there's no way currently to
get a stable stream in the release controller for a …
> SDAR-50. Use Cincinnati for source Openshift version for integration.

- Makefile
This PR adds a default environment variable to use Docker as the container engine for build/run/push commands, but allows setting the $CONTAINER_ENGINE variable to override the default to support another container engine (eg: Podman), as long as the container engine API is the same (so, Podman).
> Set continer engine in Makefile via environment variable

- pkg/runner/pod.go
- pkg/runner/service.go
There were conditions where `wait.PollImmediateUntil` would loop without end, and there are cases where we want to continually poll until timeout, not until success or failure. 
Partially addresses [SDAR-53](https://jira.coreos.com/browse/SDAR-53)
> SDAR-53 (partial fix) - use wait.PollImmediate and have a timeout

- test/operators/dedicatedadmin.go
We ran into a condition where ginkgo would not properly timeout a test because the test had a for-loop in it that wouldn't exit (because that for-loop had a timeout of ~30hrs). 
This makes all the timeouts consistent with the ginkgo test timeouts.
In the future we should probably kick tests that have their own for loops into an async call that ginkgo can then timeout and clean up. :) 
/assign @meowfaceman 
/cc @clcollins
> SDAR-55: Change minutes to seconds, add some comments

- setup.go
Some of the conformance tests are flaking. My guess is that they're still being run too soon after a cluster is "installed."
This bumps the delay between install and testing to ten minutes. I put this under SDAR-53 since it's still addressing tests timing out. 
We should see flakes start resolving over the next couple days with this change, or there's another issue to address :)
> SDAR-53 - Bump cooldown to 10min

- test/operators/configurealertmanager.go
- test/operators/dedicatedadmin.go
- test/operators/managedvelero.go
- test/operators/operators.go
This PR encompasses the refactored operator test scaffold; simplifies the dedicated-admin operator test; add configure-alertmanager and managed-velero operator tests.
Replaces PR #118 ; PR #110
> Refactor Operator Test Scaffold; add basic tests

- test/operators/operators.go
Found/removed all instances of `* 60`
Rest of the operator timeouts appeared correct.
> SDAR-60 - Fix operator timeouts

- pkg/osd/versions.go
- version.go
The MAJOR_TARGET and MINOR_TARGET variables will now target versions
that come directly from the OSD cluster versions endpoint without being
targeted at a specific type of nightly.
> SDCICD-40. Use MAJOR_TARGET and MINOR_TARGET to target CIS versions.

- pkg/runner/git_test.go
- pkg/runner/runner.go
- pkg/runner/runner_test.go
- pkg/runner/service.go
- pkg/runner/service_test.go
- test/openshift/openshift.go
- test/state/mustgather.go
- test/state/prometheus.go
The timeout in the Ginkgo tests is now propagated down to
waitForEndpoints. Additionally, the Ginkgo tests' timeouts are padded by
30 seconds to allow for a more edifying error message from the
waitForEndpoints timeout if it gets hit.
Note: Running some tests for this now, but I think the basic logic here should be fine.
> SDCICD-59. Propagate timeout to waitForEndpoints.

- pkg/helper/nodes.go
- pkg/helper/operators.go
- pkg/helper/pods.go
- pkg/osd/cluster.go
- setup.go
This mimics the osd-verify script SREs use to determine cluster health. It's checking the CVO for cluster state, then checking operator, node, and pod health. 
Once a cluster is deemed healthy, it will continue polling until 5 clean polls occur, or will attempt to do so until the setup timeout.
> Use cvo and osd-verify checks to determine cluster health

- e2e.go
- setup.go
There were some dependencies still being checked even if a Kubeconfig was provided. This checks for the presence of a Kubeconfig and skips, and otherwise behaves as normal.
tl;dr added some if statements.
> SDCICD-65 - Fix behavior with a provided Kubeconfig 

- pkg/helper/pods.go
- pkg/helper/pods_test.go
When a pod has not succeeded it will now output the message and reason. 
> CICD-69 - Output more pod info

- docs/Options.md
- e2e.go
- pkg/config/config.go
- pkg/osd/cluster.go
- setup.go
- version.go
Pretty simple.
Also there was some abandoned code after the TARGET_STREAM excision regarding generating a version string that isn't called anywhere else, so it too got pulled out. :) 
> CICD-71 - Set default values in config file.

- pkg/config/load.go
Original logic assumed if the default is set for a bool, it _must_ be true.
The broken tests indicate that that was a lie.
> CICD-73 - Fix bool default logic

- docs/Options.md
- docs/Writing-Tests.md
- glide.lock
- glide.yaml
- pkg/config/config.go
- pkg/osd/cluster.go
- pkg/osd/logs.go
- pkg/osd/osd.go
- pkg/osd/quota.go
- pkg/osd/versions.go
- setup.go
Cluster expiry is now configurable and the old cluster cleanup code has
been excised. Additionally, the code has been migrated to use ocm-go-sdk
rather than uhc-go-sdk, as uhc-go-sdk is deprecated.
> SDCICD-27. Make cluster expiry configurable and update to ocm-go-sdk.

- docs/Options.md
- pkg/config/config.go
- pkg/helper/operators.go
- pkg/helper/operators_test.go
- pkg/osd/cluster.go
This lets us configure the OperatorReadiness check to ignore any operator in a comma-delimited list. 
Default is currently set to ignore `insights` but that should change in the future.
> CICD-78: Add config option to skip certain operator health checks

- pkg/upgrade/upgrade.go
- setup.go
Currently we don't check the health of a cluster post-upgrade, unlike vanilla-install e2e tests.
This change will ensure that a cluster is considered healthy not only pre, but post-upgrade before e2e tests run.
> SDCICD-76: Check cluster readiness post-upgrade, not just pre

- Makefile
- ci/prow_pr_check.sh
- common/e2e.go
- common/setup.go
- common/version.go
- pkg/runner/runner.go
- pkg/runner/service.go
- pkg/runner/service_test.go
- suites/e2e/e2e_test.go
- suites/scale/scale_test.go
- test/scale/nodevertical.go
- test/scale/scale.go
The NodeVertical tests that @ethernetdan had been working on have been
reintroduced into osde2e. Additionally, the tests have been split into
general and scale tests, as the scale tests take much longer to run than
other tests, and as a result need to be split out.
> SDCICD-63. Reintroduce NodeVertical tests.

- e2e.go
- pkg/helper/helper.go
- pkg/upgrade/upgrade.go
- setup.go
We should validate that a cluster is valid and healthy prior to running an upgrade. 
There was some massaging to be done because of the way the test suite set itself up (if kubeconfig was set it assumed it was a filename not a valid kubeconfig and how helpers would spin up projects)  but it's been tested locally without issue.
> CICD-6: Run tests pre and post upgrade

- pkg/helper/workloads.go
Fix a condition where `info` may be nil and cause a panic. 
> SDCICD-50: Fix filewalk bug

- common/e2e.go
- common/setup.go
- common/version.go
- pkg/metadata/metadata.go
- pkg/metadata/metadata_test.go
- pkg/osd/cluster.go
osde2e will now collect metadata and serialize it to JSON when running
tests. These will then be reported in Spyglass when examining prow job
results.
> SDCICD-91. Collect metadata and report it during a run.

- ci/prow_run_tests.sh
- common/e2e.go
- docs/Options.md
- pkg/config/config.go
UHC_TOKEN has been renamed to OCM_TOKEN.
Note: There's a duplicate secret in OpenShift CI "OCM_REFRESH_TOKEN" so that once this is checked in, there should be no gap in functionality. Once this is in and a few jobs have run I'll remove UHC_REFRESH_TOKEN.
> SDCICD-98. Rename UHC_TOKEN to OCM_TOKEN.

- common/e2e.go
- pkg/helper/pods.go
- pkg/helper/pods_test.go
- pkg/osd/cluster.go
Currently if a cluster encounters an error while starting up (job or pod fails or OOMs) `PollClusterHealth` will continue until we hit the 45min timeout.
This change will fail an osde2e run if `PollClusterHealth` returns an error five times in a row. 
Along with that logic:
- I added tests to cover the checking of the error response as well as the ready boolean. 
- If you ran osde2e against an ad-hoc cluster, it would still attempt to "delete" the cluster even though the OSD bits weren't initialized. So I added a check to skip that.
> SDCICD-72: Fail osde2e fast if it encounters errors

- test/state/prometheus.go
The prometheus state gather test will sometimes flake and fail if one of the files on disk is modified while the tar is running. If tar detects this has happened, it will [exit 1](http://man7.org/linux/man-pages/man1/tar.1.html#RETURN_VALUE) causing the job pod to fail.
I can't find a way to modify this behaviour in tar 1.26 (the `--ignore-failed-read` flag doesn't work as expected). Use a bash pipe through to some if logic to prevent this from failing.
> Fix prometheus gather flake

- common/e2e.go
- pkg/config/config.go
- pkg/helper/helper.go
- test/workloads/guestbook/guestbook.go
This tracks and cleans up installed workloads. Whenever invoking the helper, it automatically creates a new project. In this case, we want to be able to recover which project a helper should have, based on the workload. 
So we now track installed workloads within the Config struct, and there are a bunch of added getter/setter functions as part of the helper to let us influence the Project lifecycle for a `helper` instance. 
Lastly, if we run this against an external/non-OSD cluster, we need to clean up everything invasive OSDe2e did during a run.
One thing that became apparent is that the helper may need to be refactored in the future, but it's not urgent.
> SDCICD-92 - Re-enable post-upgrade workload tests

- common/setup.go
If a cluster ID is provided, the cluster name was not being properly
set. It will now be retrieved from OCM if the cluster name has not
otherwise been provided. Additionally, the cluster name is now recorded
in the custom prow metadata.
> SDCICD-101. Get cluster name for existing clusters.

- test/operators/certman.go
The certman test now verifies if the NamedCertificates array is not
empty before trying to grab a certificate out of it.
/cc @wanghaoran1988
> SDCICD-103. Fix panic in certman test.

- common/e2e.go
- common/metrics.go
- common/metrics_test.go
- docs/Options.md
- go.mod
- go.sum
- pkg/config/config.go
- pkg/helper/runner.go
Metrics are now written to a Prometheus file in the report directory.
Several things are done here:
* All jUnit test results stored in an XML file are written out in the
following format:
```
cicd_jUnitResult{environment="int|stage|prod", install_version="install-version", phase="install|upgrade", result="passed|failed|skipped", suite="test suite", testname="test name", upgrade_version="upgrade-version"} 1.2345
```
This is the environment, install and upgrade versions, pass/fail/skipped, what phase (tests pre or post upgrade), the name of the suite, and the name of the test.
* Custom metadata and addon metadata (preliminary support) will be
written out in the following format:
```
cicd_metadata{environment="int|stage|prod", install_version="install-version", …
```
> SDCICD-54. Metrics are now exported in prometheus exposition format.

- ci/prow_run_tests.sh
The UPLOAD_METRICS environment variable was incorrectly being used as
METRICS_UPLOAD.
> SDCICD-54. Fix another typo in the run tests script.

- .osde2e.yaml
- Makefile
- common/e2e.go
- common/setup.go
- common/version.go
- go.mod
- go.sum
- pkg/config/config.go
- pkg/config/load.go
- pkg/helper/helper.go
- pkg/helper/operators.go
- pkg/helper/operators_test.go
- pkg/osd/cluster.go
- pkg/osd/quota.go
- pkg/osd/versions.go
- pkg/upgrade/releases.go
- pkg/upgrade/upgrade.go
- suites/e2e/e2e_test.go
- suites/scale/scale_test.go
- test/operators/certman.go
- test/operators/curator.go
- test/operators/dedicatedadmin.go
- test/operators/operators.go
- test/operators/prunejob.go
This PR restructures the Config package to have embedded structs. This was becoming necessary as the config options grew. In addition, when `osde2e` is run, it can now be supplied a `yaml` file with the config options.
By default, it looks for `./.osde2e.yaml` and if not found, continues on attempting to use environment variables and defaults. You can specify a file by passing `-e2e-config` when running `osde2e`
While a large PR, the majority of changes by and large involve changing various config options across the whole project. 
> SDCICD-83 - Support job configuration by optional YAML file

- test/operators/dedicatedadmin.go
Dedicated admin operator tests are disabled until they can be replaced
by RBAC operator tests.
> SDCICD-105. Disable dedicated admin operator tests.

- scripts/metrics-sync.sh
The trailing slash at the end of the URL prevents successfuly metrics
pushing to the pushgateway.
> Strip trailing slashes from the push gateway in the metrics-sync script.

- .gitignore
- Makefile
- cmd/osde2e-docs/main.go
- go.mod
- go.sum
- pkg/config/config.go
- pkg/helper/helper.go
- pkg/helper/runner.go
- pkg/osd/cluster.go
- pkg/runner/command.go
- pkg/runner/imagestream.go
- pkg/runner/imagestream_test.go
- pkg/runner/pod.go
- pkg/runner/runner.go
- suites/addons/addons_test.go
- suites/addons/testdata/addon-runner.template
- test/addons/addon_test_harness.go
- test/openshift/openshift.go
- vendor/k8s.io/utils/pointer/OWNERS
- vendor/k8s.io/utils/pointer/pointer.go
- vendor/modules.txt
Addon test harnesses can now be supplied to osde2e. This will allow for
addon authors to test against OSD clusters. Results from addons will be
collected by osde2e for later analysis.
> SDCICD-87. Addon test harness support.

- pkg/runner/command.go
Single line commands didn't work with the command rework before due to
the command provided to the helper seeming to require a newline at the
end of it.
> SDCICD-87. Fix command rework bug for single line commands.

- pkg/runner/pod.go
Runners will ensure that they will run as the root user for a container
so that the necessary directory /test-run-results can be created.
> SDCICD-87. Make sure runners run as root.

- common/e2e.go
- common/e2e_test.go
- common/metrics.go
- common/setup.go
- pkg/events/event_type.go
- pkg/events/events.go
- pkg/events/events_test.go
osde2e can now track counter events. This will allow for tracking the
number of successful/failed events, like cluster provisions, upgrades,
etc. This will be useful for alerting.
> SDCICD-108. Counter event support.

- pkg/osd/cluster.go
We should use the osd-4 flavor for clusters now so that we get infra
nodes as part of our clusters.
> SDCICD-114. Use osd-4 for default flavor for new clusters.

- pkg/osd/cluster.go
- pkg/osd/osd.go
- suites/addons/addons_test.go
Though currently blocked by SDA-1757, addon support has had a few fixes
to ensure things work as expected. Namely:
* Proper e2e config parsing.
* Using the general addons endpoint for querying addons as opposed to
the cluster level one.
> SDCICD-89. General fixes for addon support.

- common/version.go
- pkg/config/config.go
- pkg/metadata/metadata.go
- pkg/upgrade/releases.go
- pkg/upgrade/upgrade.go
Cluster image sets can now be used directly for upgrades if specified.
> SDCICD-123. Use cluster image sets for upgrades if specified.

- common/version.go
- pkg/osd/versions.go
By default Int will install a nightly rather than a stable version. This is true even in upgrade tests where we want to test a nightly _upgrade_ from a stable base. 
This PR changes the version selection logic to use a stable base if it detects the test will be an upgrade. Tested it locally and seems good.
> SDCICD-120: Install stable version on Int before upgrading to nightly

- common/e2e.go
- pkg/events/events_test.go
Groundwork required before Prow Jobs PR. We need to write to `metadata.json` as well as `custom-prow-metadata.json`
This will allow a smooth transition to vanilla Prow jobs. 
> SDCICD-128: Write to two different metadata.json files

- common/e2e.go
- common/metrics.go
- common/metrics_test.go
- pkg/metadata/metadata.go
- pkg/metadata/metadata_test.go
- suites/addons/testdata/addon-runner.template
Addon test harnesses were not being properly supplied to the addon
runner template, so this has been corrected. Additionally, addon
metadata is now added to the general metadata object for Spyglass
metadata display. Finally, addon prometheus data will recognize phases
now.
> SDCICD-85. Updates for addon test harness work.

- common/version.go
- pkg/osd/versions.go
- suites/clusterimagesets/latest/imagesets_test.go
- suites/clusterimagesets/middle/imagesets_test.go
- suites/clusterimagesets/oldest/imagesets_test.go
https://issues.redhat.com/browse/SDCICD-9
Based on the current framework, the cluster will be created once before suite. The only method for me is separating the oldest and newest ClusterImageSets into two suites.  The versions used for testing are not the default version, that means three versions will be covered. 
Certainly, it can be enhanced to test all the versions, but need to think whether it is worth doing. In my opinion, the newest, the oldest, the middle one can cover the most cases.
> e2e test for testing newest Hive with a set of older ClusterImageSets

- common/e2e.go
- pkg/events/events_test.go
If a job is being rehearsed, metrics upload should be skipped.
> SDCICD-131. Skip metrics upload on rehearsal jobs.

- common/e2e.go
We repeat entire test suites depending on the phase of the run (install, upgrade, ???) but it's difficult to discern which test result is part of which phase within spyglass/testgrid.
This prepends every test name with `[$phase]`
> SDCICD-144: Prepend test results with phase of test

- test/operators/managedvelero.go
The role and rolebinding for reading cluster-config-v1
is outdated and has been removed from managed-velero-operator.
https://github.com/openshift/managed-velero-operator/pull/35
This commit removes the test that looks for that rolebinding.
> Remove outdated rolebinding

- common/version.go
- pkg/config/config.go
The latest cluster image set can now be used for fresh installs.
Additionally, the upgrade logic was fine tuned to support only using
cluster image sets without needing to supply a Cincinnati fallback.
> SDCICD-157. Support using latest cluster image set for fresh installs.

- common/e2e.go
- common/version.go
- pkg/state/state.go
If the upgrade version and install version matches, we should skip the
upgrade.
> SDCICD-157. Skip upgrades if the versions are identical.

- pkg/osd/cluster.go
This effecitvely makes the health check window require 10 minutes of
good health instead of 5. This will hopefully allow for OSD operators to
have more time to set up properly and reduce flakes in our builds.
> SDCICD-158. Increase health check window.

- test/operators/certman.go
Instead of failing immediately, we should give the certman operator a minimum of 15 minutes to provision certs per the [docs](https://github.com/openshift/certman-operator#how-the-certman-operator-works)
> SDCICD-160: Add a wait loop to certman tests

- common/e2e.go
Cluster image set upgrades were not behaving as expected due to the
logic surrounding whether to run an upgrade and upgrade tests. It now
simply tests if the release name has been set.
> SDCICD-161. Fix cluster image set upgrade logic.

- pkg/upgrade/upgrade.go
If the upgrade image is set, force the upgrade to use that.
If not, if minor versions aren't the same, automatically change the channel to be fast-x.y of the upgrade path and sleep 15 (per the SRE script)
Then attempt the upgrade.
> SDCICD-162 - Automatically update to fast-x.y channel

- pkg/upgrade/upgrade.go
Forgot to pull the latest version of the object after updating the channel. Ugh.
> SDCICD-162: Retrieve latest object

- test/verify/storage.go
Adding a test to verify volume expansion is set correctly as per: https://issues.redhat.com/browse/OSD-2390
During an upgrade [a bug](.https://bugzilla.redhat.com/show_bug.cgi?id=1751641) was introduced where `AllowVolumeExpansion` was unset. This test verifies this value is true on all StorageClasses.
> Add test to verify volume expansion

- test/operators/operators.go
Added a function checkSecrets to verify the presence of one or more secrets.
Tickets OSD-2455 and OSD-2456, concerning the creation of additional operator tests, will both be needing to verify the presence of secrets installed by the operators that are being tested. This commit adds a common function that can be used by future operator tests requiring this ability.
Refs:
https://issues.redhat.com/browse/OSD-2455
https://issues.redhat.com/browse/OSD-2456
> Added checkSecrets assistant function

- Dockerfile
- test/operators/pagerduty.go
Testing if the secrets exist in the target cluster after installation.
Also added `RUN go mod vendor` in the `dockerfile` to fix the image build which was failing.
> Add PagerDuty e2e test and fix dockerfile

- test/operators/deadmanssnitch.go
OSD-2455 concerns the validation of the behaviour of the Hive deadmanssnitch operator to successfully install a secret on a target OSD cluster. This PR adds a test case to verify that the DeadMansSnitch secret has been successfully installed on the target cluster.
> Added DeadMansSnitch operator test case

- Makefile
- configs/log-metrics.yaml
- pkg/e2e/e2e.go
Starting metric generation using five basic but frequently-occurring errors observed.
One note: These metrics do not need to be negative or error metrics: We can generate positive metrics, or whatever we want.
> SDCICD-159: Start generating metrics based on logs

- Makefile
The out directory is now created when building the osde2e binary.
> SDCICD-182. Make sure the out directory is created before building.

- Dockerfile
The osde2e-scale binary no longer exists, so it's been removed from the
Dockerfile.
> Remove osde2e-scale from Dockerfile.

- pkg/common/config/config.go
- pkg/e2e/scale/scale.go
Scale tests were failing because the execution order of configuration
value loading has changed, making the init() call in scale.go execute
prior to loading any configuration values. This has been fixed.
> SDCICD-20. Fix failing scale tests.

- ci/prow_run_tests.sh
The pbench secrets don't look like they're propagating to the scale
tests. This fix will hopefully fix the issue.
Note: I believe this will fix the credentials issue. I believe there is a problem in the openshift-scale repo related to https://github.com/openshift-scale/workloads/commit/69365243a849cdae4e7705da55f0f3cd561dfa83 that is contributing to the scale failures.
> Hopefully fix pbench secrets.

- pkg/e2e/verify/validation_webhook.go
[OSD-2558](https://issues.redhat.com/browse/OSD-2558) concerns adding test cases for the [OSD Managed Cluster Validation Webhook](https://github.com/openshift/managed-cluster-validating-webhooks) app to verify its running presence on OSD clusters.
> Added tests for the OSD Managed Cluster Validation Webhook

- scripts/metrics-sync.sh
An echo statement was not moved with the rest of the logic when adding
in support for new test metrics files.
> SDCICD-190. Move echo into processing block.

- scripts/gate-report.sh
The report name for the generated gate report was interpolated
incorrectly. Additionally, if a report that was not viable was
generated, it would fail the report generation, which was not intended.
> SDCICD-173. Bugfixes for the gate-report.sh script.

- ci/prow_run_tests.sh
The addon tests were broken by the recent scale changes. This will fix
the issue.
> Fix addon tests.

- scripts/gate-report.sh
Gate reports are now generated using a docker image instead of trying to
build the osde2e utility. This is done to ensure there are no golang
version problems.
> SDCICD-173. Use docker image for gate report generation.

- pkg/common/osd/versions.go
- pkg/common/state/state.go
- pkg/e2e/e2e.go
- pkg/e2e/version.go
If a version cannot be found for the middle/oldest imageset test, we
should exit gracefully instead of failing.
> SDCICD-194. Exit gracefully for middle/oldest imageset tests.

- scripts/gate-report-analysis.sh
- scripts/gate-report.sh
The scripts will now always grab the most recent docker image before
running the docker run command.
> SDCICD-174. Scripts should always grab the most recent image.

- scripts/gate-report-analysis.sh
I forgot to substitute $AWS for aws on one line in the
gate-report-analysis script.
> SDCICD-174. Add in missing $AWS substitution.

- pkg/e2e/operators/splunkforwarder.go
This PR adds a test case for the presence and correct configuration of the splunk-forwarder-operator ([OSD-3049](https://issues.redhat.com/browse/OSD-3049)). I've tested it successfully on clusters in both staging and prod so hopefully there should be no issues.
> Add tests for splunk-forwarder-operator

- pkg/common/upgrade/upgrade.go
Release candidates should use the candidate-x.y channel instead of the
fast-x.y channel.
> SDCICD-204. Use candidate-x.y channel for rcs.

- pkg/common/osd/versions.go
- pkg/common/upgrade/releases.go
- pkg/common/upgrade/upgrade.go
- pkg/e2e/version.go
If cluster image sets are not present in Cincinnati, then they will now
be filtered out of electable upgrade versions if trying to use cluster
immge sets.
Additionally, upgrading clusters via Cincinnati has now been excised
since we no longer do that directly. We only use cluster image sets or
the release controller.
> SDCICD-206. Filter upgrade version CISes if they're not in Cincinnati.

- scripts/metrics-sync.sh
Metrics sync has been adjusted to expire the following osde2e jobs
metrics with the following timeouts:
* Regular job metrics expire after 6h.
* Addon jobs metrics expire after 13h.
* Scale jobs metrics expire after 26h.
* Middle/Oldest jobs metrics expire after 26h.
This is to ensure we capture problems with outages more quickly, as the
prod outage that happened on March 10th was missed because our metrics
were expiring after 48h.
> SDCICD-205. Adjust metrics sync expirations

- pkg/e2e/operators/configurealertmanager.go
- pkg/e2e/operators/operators.go
- pkg/e2e/operators/rbac.go
- pkg/e2e/operators/splunkforwarder.go
Fixed operator versions are now being used to test upgrades due the OLM
change where the `Replaces` field is no longer being used.
> SDCICD-210. Use fixed operator versions to test upgrades.

- pkg/e2e/operators/operators.go
The checks that were in place for the Replaces field are now also
removed.
> SDCICD-210. Remove checks for the Replaces field.

- pkg/gate/generate_report.go
generate_report had the number of samples required to generate a
"non-viable" OCP gate too high by one. This has been corrected.
> SDCICD-209. Reduce number of samples needed in generate_report.

- pkg/common/osd/versions.go
- pkg/e2e/setup.go
- pkg/e2e/verify/prom_exporters.go
- pkg/e2e/version.go
The daemonset check in prom_exporters uses the ExtensionV1beta1 API. In
Openshift 4.4.0+, this check should now use the AppsV1 API instead.
> SDCICD-212. Use AppsV1 instead of ExtensionV1beta1 for daemonset check.

- pkg/e2e/operators/configurealertmanager.go
- pkg/e2e/operators/operators.go
- pkg/e2e/operators/rbac.go
- pkg/e2e/operators/splunkforwarder.go
Fixed operator upgrades have are now using more appropriate versions for
the current cluster versions.
Note: Basically just reverted the revert but updated versions. This has been verified against 4.3.0. Trying to verify against 4.4.0 but running into testing issues unrelated to this.
> SDCICD-210. Resubmit fixed operator upgrades.

- pkg/e2e/verify/prom_exporters.go
The machine-api prometheus exporter checks are no longer necessary as
the machine-api exporters are being removed.
> SDCICD-211. Remove prometheus-exporter-machine-api checks.

- pkg/e2e/operators/configurealertmanager.go
- pkg/e2e/operators/rbac.go
- pkg/e2e/operators/splunkforwarder.go
At the moment, it looks like Openshift 4.4 doesn't really have a good
way of returning the previous available version of an operator. We can
use a fixed version rather than try to detect a previously available
version, but it looks like these upgrades take >20 minutes per, and we
have a max limit of 4 hours per test run.
At the moment, we're going to just have to remove these tests until we
figure out a better approach that's compatible with Openshift 4.4.
cc @sedroche
> SDCICD-210. Remove operator upgrade tests.

- pkg/common/osd/versions.go
- pkg/common/osd/versions_test.go
- pkg/e2e/verify/prom_exporters.go
Semver constraints are now being used instead of version comparison for
checking for DaemonSets. This will be clearer. Additionally, the
constraint has been updated to properly accommodate prereleases.
https://github.com/Masterminds/semver#working-with-prerelease-versions
> SDCICD-212. Use semver constraint instead of version comparison.

- pkg/e2e/operators/configurealertmanager.go
- pkg/e2e/operators/operators.go
- pkg/e2e/operators/rbac.go
- pkg/e2e/operators/splunkforwarder.go
This fixes an issue identified in OSD-3141 / SDCICD-210 whereby
once the static previousCSV version got two hops out of date
the test would fail. The fix sets the operator subscription
installplan to automatic once a first manual upgrade hop
has successfully been undertaken.
Additionally the previousCSVs for affected operators have been
updated to the most recent N-1 version.
> Set operator upgrades to automatic after first manual test refs OSD-3141

- Makefile
- configs/app-build-suite.yaml
- pkg/e2e/openshift/app_builds.go
- pkg/e2e/openshift/config.go
This commit introduces tests from the OpenShift image-ecosystem
suite to verify the ability to build and host S2I applications.
Refs [OSD-2132](https://issues.redhat.com/browse/OSD-2132)
> OSD-2132 Introducing tests for Customer Perspective Testing

- Makefile
- configs/app-build-suite.yaml
- configs/e2e-suite.yaml
Due to limitations in the way we parse files, we need to stick with one
e2e suite for now. We'll follow on to see if we can merge YAML files
together and parse.
> SDCICD-215. Stick with one test suite for now.

- pkg/e2e/openshift/app_builds.go
cakephp-mysql and nodejs-mongodb are failing to build on clusters v4.3.0 and older as the required imagestreams are not present. removing the builds until we are on later versions.
Some background info on this is available [at this Jira link](https://issues.redhat.com/browse/OSD-2132?focusedCommentId=14004073&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14004073).
refs OSD-2132
> Removing app builds cakephp-mysql and nodejs-mongodb

- pkg/e2e/operators/operators.go
When testing in staging environments, the number of hops that can potentially be made to upgrade an operator up to the latest version can sometimes exceed the previous polling timeout of 5 minutes. This increases the timeout to 15 minutes which should be a generous enough period to allow an operator
to get back to the latest version.
Refs OSD-3141
> Extend the poll timeout for CSV on operator upgrade checks.

- pkg/e2e/e2e.go
When the helper fails to clean up, ginkgo will panic. This will fix that
panic, as well as prevent the cleanup from running during a dry run.
> Fix ginkgo panic on helper cleanup failure.

- pkg/e2e/state/alerts.go
Due to the previous RBAC/SA PRs, if a test requires elevated permissions we need to explicitly specify it.
> Ensure alert scraper test runs as cluster-admin

- assets/workloads/e2e/redmine/mysql-deployment.yaml
- assets/workloads/e2e/redmine/mysql-pvc.yaml
- assets/workloads/e2e/redmine/mysql-root-secret.yaml
- assets/workloads/e2e/redmine/mysql-secret.yaml
- assets/workloads/e2e/redmine/mysql-service.yaml
- assets/workloads/e2e/redmine/redmine-deployment.yaml
- assets/workloads/e2e/redmine/redmine-pvc.yaml
- assets/workloads/e2e/redmine/redmine-service.yaml
- cmd/osde2e/test/test.go
- pkg/common/helper/workloads.go
- pkg/e2e/workloads/redmine/redmine.go
In support of OSD-2132 to improve customer app testing, this PR adds a new workload to build and host the Redmine web application via a Kubernetes deployment, using persistent storage for both the backend MySQL database service and the frontend web service, and secrets to manage the database credentials.
An initial validation method has been written to check that the service is responding. The deployment should complete within several minutes.
It has been successfully tested on staging and prod CI clusters so far.
If accepted as an additional workload, more sophisticated validation will be added as part of OSD-2132.
Thank you! :)
> OSD-2132 Add Redmine workload

- configs/one-release-from-prod-default.yaml
- configs/two-releases-from-prod-default.yaml
- pkg/common/config/config.go
- pkg/common/osd/versions.go
- pkg/common/osd/versions_test.go
- pkg/e2e/version.go
Fresh installs now can be specified as a delta from the production
default value. As an example:
- Prod default: 4.3, delta 1 == 4.4.0-nightly.
- Prod default: 4.3, delta 2 == 4.5.0-nightly.
- Prod default: 4.4, delta 1 == 4.5.0-nightly.
- Prod default, 4.4, delta 2 == 4.6.0-nightly.
There needs to be a follow on to support upgrades in the same way, but
this will get us half of the way there.
> SDCICD-214. Enable dynamic version selection for fresh installs.

- pkg/e2e/addons/addon_test_harness.go
See here: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/7909/rehearse-7909-periodic-ci-openshift-osde2e-addon-codeready-operator-stage/14/artifacts/install/addon-tests-err.txt
> Bugfix: Grant cluster-admin to addon tests

- pkg/e2e/e2e.go
This creates a separate junit.xml with the contents of log-metrics. This will, in effect, render the work done to generate the log-metrics prom file redundant/obsolete, which is fine. 
The count of observed metrics has been put in the "time" field
> SDCICD-198 - Create junit.xml based on observed log metrics

- configs/nightly-release-for-prod-default.yaml
- configs/upgrade-nightly-release-for-prod-default.yaml
- configs/upgrade-one-release-from-prod-default.yaml
- configs/upgrade-two-releases-from-prod-default.yaml
- pkg/common/config/config.go
- pkg/common/osd/versions.go
- pkg/common/upgrade/releases.go
- pkg/e2e/version.go
Dynamic version selection is now enabled for integration upgrades. Like
dynamic version selection for fresh installs, this allows you to specify
a distance from the current prod default to determine what version of
OCP to upgrade to. This currently only really works for integration, and
it's doubtful this will be expanded unless necessary.
Additionally, the original logic has been modified to support a 0 value
for next release, allowing for the nightly in the current major/minor
version line for the default version in production.
> SDCICD-214. Enable dynamic version selection for upgrades.

- pkg/e2e/e2e.go
The quota check has been moved and additionally skipped during a dry
run. This will allow us to see version selections even if there isn't
enough quota. This will be useful for debugging.
> SDCICD-214. Move quota check.

- pkg/common/osd/versions.go
If a query to OCM fails, we don't get much info back outside of the failure. We don't have access to the raw response, but we can at least log what we do see to aid in debugging.
> Debug: Add info to OCM version query failures

- pkg/common/metadata/metadata.go
-1 should be used as a default for pass rates so that we can filter out
non-existent values.
> SDCICD-235. Use -1 as a default for pass rates.

- pkg/common/upgrade/upgrade.go
- pkg/e2e/e2e.go
- pkg/e2e/setup.go
This should unblock upgrades post-helper-changes and make the state-gathering a bit more stable.
> Bugfix: Relocate cleanup / state gathering. Change helper in upgrade.go

- pkg/e2e/operators/configurealertmanager.go
- pkg/e2e/operators/rbac.go
- pkg/e2e/operators/splunkforwarder.go
The operator upgrade tests are flaking consistently on int and stage,
which makes our full cluster upgrade tests fail to run. We need to
disable these until we can get them more stable.
We will re-enable these once we can introduce test tagging to indicate
that these are known to be flaky.
cc @sedroche
> Disable operator upgrade tests.

- pkg/e2e/workloads/redmine/redmine.go
The redmine workload is frequently timing out, so this increases the
timeout of the redmine workload test to 15 minutes. Additionally, the
timeout waiting for the pods to come up has been increased from 5 to 10
minutes.
> SDCICD-239. Increase redmine timeout.

- configs/only-upgrade-to-z-releases.yaml
- pkg/common/config/config.go
- pkg/common/osd/versions.go
- pkg/common/upgrade/releases.go
- pkg/e2e/e2e.go
- pkg/e2e/version.go
Upgrades can now be restricted to only Z releases, not just the latest
version in the OCM versions endpoint.
Stage will now use fast/candidate channels and production will use
stable. Additionally, we will not attempt to select a version if no
edges exist in Cincinnati for the proposed upgrade.
> SDCICD-237. Cincinnati aware version selection for upgrades.

- pkg/e2e/osd/daemonsets.go
This test creates a daemonset using:
1) No nodeLabel
2) nodeLabel for worker
3) nodeLabel for infra
The criteria in the service definition is now "Create a DaemonSet using the worker NodeLabel" but technically others can be created. I'm testing for all three, and if OSD eventually restricts creation, we can tweak these accordingly.
> SDCICD-201: Test daemonset creation in OSD with various nodelabels

- pkg/e2e/e2e.go
Sets the ginkgo flag to retry a failed test 3 times.
Per Ginkgo, if there's one success it deems the test a success.
> SDCICD-229: Attempt to retry failed tests 3 times

- pkg/common/config/config.go
- pkg/common/osd/cluster.go
- pkg/common/osd/quota.go
- pkg/common/state/state.go
- pkg/e2e/setup.go
- pkg/e2e/verify/prom_exporters.go
GCP clusters will no longer test AWS specific prom exporters.
Additionally, cloud provider configuration has been moved to the state
object, as it can now be populated by osde2e when given a cluster ID.
> SDCICD-242. Don't test AWS specific prom exporters on GCP.

- Makefile
- configs/informing-suite.yaml
- docs/Writing-Tests.md
- pkg/e2e/operators/configurealertmanager.go
- pkg/e2e/operators/rbac.go
- pkg/e2e/operators/splunkforwarder.go
This creates the "informing" test suite. 
Also updates docs regarding the definition of informing as well as some incorrect links after a refactor or two.
> SDCICD-240: Create informing test suite

- pkg/e2e/scale/scale.go
The scale tests now run as privileged workloads, which should solve some
of the issues with the jobs running on GCP.
> SDCICD-249. Make scale tests run as privileged workloads.

- pkg/common/runner/runner.go
Now that runner pods all share a namespace, we now append a 5 character
long random string to the end of pod names to make sure it's unique.
> SDCICD-253. Append random string to pods.

- pkg/common/metadata/metadata.go
- pkg/e2e/e2e.go
Previously, log metrics from the install phase would then be duplicated during the upgrade phase: This is not ideal. Now we zero out the metrics between phases.
Of note: Two metadata files, and thus, logMetric entries, will still be created: One for Install, one for Upgrade.
I'm not 100% sure whether this should occur long-term, but it could provide interesting data being able to diff log metrics between phases.
> SDCICD-256: Zero out log metrics at every phase

- configs/log-metrics.yaml
- Setting EOFs to a high threshold of 6 assuming several instances are acceptable
- Changing "Pending" instances to be up to 20 from GCP observations
- Updating DNS log metric to be more generic / match other errors observed
> SDCICD-254: Tune log metrics further

- pkg/common/osd/healthchecks/certs.go
The certFound flag was not set, which led to longer than expected cert
issued times.
> SDCICD-257. Add in missing certFound flag set.

- pkg/e2e/e2e.go
An idealistic behavior that in retrospect was a mistake.
This will ensure we have some form of upgrade-signal regardless of the results of install-phase testing. 
> SDCICD-269: Run upgrade testing regardless of install phase results

- pkg/e2e/addons/addon_test_harness.go
The failure check was inadvertently type dependent. This has been fixed.
> SDCICD-264. Remove type dependent failure check.

- pkg/common/runner/service.go
LastTerminationState can have a null terminated object apparently -- we
should use the raw state when checking the termination state instead of
using the LastTerminationState.
> SDCICD-264. Use state instead of of last termination state.

- pkg/e2e/osd/nodelabels.go
This test verifies that dedicated-admins cannot update nodeLabels in an OSD cluster.
> SDCICD-222: Add nodeLabel permission check to informing suite

- pkg/common/helper/runner.go
After discovering my very polluted cwd, I realized that I thought
`filename.Base` was the same as `filename.Dir`. Don't ask me how.
Anyway, it's fixed.
> Fix MkdirAll so that it creates the directory and not the filename.

- pkg/common/cluster/clusterutil.go
- pkg/e2e/version.go
During the cluster health wait, if an error occurs when hitting the
provisioner API, an NPE can be hit because the err isn't being checked.
Additionally, when no upgrade candidates are found, the job doesn't
fail, but just fails gracefully (again).
> SDCICD-274. Prevent cluster panic if err occurs in wait.

- pkg/common/runner/service.go
Looks like the scale tests are failing because err.Errors in service.go
doesn't always get populated. Looks like we can just replace this with a
nil check instead.
> Fix scale tests.

- pkg/e2e/e2e.go
Flubbed the order of the args for GenerateDiff
> SDCICD-273: Fix arg order for generatediff

- pkg/debug/diff.go
- pkg/e2e/e2e.go
It's entirely possible aurora is outputting an incorrect color type because it's being concatted and then output. 
Since we aren't doing anything else with the generated diff, we'll just have the GenerateDiff function handle logging out the results per-line.
> SDCICD-273: Have GenerateDiff output directly to the log rather than return a string

- pkg/e2e/version.go
When CLUSTER_VERSION was supplied, it wasn't being returned
appropriately by the setupVersion() function. This has been fixed.
> Fix user supplied CLUSTER_VERSION.

- pkg/common/config/config.go
- pkg/common/state/state.go
- pkg/e2e/e2e.go
- pkg/e2e/version.go
A test can be configured to run N versions prior to the default version.
Since production will soon support running multiple installation
versions on production, this will be necessary to ensure that we have
automated tests for all versions trying to upgrade to the current
default.
> SDCICD-283. Select versions prior to default version.

- pkg/common/cluster/clusterutil.go
- pkg/common/cluster/healthchecks/clusterversionoperator.go
- pkg/common/util/versionutil.go
- pkg/common/util/versionutil_test.go
- pkg/e2e/operators/curator.go
- pkg/e2e/verify/prom_exporters.go
The curator operator tests don't work for clusters under version 4.2.0
at least. The curator operator is being removed, but in the meanwhile,
we'll just disable these tests since they don't work for the 4.1.x line.
If they don't work for the 4.2.x line, we'll deal with that when we come
to it.
> OSD-3551. Disable curator operator tests for Openshift version <4.2.0.

- pkg/e2e/metrics.go
- pkg/e2e/metrics_test.go
This ensures every metric produced also has the job ID, cluster ID, and cloud provider as a label.
The frequency at which we generate metrics should not cause a performance impact with these changing/unique labels, and will help us with both debugging and long-term trending queries.
> SDCICD-244: Add cloud provider, job id, and cluster id, in all metrics

- pkg/common/cluster/clusterutil.go
- pkg/common/state/state.go
- pkg/e2e/e2e.go
This creates a state variable that updates during cluster-readiness-check.
If the cluster state is not "Installed" it assumes that dependencies cannot get gathered.
> SDCICD-??? Check for cluster state before attempting dependency gather

- pkg/e2e/e2e.go
It looks like the log metrics reset was inadvertently directly after
collecting the log metrics, which was causing all log metrics to be zero
all the time. This has been moved.
> SDCICD-313. Move log metrics reset before the calculation.

- pkg/e2e/version.go
If the install version can't be found while trying to perform an
upgrade, we'll get a null pointer exception. This fixes that problem.
> SDCICD-283. Fix version NPE.

- pkg/common/config/config.go
- pkg/e2e/e2e.go
This PR proposes the addition of a "mustGather" toggle for occasions where it's not necessary to collect Must-Gather data; for example, when doing test development and not needing to wait the time needed for Must-Gather to complete.
The toggle defaults to on, so disabling the behaviour would be an opt-in.
> Added option to toggle must-gather

- pkg/common/providers/ocmprovider/cluster.go
New clusters will be tagged with two new tags when being launched:
* MadeByOsdE2E to distinguish clusters that are created by osde2e.
* OwnedBy with a value of the current system user to distinguish who has
created the cluster, or at least provide some idea of who has done so.
> SDCICD-315. Add in new cluster property tags.

- pkg/common/helper/helper.go
- pkg/common/upgrade/upgrade.go
- pkg/e2e/e2e.go
Whenever helper.OutsideGinkgo is called, we should ensure helper is aware that it may not have some of the ginkgo error handling properties.
Also while running checks against this change, I had to refactor a couple things in order to get under `gocyclo`'s (seemingly arbitrary) check. 
Now, it will always attempt to generate a diff (regardless of if you're in Prow or not) and return an error if it fails (which seems fine for this case.)
> SDCICD-289: Change error handling depending on whether helper is in ginkgo or not.

- pkg/debug/diff.go
If we see a 404 (or really anything-not-200) status from the bucket browser, return an error rather than attempt to generate a diff.
> SDCICD-316: Check for error message before generating diff

- pkg/common/config/config.go
- pkg/common/providers/ocmprovider/cluster.go
It looks like, on prow, user.Current() fails. Now, if a BUILD_NUMBER is
detected, it's assumed we're running on prow. This should prevent
failures when running on prow.
> SDCICD-315. Restore cluster properties with Prow specific logic.

- pkg/e2e/state/alerts.go
- pkg/e2e/state/alerts_test.go
In integration, this alert fires with every test (OSD-3300). This is a
known problem, but does not otherwise effect the quality of an OSD
cluster in integration. We should ignore this alert for now until
OSD-3300 is fixed.
> SDCICD-321. Ignore the MetricsClientSendFailingSRE alert in int.

- scripts/shellcheck.sh
Fetch the correct tarball based on the operating system and
architecture.
Fixes #391 
- Macbook
- Fetch the repo using `git clone`
- Run `make check`
```bash
/Users/drpaneas/gocode/src/github.com/openshift/osde2e/scripts/shellcheck.sh: line 9: /Users/drpaneas/gocode/src/github.com/openshift/osde2e/scripts/shellcheck-stable/shellcheck: cannot execute binary file
make: *** [check] Error 126
```
--> Issue has been reproduced
```bash
x shellcheck-stable/README.txt
x shellcheck-stable/LICENSE.txt
x shellcheck-stable/shellcheck
No files specified.
```
--> Issue is fixed.
> Optimize shellcheck tarball fetch

- pkg/common/upgrade/upgrade.go
- pkg/common/util/versionutil.go
- pkg/common/versions/common/utils.go
- pkg/common/versions/common/utils_test.go
- pkg/common/versions/installselectors/default_version.go
- pkg/common/versions/installselectors/interface.go
- pkg/common/versions/installselectors/latest_version_selector.go
- pkg/common/versions/installselectors/middle_cluster_image_set.go
- pkg/common/versions/installselectors/next_version_after_prod_default.go
- pkg/common/versions/installselectors/oldest_cluster_image_set.go
- pkg/common/versions/installselectors/previous_release_from_default.go
- pkg/common/versions/installselectors/registry.go
- pkg/common/versions/installselectors/utils.go
- pkg/common/versions/upgradeselectors/cincinnati_version.go
- pkg/common/versions/upgradeselectors/interface.go
- pkg/common/versions/upgradeselectors/registry.go
- pkg/common/versions/upgradeselectors/release_controller_version.go
- pkg/common/versions/version_selector.go
- pkg/e2e/e2e.go
- pkg/e2e/version.go
The version selection logic has been refactored. The version selection
logic is complex, so it's been split out into a number of different
version selectors. These version selectors should be easier to test
independently, which will give us more confidence overall in our version
selection logic.
> SDCICD-311. Refactor version selection logic.

- pkg/e2e/verify/prom_exporters.go
- pkg/e2e/verify/user_webhook.go
This PR addresses two minor nits:
- The "user validating webhook" test has been moved out of the operators package and into verify (it is not operator related), and renamed to explicitly identify as a user validating webhook test to better distinguish it from other webhook tests.
- The variables in the "prometheus exporter" test have been moved out of package scope and into the test scope. This will help prevent accidental use of the variables in other "verify" package files.
> Fix minor nits in User Validating Webhook and Prom Exporter tests

- pkg/e2e/verify/namespace_webhook.go
This adds a new test for verifying the behaviour of the [namespace validating webhook](https://github.com/openshift/managed-cluster-validating-webhooks/).
Refs: [OSD-3623](https://issues.redhat.com/browse/OSD-3623)
> Add tests for namespace validation webhook

- pkg/common/config/config.go
Two environment variables were misnamed. This has been corrected.
> SDCICD-250. Fix environment variables.

- pkg/e2e/osd/dedicatedadmin.go
Adds a test to ensure that members of the dedicated-admin group cannot alter the cluster-admins group.
Refs: OSD-3570
> OSD-3570 test dedicated-admin permissions

- README.md
- cmd/osde2e/helpers/helpers.go
- cmd/osde2e/test/cmd.go
- pkg/e2e/e2e.go
This PR integrates the work of #399 and #400 to allow the ability to specify some test-related configuration parameters via the CLI. 
Parameters selected were based on personal preferences of ones I change/use frequently, these can also be viewed via `osde2e test --help`:
- cluster ID
- OCM provider environment
- kube config path
- tests to focus
- tests to skip
- skip health checks
- destroy after test
As an example:
`osde2e test --configs informing-suite --environment int --cluster-id 1ddkj9cr9j908gdlb1q5v6ld4b7ina5m --focus="namespace validating" --skip-health-check`
The README has also been updated to include an example.
> Add viper config integration on CLI for test subcommand

- pkg/common/config/config.go
The metrics upload key was a victim of a bad copy/paste job.
> Fix metrics upload.

- pkg/common/cluster/healthchecks/clusterversionoperator.go
- pkg/common/cluster/healthchecks/clusterversionoperator_test.go
- pkg/common/cluster/healthchecks/nodes.go
- pkg/common/cluster/healthchecks/nodes_test.go
- pkg/common/cluster/healthchecks/operators.go
- pkg/common/cluster/healthchecks/operators_test.go
- pkg/common/cluster/healthchecks/pods.go
- pkg/common/cluster/healthchecks/pods_test.go
Upon review, there were a couple conditions where a cluster readiness check would fail silently or incorrectly.
This makes certain conditions return errors that should be visible during the readiness check.
/assign @meowfaceman 
/cc @cblecker
> SDCICD-330: Fail cluster readiness checks more loudly

- pkg/e2e/operators/rbac.go
It looks like the RBAC upgrade test is failing frequently on stage. This
needs to be reverted back to informing.
> Revert RBAC upgrade test to informing.

- pkg/e2e/operators/configurealertmanager.go
- pkg/e2e/operators/rbac.go
- pkg/e2e/operators/splunkforwarder.go
This PR bumps the previousCSV values used for operator upgrade tests in the RBAC, Configure-Alertmanager and Splunk-forwarder operators. This should hopefully reduce the timeouts being observed during these tests due to the number of version-hops needed to get back to the latest CSV.
Refs: #413 where this was most recently observed.
> Bumping previousCSV values for operator upgrade tests

- ci/prow_run_tests.sh
- ci/prow_setup.sh
- pkg/common/aws/s3.go
- pkg/common/aws/session.go
- pkg/e2e/e2e.go
At the moment, MOA can only be provisioned using AWS environment
variables. This alters things such that metrics now uses static AWS
credentials as opposed to using environment variables to make room for
MOA's use of the AWS environment variables.
Note: The various MOA/Metrics secrets are already in place in origin CI.
> SDCICD-297. Alter metrics AWS parsing to support MOA pipelines.

- cmd/osde2e/common/configs.go
- cmd/osde2e/query/cmd.go
- cmd/osde2e/test/cmd.go
- cmd/osde2e/weather/cmd.go
- cmd/osde2e/weather_slack/cmd.go
- configs/moa.yaml
- pkg/common/aws/session.go
- pkg/common/config/config.go
- pkg/common/load/load.go
- pkg/common/providers/moaprovider/cluster.go
- pkg/common/providers/moaprovider/config.go
- pkg/common/providers/moaprovider/util.go
- pkg/common/providers/ocmprovider/config.go
Secret gathering is now handled by osde2e. This is the first step in
removing our reliance on scripting glue, which should make our job
definitions simpler.
Some refactoring was done to MOA to ensure that we'd be able to remove
the prow_run_tests.sh script.
> SDCICD-200. Handle secret gathering within osde2e.

- ci/prow_run_tests.sh
The prow script now exports MOA variables so as not to break things.
Note; This is a stop gap until we can get the jobs adjusted in the openshift/release repo.
> SDCICD-200. Export MOA variables in prow script.

- pkg/common/config/config.go
- pkg/common/load/load.go
In order to reduce the amount of scripting we'll have to do around the
ARTIFACTS environment variable in prow jobs, we'll just have our own
notion of ARTIFACTS to work with that will override the REPORT_DIR.
> SDCICD-200. Add in ARTIFACTS config.

- pkg/e2e/operators/curator.go
Curator tests are now skipped for MOA clusters.
Note: I'm not really able to test this well because I'm hitting 403 issues with my new OCM token, but I'm fairly confident in it.
> SDCICD-335. Skip curator tests for MOA clusters.

- go.mod
- go.sum
- pkg/common/config/config.go
- pkg/common/metadata/metadata.go
- pkg/e2e/e2e.go
- pkg/e2e/routemonitors/routemonitors.go
- pkg/e2e/workloads/guestbook/guestbook.go
- pkg/e2e/workloads/redmine/redmine.go
**About**
This PR presents a first cut at implementing [OSD-3680](https://issues.redhat.com/browse/OSD-3680) to perform and present 
monitoring of important routes during an OpenShift upgrade.
The PR introduces a `RouteMonitors` package which, when used, will automatically detect and monitor the following routes to ensure they continue to respond to HTTP GET requests:
- API servers
- OAuth
- Web Console
- Any OSDE2E workloads with routes
The `redmine` OSDE2E workload has been updated as part of this PR to now create a route that can hence be monitored.
Monitoring of routes is being performed using `vegeta` - this has been added as a new go module dependency.
**Configuration**
The route monitor process can be controlled through the MonitorRoutesDuringUpgrade configuration option (and …
> OSD-3680 Add route monitoring during upgrades

- pkg/common/load/load.go
It looks like secrets are getting munged by leading/trailing whitespace,
which we should strip off.
> SDCICD-200. Trim leading/trailing whitespace from secrets.

- pkg/e2e/routemonitors/routemonitors.go
Observed in CI job 1271955636241829888 that when a cluster fails to become ready, the routemonitors (OSD-3680) were triggering a panic as the helper they use is nil.
This commit should at least address the panic behaviour so that the execution of the remainder of the osde2e run continues normally.
> Safe handling of helper in routemonitor code

- cmd/osde2e/alert/cmd.go
- cmd/osde2e/main.go
- go.mod
- go.sum
- pkg/common/alert/alert.go
- pkg/common/config/alerts.go
- pkg/common/config/config.go
- pkg/common/prometheus/connect.go
- pkg/e2e/osd/daemonsets.go
This is the foundation for fine-grained alerting on test failures (SDCICD-294). 
Currently, this only supports alerting via Slack. Emails will eventually be supported. 
Using our daemonset tests as an example, we define the alert as part of the whole test definition. If, within a 24h period, a failure threshold is met, this will alert the specified slack channel.
I moved some code around (mainly the WeatherRoundTripper) so it could be reused.
> SDCICD-294: Define per-ginkgo-context alerting mechanism

- configs/ocm-aws-compute-optimized.yaml
- configs/ocm-aws-memory-optimized.yaml
- configs/ocm-gcp-compute-optimized.yaml
- configs/ocm-gcp-memory-optimized.yaml
- pkg/common/providers/ocmprovider/cluster.go
- pkg/common/providers/ocmprovider/config.go
Adds the option `ocm.computeMachineType` which we can use on cluster-creation. This is currently specific to OCM (and I think that's okay for now)
Also adds compute and memory optimized configs for AWS and GCP to be used in periodic jobs.
> SDCICD-183: Support cluster creation with custom compute machine types

- cmd/osde2e/cleanup/cmd.go
- cmd/osde2e/main.go
- pkg/common/providers/crc/crc.go
- pkg/common/providers/moaprovider/wrapped_calls.go
- pkg/common/providers/mock/mock.go
- pkg/common/providers/ocmprovider/cluster.go
- pkg/common/spi/provider.go
- Adds a ListClusters command to the SPI interface. The ListClusters query arg is a SQL-like command to mirror the OCM search method.
- Created an ocmToSPICluster internal method to convert the list of clusters returned.
- Stubs out ListClusters in the other providers
- Adds a `cleanup` command to osde2e. Based on a standard osde2e run/config, it will list OSDe2e clusters in the specified environment and issue a provider delete command if they're expired.
:taco: :taco: :taco: :taco:
> SDCICD-341: Add provider list method, cleanup cluster command

- pkg/common/cluster/clusterutil.go
Added checking and handling of errors when fetching the cluster details from the cluster provider.
This was observed to be causing an osde2e panic during CI runs.
> Handle errors fetching cluster details from provider

- configs/region-random.yaml
- pkg/common/providers/ocmprovider/cluster.go
This will allow us to set a cloud provider region to "random". This queries and pulls a random region from OCM, given a cloud provider.
> SDCICD-343: Support setting ocm region to 'random'

- scripts/check-vendor.sh
The Makefile will now (non-destructively) check to make sure that the
vendor directory is up to date.
> Check if the vendor directory is up to date.

- Makefile
The various make targets that have been focused on running osde2e and
its various tests have been removed. Now that the prow test runner has
been removed, job running in prow is much more explicit. We expect that
people running osde2e manually will use an actual osde2e binary from
here on out.
> SDCICD-200. Remove e2e focused make targets.

- pkg/common/helper/helper.go
- pkg/common/helper/projects.go
- pkg/e2e/e2e.go
This PR runs an `oc adm inspect` on the OSDE2E test project namespace at the completion of an `osde2e` run.
The output is saved in a file `osde2e-project.tar.gz` in the `install` directory of the `osde2e` test output.
The contents of this file can be used either in conjunction with the `must-gather` or in isolation in order to better understand the state of the `osde2e` project upon completion of the test. This can be useful for providing better context around why a test may have failed to pass when conducting follow-up analysis.
> Add gather of test project state at end of run

- pkg/common/cluster/clusterutil.go
Cluster health checks will now fire for MOA clusters.
> SDCICD-354. Make sure cluster health checks fire for MOA clusters.

- pkg/common/config/config.go
- pkg/common/versions/installselectors/delta_release_from_default.go
Install versions can now be specified as a delta from the default in
either direction.
> SDCICD-357. Support install version delta from default.

- pkg/common/versions/installselectors/delta_release_from_default.go
When going forward while selecting a version delta relative to the
default, it's possible to go off the end of the version array.
> SDCICD-357. Handle version out of bounds error.

- pkg/common/providers/ocmprovider/cluster.go
This will now loop through a given region list and, upon the first enabled (random) region, break out of the loop.
We limit the loop to the length of the list to prevent an infinite loop. The likelihood of hitting a disabled region given the list is possible, but remote.
> SDCICD-363: Only use enabled regions

- pkg/e2e/e2e.go
Prow Spyglass picks up all logs named "build-log.txt," which makes our
job dashboards look really noisy. We'll just restore the old name of
test_output.log in order to reduce the duplicative display in Spyglass.
> SDCICD-364. Rename report dir build log to reduce prow job noise.

- pkg/e2e/osd/machinehealthcheck.go
LabelSelector is a map[string]string and couldn't match against a string
without being indexed into
> fix the LabelSelector for the test verifying MachineHealthCheck presence

- pkg/e2e/scale/mastervertical.go
The number of nodes to scale to has been reduced to try to get scale
tests working.
> Reduce scale count to try to get scale tests working.

- pkg/e2e/osd/machinehealthcheck.go
This timeout is expected to contain the s for seconds. See https://github.com/openshift/managed-cluster-config/blob/master/deploy/osd-machine-api/011-machine-api.srep-worker-healthcheck.MachineHealthCheck.yaml#L10-L16.
> Fix Timeout comparison

- pkg/common/config/config.go
- pkg/debug/diff.go
- pkg/e2e/e2e.go
Looking up job history is a different URL from the baseJobURL (which was a mistake on my part)
This adds a baseProwURL, sets it, and refactors some variable names a bit.
> SDCICD-362: Differentiate between prow URL and gcs URL

- pkg/metrics/addon_metadata.go
- pkg/metrics/addon_metadata_test.go
- pkg/metrics/client.go
- pkg/metrics/client_test.go
- pkg/metrics/events.go
- pkg/metrics/events_test.go
- pkg/metrics/junitresult.go
- pkg/metrics/junitresult_test.go
- pkg/metrics/metadata.go
- pkg/metrics/metadata_test.go
- pkg/metrics/objects.go
- pkg/metrics/objects_test.go
All objects in the metrics library are now sorted by timestamp in a
descending order. Additionally, interfaces have been added that will
allow for reverse sorting/arbitrary sorting of metrics objects.
> SDCICD-372. Sort objects by timestamp.

- pkg/common/prometheus/connect.go
- pkg/metrics/client.go
The metrics client can now be supplied with Prometheus credentials in
order to connect to a Prometheus server.
> SDCICD-368. Supply prometheus credentials for metrics client.

- pkg/e2e/e2e.go
Cluster ID was mistakenly left out of being set in viper after a cluster
provision.
> SDCICD-371. Set cluster ID after cluster provision in e2e.

- pkg/e2e/operators/managedvelero.go
As this operator is now deployed via OLM, some of its objects are now deployed with automatically generated names, making some of these verifications non-functional as they are written.
I've updated the tests to reflect the statically created objects.. but we should probably create some better test templating around OLM operators.
> Update managed-velero-operator tests

- pkg/e2e/e2e.go
Logging output is now restored after the tests run.
> Restore top level logging after test failure.

- Dockerfile
Our docker image will now include the osde2ectl binary.
> SDCICD-383. Bake osde2ectl into our Docker image.

- pkg/e2e/osd/ocm.go
This metrics endpoint is returning nil and causing noisy signal. This should clean up the Informing signal for the OCM test. :)
> SDCICD-334: Remove missing endpoint

- pkg/common/providers/ocmprovider/cluster.go
- pkg/common/providers/ocmprovider/config.go
The username used for a properties tag can now be overridden. This will
be useful for the scale test job, which runs in Docker and will have a
"root" username. This will allow us to specify exactly what the username
should be and tailor it for the job.
> SDCICD-383. Add in an OCM user override for properties tagging.

- pkg/e2e/operators/operators.go
OLM operator upgrade testing was running into a condition where a subscription would still exist when trying to create a new subscription object.
This ensures that the object has been deleted (or times out) before the new subscription is created.
> SDCICD-389: Wait for subscription deletion before creating a new subscription

- pkg/common/cluster/healthchecks/clusterversionoperator.go
- pkg/common/cluster/healthchecks/machines.go
The machine status comparison was inadvertently checking pointer
addresses instead of values.
> SDCICD-352. Fix machine status comparison.

- pkg/common/cluster/healthchecks/machines.go
Occasionally phase can be nil, so we need to handle this possibility.
> SDCICD-352. Handle nil panic.

- pkg/common/cluster/healthchecks/machines.go
If the phase is nil for a machine, it should be considered not ready.
> SDCICD-352. Recognize a machine as not ready if the phase is nil.

- pkg/e2e/operators/configurealertmanager.go
- pkg/e2e/operators/rbac.go
- pkg/e2e/operators/splunkforwarder.go
Operator upgrade tests are very flaky across the environments, so
they've been moved back to informing.
> SDCICD-394. Move operator upgrade tests to informing.

- cmd/osde2ectl/create/cmd.go
The timeout channel shoudl only be closed until after the signal has
been sent. Even if there's nothing listening for it, this should prevent
a panic.
> SDCICD-395. Don't close the timeout channel until the signal is sent.

- cmd/osde2ectl/create/cmd.go
- pkg/common/cluster/clusterutil.go
Batch clusters will now all have unique names during creation.
> SDCICD-397. Ensure that batch clusters have unique names.

- pkg/e2e/state/prometheus.go
The command(s) we send to collect and ship the Prometheus data had both faulty logic and an incorrect redirect.
This fixes it and restores collect-prometheus data.
> SDCICD-396: Fix prometheus dump generation command

- cmd/osde2ectl/get/cmd.go
A fix to make sure cluster expiry time is extended by default only if the cluster expiry time is less than or equal to 30 minutes while the cluster's kubeconfig is being retrieved.
> Modified cluster expiry extension while retrieving kubeconfig 

- docs/Addons.md
- pkg/common/config/config.go
- pkg/e2e/addons/addon_test_harness.go
This allows the addon authors to run their test harnesses as a specific user in-cluster.
The default stays the same (cluster-admin) however they can now specify other-existing users. We do not support creation of a user at this time.
> SDCICD-375: Allow test harness user to be configurable

- cmd/osde2ectl/create/cmd.go
Looks like, unbeknownst to me, closing channels isn't strictly necessary
in go. If nothing is waiting on or listening to the cluster any more, it
looks like these will be garbage collected. I'm removing the channel
close logic because I think it's an avenue of potential panics, and
hopefully this fixes any of the latent batch provisioning failures I've
seen.
> Remove channel close from batch cluster wait.

- pkg/common/providers/moaprovider/cluster.go
- pkg/common/providers/ocmprovider/cluster.go
Clusters can now be provisioned without an expiration set if the cluster
expiry time is 0 or less.
> SDCICD-399. Allow clusters to skip expiration setting.

- docs/Metrics-Client.md
This is a start/first pass at the metrics consumption library docs. For the most part, writing examples of data structures and all the methods in here would be redundant, and the godoc/comments we have provide a decent direction.
> SDCICD-369: Add docs on the metrics library

- pkg/e2e/state/alerts.go
There is a chance the cluster is actually healthy, but the alerts haven't cleared. Therefore we should wrap the alert-check in an `Eventually` block.
> SDCICD-409: Retry checking for cluster alerts

- pkg/common/versions/installselectors/common_test.go
- pkg/common/versions/installselectors/default_version_test.go
- pkg/common/versions/installselectors/delta_release_from_default_test.go
- pkg/common/versions/installselectors/latest_version_selector.go
- pkg/common/versions/installselectors/latest_version_selector_test.go
- pkg/common/versions/installselectors/middle_cluster_image_set.go
- pkg/common/versions/installselectors/middle_cluster_image_set_test.go
- pkg/common/versions/installselectors/oldest_cluster_image_set.go
- pkg/common/versions/installselectors/oldest_cluster_image_set_test.go
- pkg/common/versions/installselectors/utils.go
Version selector unit tests have been added to ensure that, if we muck
with the logic of OSDe2e version selection in the future, we are able to
verify/validate the existing behavior to ensure we don't break anything.
Upgrade selectors have not been tested due to their reliance on
Cincinnati/the release controller.
> SDCICD-346. Add in version selector unit tests.

- pkg/metrics/junitresult.go
- pkg/metrics/junitresult_test.go
Upgrade failures as returned by the metrics library will now more
accurately reflect that the entire suite of upgrade tests has failed as
opposed to just one singular test failure. For instance, let's look at
the following example data:
* [install] test1 PASS
* [install] test2 PASS
* [install] test3 PASS
* [install] test4 PASS
* [upgrade] BeforeSuite FAILURE
If we're only taking test failures into account, this looks like an 80%
pass rate. However, in reality, what's happened here is that the install
suite of 4 tests passed and then the entire suite of upgrade tests
failed to run. This means that the pass rate should really be 50% (4
passing install tests + 4 failing upgrade tests).
Occasionally it looks like [upgrade] BeforeSuite test can fail but
upgrade tests do, in fact, run. If this …
> SDCICD-380. Tweak passrates for upgrade failures.

- pkg/e2e/operators/configurealertmanager.go
- pkg/e2e/operators/rbac.go
- pkg/e2e/operators/splunkforwarder.go
- pkg/e2e/osd/machinehealthcheck.go
- pkg/e2e/verify/namespace_webhook.go
These jobs have a clean track record for over a week and should be promoted up from informing. 
Some of them involved moving the upgrade operator tests out of a separate Describe block and under the existing one. :)
> SDCICD-376: Promote stable informing jobs

- pkg/common/cluster/clusterutil.go
- pkg/common/events/event_type.go
- pkg/common/providers/ocmprovider/cluster.go
- pkg/e2e/e2e.go
If the cluster health check fails, we'll now still display the cluster
ID/cluster region/etc. if we can. We do this by updating cluster
metadata if we can provision the cluster at all, but still fail if the
health check fails.
> SDCICD-415. Display available metadata in on health failure.

- pkg/common/cluster/clusterutil.go
- pkg/e2e/e2e.go
There's no reason to have cluster version info in the cluster name, and
it's causing issues with cluste name length. It has been removed.
Additionally, the suffix has been bumped to 5 characters to reduce the
possibility of cluster name collisions.
> SDCICD-417. Remove version info from cluster name.

- pkg/e2e/e2e.go
Health checks were not actually making an assertion on the error seen by
WaitForClusterReady.
> Fix health checks.

- pkg/common/runner/runner.go
- pkg/e2e/scale/scale.go
The scale pod logs display more sensitive data than we expected. We are
no longer collecting pod logs for scale tests.
> SDCICD-434. Stop collecting pod logs for scale tests.

- pkg/e2e/e2e.go
- pkg/e2e/metrics.go
- pkg/e2e/routemonitors/routemonitors.go
This collects and stores the route results in Prometheus in a new metric: `cicd-route`
In the process, I ran into/resolved three issues:
1. Prometheus metrics were generated before the route monitors closed.
2. There was a race with the route monitor channels closing (cc @mrbarge )
3. At times, the routemonitor values would return NaN, so began defaulting values to 0.
> SDCICD-339: Store route metrics in Prometheus

- scripts/granular-alerting.sh
This updates the script to expect the `SLACK_API_TOKEN` environment variable to be loaded via vault.
> SDCICD-296: Update slack token env var

- docs/Addons.md
- pkg/common/config/config.go
- pkg/common/helper/addons.go
- pkg/e2e/addons/addon_test_harness.go
- pkg/e2e/e2e.go
This adds the `ADDON_CLEANUP_HARNESSES` config option and updates the docs to support it.
> SDCICD-437: Support separate addon cleanup harnesses

- pkg/common/providers/ocmprovider/cluster.go
When trying to add a property to an existing cluster, if there are no
existing cluster properties, osde2e will faulter. We now create our our
properties map, which should fix our testing against existing clusters.
> SDCICD-435. Create cluster properties if there are none.

- pkg/e2e/verify/loadbalancers.go
This test simply verifies the existence of two OSD focused load
balancers.
> SDCICD-219. Add in load balancer tests.

- README.md
- pkg/common/config/config.go
This PR removes all references to the old `make test` usage and updates the docs with the current style of how to run `osde2e` locally. 
As config options are bountiful, it also updates the config package with inline-comments of their environment variables. This should clear up most questions when writing a local script that uses environment variables, and also show up in the godoc (eventually)
cc @cblecker
> SDCICD-420: Update docs removing makefile references, add more config context

- pkg/common/providers/crc/crc.go
- pkg/common/providers/moaprovider/wrapped_calls.go
- pkg/common/providers/mock/mock.go
- pkg/common/providers/mock/mock_test.go
- pkg/common/providers/ocmprovider/cluster.go
- pkg/common/providers/ocmprovider/flavour.go
- pkg/common/providers/ocmprovider/quota.go
- pkg/common/spi/provider.go
- pkg/e2e/e2e.go
Viper apparently isn't entirely thread safe. So I removed the need for it entirely. 
It required a minor refactor of our quotaCheck method, which now expects a `flavour` argument.
> Move quota check to launch method, remove need for viper.set

- cmd/osde2ectl/create/cmd.go
- pkg/common/cluster/clusterutil.go
- pkg/common/providers/crc/crc.go
- pkg/common/providers/moaprovider/wrapped_calls.go
- pkg/common/providers/mock/mock.go
- pkg/common/providers/ocmprovider/cluster.go
- pkg/common/spi/provider.go
- pkg/common/upgrade/upgrade.go
- pkg/e2e/e2e.go
- Refactor `PollClusterHealth` to return an array of failures (abbreviated, ie CheckCVOReadiness would be "cvo")
- Refactor `AddProperty` to expect an `*spi.Cluster` object instead of a ClusterID (This cuts down on OCM calls significantly)
- Update the Cluster Status property at every failure change from PollClusterHealth
- Create / Upload a prometheus file to our metrics inbox S3 bucket for processing (current job processes every 5min)
> SDCICD-454/455: Return list of failing checks, update cluster property / metrics with it

- pkg/common/providers/ocmprovider/versions.go
This is a temporary fix to unblock some pipelines while we build more robust support for channel groups in versions.
> SDCICD-482: Only look at stable channels in stage/prod

- pkg/common/runner/command.go
python3 is the version used in rhel8 images
for SDCICD-484
> SimpleHTTPServer has been merged into http.server in python3

- pkg/common/clusterproperties/properties.go
- pkg/common/config/config.go
- pkg/common/providers/ocmprovider/cluster.go
Added support for pinning OCM cluster to a hive shard using osde2e.
> Provision shard for OCM cluster through osde2e

- pkg/e2e/osd/ocm.go
Removed the count check for nodes during an OCM metrics test on a created cluster.
> Removed node check for OCM metrics test

- pkg/common/upgrade/upgrade.go
This PR corrects an issue whereby the `managed-upgrade-operator`'s E2E-tailored configmap may get overridden by a Hive sync mid-upgrade. 
The configmap is now checked and (only if needed) corrected during OSDE2E's repeated "is the upgrade finished" checks, so that even if it is replaced by a Hive sync it will be quickly corrected with the overriding values.
> OSD-5292 always be overriding managed-upgrade config

- pkg/common/providers/ocmprovider/cluster.go
Fixed improper date formatting in the cluster extend expiry output for osde2ectl. The hour and year fields are properly populated now.
> Date format fix during cluster expiry extend

- pkg/common/upgrade/managed.go
- pkg/e2e/operators/managedupgrade.go
`managed-upgrade-operator` now standardizes on a `UpgradeConfig` CustomResource name of `osd-upgrade-config`. When this change was made, it caused E2E upgades to no longer occur because E2E was creating a CR name of `osde2e-upgrade-config`. 
This PR rectifies this so that E2E will now create a CR with the expected name which will allow upgrades to occur.
> Rename managed-upgrade CR name

- pkg/e2e/operators/cloudingress/apischeme_cr.go
- pkg/e2e/operators/cloudingress/publishingstrategies_cr.go
In this commit, I added tests to verify that dedicated admin can't create an apischeme CR and cluster admin can.
> Added dedicated admin Apischeme CR tests; corrected typo in publishingstrategies.go

- cmd/osde2ectl/create/cmd.go
- pkg/common/providers/ocmprovider/cluster.go
- pkg/common/providers/ocmprovider/config.go
- Adds AWS account configs to the OCM Provider
- Creates `aws-accounts-file` argument to `osde2ectl create` to supply multiple accounts during cluster creation
- Mutex is used for modifying the OCM AWS account configs between cluster creation to prevent `viper.Set` concurrent read/write error
> SDCICD-502: Support AWS CCS clusters and support supplying a list of AWS accounts for multi-cluster testing

- pkg/common/providers/crc/crc.go
- pkg/common/providers/moaprovider/wrapped_calls.go
- pkg/common/providers/mock/mock.go
- pkg/common/providers/ocmprovider/cluster.go
- pkg/common/spi/provider.go
- pkg/common/upgrade/managed.go
This PR increases the Pod Disruption Budget timeout for upgrades from 5 minutes to 15, as '15' is now the minimum value enforced by OCM when scheduling an upgrade. The maximum node drain time was increased to 15 accordingly.
This should correct job errors such as [this](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/osde2e-stage-aws-e2e-upgrade-default-next/1320878116121350144).
Fixes [OSD-5674](https://issues.redhat.com/browse/OSD-5674)
> Increase PDB timeout duration for upgrades

- pkg/e2e/verify/regularuser_webhook.go
[OSD-5447](https://issues.redhat.com/browse/OSD-5447) - Extending webhook validation E2E testing
> Adding regularuser_webhook.go

- pkg/common/providers/ocmprovider/cluster.go
- pkg/common/upgrade/managed.go
This corrects the issue identified in [OSD-5692](https://issues.redhat.com/browse/OSD-5692)
The call to Upgrade() now returns a http.StatusCreated. This, in conjunction with the fact that Error() in the SDK is 'nil', resulted in a panic when Error().String() was called.
The code around restarting the upgrade operator during the upgrade scheduling was also made slightly more robust to combat a niche issue where `object has been modified` was being reported when patching the `deployment`, using retries.
> OSD-5692 fix panic during upgrade scheduling

- pkg/e2e/operators/operators.go
- vendor/k8s.io/client-go/util/retry/OWNERS
- vendor/k8s.io/client-go/util/retry/util.go
- vendor/modules.txt
This PR attempts to fix several issues around sporadic failures of the operator "should upgrade from previous version" test. This affected the `configure-alertmanager-operator`, `splunk-forwarder-operator` and `rbac-permissions-operator`.
Some issues were identified:
- Updating the `subscription` could occasionally return `object has been modified`, so it's now surrounded in a `RetryOnConflict` block.
- Instead of incrementally approving `InstallPlan`s, the test was occasionally approving multiple (a race condition dependent on a delay when approving the first), which caused it to then get stuck in a holding pattern looking for a `ClusterServiceVersion` that didn't exist.
Refs [OSD-5252](https://issues.redhat.com/browse/OSD-5252)
> OSD-5252 fix occasional operator upgrade test errors

- pkg/common/cluster/clusterutil.go
- pkg/common/providers/crc/crc.go
- pkg/common/providers/moaprovider/cluster.go
- pkg/common/providers/mock/mock.go
- pkg/common/providers/mock/mock_test.go
- pkg/common/providers/ocmprovider/cluster.go
- pkg/common/spi/provider.go
Checks if proposed cluster name exists before attempting to launch
cluster.
Will fail after 10 attempts to validate name. Can fail due to a
combination of 10 failure of duplicate names and/or OCM errors upstream
Ideally when this actually fails, it indicates we have much larger
issue that needs addressing.
> Fixes SDCICD-513 duplicate clusterName upon create

- pkg/e2e/operators/cloudingress/apischeme_cr.go
- pkg/e2e/operators/cloudingress/cloudingress.go
- pkg/e2e/operators/cloudingress/public_private.go
- pkg/e2e/operators/cloudingress/publishingstrategies_cr.go
- pkg/e2e/operators/cloudingress/rhapi_endpoint.go
Enable all CIO tests that aren't placeholders.
They worked all on last run: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/osde2e-prod-aws-informing-default/1323626158381600768
> Add cloud-ingress-operator tests to operators suite

- pkg/e2e/operators/cloudingress/apischeme_cr.go
- pkg/e2e/operators/cloudingress/cloudingress.go
- pkg/e2e/operators/cloudingress/public_private.go
- pkg/e2e/operators/cloudingress/publishingstrategies_cr.go
- pkg/e2e/operators/cloudingress/rhapi_endpoint.go
Reverts openshift/osde2e#619
These tests fail on GCP clusters, @cblecker I think we need to either make the tests aware of the platform they are running on or disable them until the operator is ready to run on GCP.
Currently the operator is deployed to AWS clusters only: https://github.com/openshift/cloud-ingress-operator/blob/master/hack/templates/selectorsyncset.yaml#L13
> Revert "Add cloud-ingress-operator tests to operators suite"

- pkg/e2e/operators/managedupgrade.go
In this commit, I added a test to verify that dedicated admin can't manage upgradeconfig and cluster admin can.
> Dedicated admin can't manage upgradeconfig test.

- pkg/e2e/operators/rbac.go
The [prow tests](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/osde2e-prod-aws-e2e-next/1327219793371074560#1:build-log.txt%3A1956) for the rbac-permission-operator appear to be failing to verify that dedicated-admins are unable to create subjectPermissions because the validating webhooks are returning the forbidden message in a different format than the `apierrors.IsForbidden(err)` check is expecting.  This replaces the check with the more generic `Expect(err).To(HaveOccurred())`.
REF:
[https://issues.redhat.com/browse/OSD-5811](https://issues.redhat.com/browse/OSD-5811)
> Fixes prow errors for RBAC dedicated admin test

- pkg/e2e/verify/sccs.go
This promotes the work of [OSD-5213](https://issues.redhat.com/browse/OSD-5213) to the main e2e suite, as there has been a clear run during it's time in `informing` with no failures.
> OSD-5799 Promote SCC Dedicated Admin check from informing

- ci/prow-ocm-adoption.sh
This is a script to validate that a vanilla OCP cluster shows up in OCM.
We test this by using a CI-created cluster and looking up its external cluster ID in OCM. To validate the workflow in Stage, we need to patch the cluster's Telemetry endpoint then wait until the telemetry operator cycles and registers the cluster. 
There will be a subsequent PR in openshift/release with the Prow Job that uses this
> SDCICD-387: Add script/test to test ocm adoption of an OCP cluster

- pkg/e2e/operators/rbac.go
Tests validating whether or not subjectPermissions can or cannot be
created by dedicated-admins and cluster-admins belong in the validating
admission webhook tests rather than the RBAC Permissions Operator, as
the webhook is the authority for those.
REF:
* [https://issues.redhat.com/browse/OSD-5811](https://issues.redhat.com/browse/OSD-5811)
* [https://coreos.slack.com/archives/CNJPJSG3Z/p1605560323375800?thread_ts=1605559773.372800&cid=CNJPJSG3Z](https://coreos.slack.com/archives/CNJPJSG3Z/p1605560323375800?thread_ts=1605559773.372800&cid=CNJPJSG3Z)
Jira for replacement tests in webook e2e: [https://issues.redhat.com/browse/OSD-5446](https://issues.redhat.com/browse/OSD-5446)
> Removes tests for subjectPermission creation gated by webhook

- pkg/common/providers/crc/crc.go
- pkg/common/providers/moaprovider/wrapped_calls.go
- pkg/common/providers/mock/mock.go
- pkg/common/providers/ocmprovider/cluster.go
- pkg/common/spi/provider.go
- pkg/common/upgrade/managed.go
This PR removes the setting of a `pod disruption budget` policy when creating an upgrade policy, as that setting is soon to be managed at the cluster level rather than at an upgrade policy level.
This PR has been successfully tested in staging with an E2E upgrade run.
Refs [OSD-5867](https://issues.redhat.com/browse/OSD-5867)
> OSD-5867 remove PDB configuration for upgrades

- pkg/common/constants/constants.go
- pkg/e2e/operators/cloudingress/apischeme_cr.go
- pkg/e2e/operators/cloudingress/cloudingress.go
- pkg/e2e/operators/cloudingress/installed.go
- pkg/e2e/operators/cloudingress/public_private.go
- pkg/e2e/operators/cloudingress/publishingstrategies_cr.go
- pkg/e2e/operators/cloudingress/rhapi_endpoint.go
Some test cleanup to add a bit more consistency:
- Create a common/constants package with the suite prefixes in them. Allows us to use these across tests.
- Clean up variables inside the CIO e2e tests to have them be a bit more consistent
- Enable tests we expect to pass
> Cleanup of cloud-ingress-operator e2e tests

- pkg/e2e/operators/cloudingress/apischeme_cr.go
Added a clean up functionality to the test. 
after the test for creation of the apischeme is ran the resource will be deleted allowing for extra executions
without failures or having to manually delete the apischeme from the cluster.
https://issues.redhat.com/browse/OSD-5881
> Added function to clean up apischeme-cr-test

- pkg/common/cluster/clusterutil.go
- pkg/common/cluster/healthchecks/pod_predicates.go
- pkg/common/cluster/healthchecks/pods.go
- pkg/common/cluster/healthchecks/pods_test.go
- pkg/common/upgrade/managed.go
- pkg/e2e/workloads/guestbook/guestbook.go
- pkg/e2e/workloads/redmine/redmine.go
This PR adds a variadic argument section to `CheckPodHealth`, allowing for more refined checking of pod status by comparing the list of retrieved pods against a supplied slice of pod name prefixes.
This allows tests which (re)use `CheckPodHealth` to not be impacted if another unrelated pod in the cluster happens to be in a Pending state.
The `guestbook` and `redmine` tests, and the managed upgrade code, have been updated to make use of the additional arguments. Features such as the cluster health check will continue to scan through all pods.
> Add optional pod prefix to pod health check

- pkg/common/cluster/clusterutil.go
- pkg/common/providers/mock/mock.go
- pkg/e2e/e2e.go
Since OCM provider-driven testing is having issues for SRE with fetching the kubeconfig, this PR attempts to get the `TEST_KUBECONFIG` method of local `kubeconfig`-based testing working again, by setting it up with the mock provider.
I found that with the existing `osde2e`, trying to use `TEST_KUBECONFIG` caused code panics because it assumes that a provider is created, but one never is. So this change attempts to address that problem in a pretty crude way via the mock provider, so that there is at least some avenue for SRE to continue using `osde2e` for testing whilst this whole issue is figured out.
> Make TEST_KUBECONFIG use the mock provider

- pkg/e2e/operators/prunejob.go
As part of [OSD-3985](https://issues.redhat.com/browse/OSD-3985) we will be removing the SRE image pruner cronjob on 4.6.x clusters in favour of the existing cluster image pruner.
This PR adjusts the `Prune Jobs` test so that it will not attempt to test the ability to create jobs from the SRE image pruner cronjob, as this cronjob will not exist on 4.6 clusters when [OSD-3985](https://issues.redhat.com/browse/OSD-3985) is promoted.
cc @wanghaoran1988 as original test author.
> OSD-3985 remove image-pruner cronjob test

- cmd/osde2ectl/delete/cmd.go
Modified the osde2ectl delete command to return an error if no cluster ID or owner arguments are passed.
> osde2ectl delete should error when no id is passed

- pkg/e2e/osd/inhibitions.go
Fix AlertmanagerInhibitions due to changes in https://github.com/openshift/configure-alertmanager-operator/pull/126
fixes [OSD-6013](https://issues.redhat.com/browse/OSD-6013)
> Fix AlertmanagerInhibitions

- README.md
- docs/Config.md
- pkg/common/cluster/clusterutil.go
- pkg/common/providers/ocmprovider/cluster.go
- pkg/e2e/e2e.go
This PR allows for the ability to override the `credentials` request made by the OCM provider with a locally-hosted kubeconfig using the `TEST_KUBECONFIG` environment variable. This allows SRE-P, who do not possess the permissions to obtain `credentials` from OCM, to continue to operator OSDE2E with an OCM provider.
Their steps would now be:
- Log in to the OSD cluster locally, to create the local kubeconfig
- Elevate permissions on the cluster to `osd-sre-cluster-admins` if needed (required by many tests)
- Set `TEST_KUBECONFIG` to the path to that kubeconfig, eg. `$HOME/.kube/config`
- Run OSDE2E as normal.
The existing method of using osde2e to test non-OSD clusters via `TEST_KUBECONFIG` is retained, however must be opted in explicitly through setting the `PROVIDER` viper config to …
> Allow override of OCM provider credentials request

- cmd/osde2ectl/list/cmd.go
Changed the output of osde2ectl list fields to avoid collision between them for longer outputs. (The fields in check are cluster status, owner and installed version)
> Cleaned osde2ectl list fields output

- README.md
This PR adds some directions around using `TEST_KUBECONFIG` for credential overriding into the project README.
> Clarify TEST_KUBECONFIG test steps in README

- pkg/e2e/operators/configurealertmanager.go
- pkg/e2e/operators/operators.go
After a recent upgrade to latest stable, the required serviceAccount wasn't existing anymore.
We have to make sure during tests this doesn't happen
> Ensure configure-alertmanager-operator service account exists

- pkg/e2e/osd/inhibitions.go
Corrects a couple of issues in the `AlertmanagerInhibitions` test.
- This test was breaking if multiple tests had the same "equals" and the same "source" (#652 introduced one). This has been fixed.
- Corrects a broken inhibition rule test (it was looking for `KubePodNotReady` as a source instead of `KubePodCrashLooping` - and there already exists a test for the that)
- Added an optional description to the `Expect()` clause so that now if one of the tests fails it will print out what AM Inhibition test actually failed.
- Added a new missing inhibition rule to test for that 's been introduced recently.
Refs [OSD-6013](https://issues.redhat.com/browse/OSD-6013)
> OSD-6013 Fix AlertmanagerInhibitions test

- cmd/osde2ectl/healthcheck/cmd.go
- cmd/osde2ectl/main.go
Added a command to run a healthcheck against a cluster with the help of a local kubeconfig or a cluster ID.
> Add an ad-hoc healthcheck command to osde2ectl

- pkg/e2e/e2e.go
This tiny little PR resumes allowing OSDE2E to perform image-based upgrades. Previously this was being blocked outright, regardless of whether managed upgrades were enabled or disabled in the viper config.
I've tested this successfully with an image-based upgrade in `osde2e`. Should have no impact to our existing `e2e` runs which use managed upgrades.
> Allow non-managed image-based upgrades

- pkg/e2e/verify/pod_webhook.go
In this commit, we test the pod webhook and verify that the dedicated-admin user can not create pods in unprivileged namespaces on master and infra nodes. We also verify that RBAC does not allow ordinary users to create pods.
> Pod webhook

- configs/upgrade-rescheduled.yaml
- docs/Config.md
- pkg/common/config/config.go
- pkg/common/providers/crc/crc.go
- pkg/common/providers/moaprovider/wrapped_calls.go
- pkg/common/providers/mock/mock.go
- pkg/common/providers/ocmprovider/cluster.go
- pkg/common/spi/provider.go
- pkg/common/upgrade/managed.go
- pkg/common/upgrade/upgrade.go
- pkg/e2e/e2e.go
Adding the upgrade test for reschedule the upgrade policy before the upgrade triggered.
Haven't test this yet, since the kubeconfig issue on stage env.
> add upgrade test for reschedule

- pkg/common/providers/crc/crc.go
- pkg/common/providers/moaprovider/wrapped_calls.go
- pkg/common/providers/mock/mock.go
- pkg/common/providers/ocmprovider/cluster.go
- pkg/common/spi/provider.go
Osde2e now supports random selection of an instance/machine type for a given cloud provider and cluster under ocm. Users can make use of the OCM_COMPUTE_MACHINE_TYPE env variable to use random values.
> Select random machine type for a given cluster

- pkg/e2e/e2e.go
This PR addresses [SDCICD-519](https://issues.redhat.com/browse/SDCICD-519) whereby the following concerning error messages were being logged:
```
Error creating route monitors: Unable to generate helper outside ginkgo
```
which, to a newcomer to reviewing CI logs, may look like a problem.
In reality this was occuring because the route monitors were being created regardless of whether or not the cluster had successfully been able to set up its kubeconfig credentials (needed to create a `helper`), and also being created unnecessarily if no upgrade needed to occur.
This PR adjusts creation of the route monitors so that they only get created if:
- E2E has been able to obtain the cluster's kubeconfig
- E2E is running a test job to upgrade a cluster
So the aforementioned error won't show up …
> SDCICD-519 only create route monitors when necessary

- pkg/common/versions/installselectors/specific_image.go
This PR removes the registry server `registry.ci.openshift.org` from version images, prior to performing semantic version parsing.
Some Prow CI jobs are currently failing because they're trying to create clusters with an image reported by Cincinnati as `registry.ci.openshift.org/ocp/release:...` [0], which looks to be a recent change from `registry.svc.ci.openshift.org/ocp/release`. The jobs fail because it doesn't parse the version as a valid semantic version - which is because it isn't removing the `registry.ci.openshift.org/org/release:` text of the image prior to parsing check. Examples: [1] [2]
OSDE2E currently removes `registry.svc.ci.openshift.org` from the image, but isn't removing `registry.ci.openshift.org`. This PR makes it attempt to remove both.
This change has been …
> Remove CI registry from version image during selection

- pkg/common/cluster/healthchecks/nodes.go
This change attempts to validate that no nodes in a cluster have the "NoSchedule" effect.
> Validate no nodes have the no schedule taint

- pkg/common/alert/alert.go
- pkg/common/config/config.go
- pkg/common/helper/addons.go
- pkg/e2e/addons/addon_test_harness.go
This will simply list the harnesses that failed in slack. @jeefy mentioned perhaps providing links to review the test output (which would be cool), but I'm putting this up in its current state to get feedback about the high-level approach.
> add notification channel config to addon harness

- cmd/osde2ectl/get/cmd.go
this fixes #657 
If the given directory exists, we should be using that.
Nil pointer was thrown because we didn't have an error in this case but still tried to use it.
Now we only cast an error when we actually have one
> cmd/osde2ectl/get/cmd.go: do not panic if directoy exists

- pkg/common/helper/olm.go
- pkg/e2e/e2e.go
This PR allows `osde2e` to perform an OLM inspection during its end-of-test data gathering process. This will result in an `olm-inspect.tgz` file as part of the generated test artifacts, which can be used alongside existing must-gather data.
Doing this allows us to gather the OLM state of operators on the cluster, which is presently not included as part of must-gathers. The lack of this data makes it quite hard to debug failing tests such as the `Should upgrade from a previous version` ones, and equally hard to provide relevant data to a Bugzilla if we encounter OLM bugs as part of E2E testing.
The must-gather image has recently had an enhancement to do this for us [0], but unfortunately it is not something we can yet make use of. When it makes its way into a release and we start getting …
> Add OLM Inspection to end of test run

- pkg/common/cluster/clusterutil.go
- pkg/common/cluster/healthchecks/pod_predicates.go
- pkg/common/cluster/healthchecks/pods.go
This commit enables real health checks to be run from the [osd-cluster-ready Job](https://github.com/iamkirkbater/osd-cluster-ready-job) by:
- Tweaking `PollClusterHealth` to use in-cluster REST config if the `clusterID` is not specified (empty string).
- Ignoring the `osd-cluster-ready` pod itself, as it will be Pending while it's running the health check.
> Enable osd-cluster-ready in-cluster healthcheck

- docs/Metrics-Client.md
Updated the metrics library doc to use appsre prometheus for access and query results.
> Update metrics library doc to use appsre prometheus instead of datahub

- pkg/e2e/operators/cloudingress/public_private.go
This implements two tests for the cloud-ingress-operator's management of the PublishingStrategy CR. It updates the default OSD PublishingStrategy to make the default application ingress private and waits until it can confirm that the correct service LoadBalancer object has been created. It then tests the same process for toggling back from private to public. 
The associated JIRA ticket: https://issues.redhat.com/browse/OSD-5337
> Test cases for PublishingStrategy's management of public/private ingress

- pkg/common/cluster/healthchecks/pods.go
PR #681 [added](https://github.com/openshift/osde2e/pull/681/files#diff-eeb67b7723fc2c3c66c4d4e7e85f31e1a38d43f7268e0e56e1c997c87b899aaeR11-R17) a predicate to skip the osd-cluster-ready pod when checking whether "all" pods are healthy, because that pod is itself checking whether all pods are healthy. The predicate was [added to CheckClusterPodHealth](https://github.com/openshift/osde2e/pull/681/files#diff-140e0200e3dd96daa38c05e5a3877f19ec4b3b11337d50db24ac917f619b2020R20) but not CheckPodHealth, so tests running through that function can still fail. This commit adds the predicate there.
> Ignore readiness pod in health checks

- pkg/common/versions/version_selector.go
- pkg/e2e/version.go
Previously we had to strip the channel names from versions to match installed CISs.
Now CISs have the channel as a suffix and we support multiple channels. :)
> SDCICD-574: Ensure supplied versions retain their channel suffix so CIS matches

- pkg/common/config/config.go
- pkg/common/providers/ocmprovider/cluster.go
- pkg/e2e/e2e.go
Inserted a config flag check to disable listing of addons in clusters for a scale test during health check polling.
> Disable addon list on scale tests

- pkg/e2e/operators/mustgather.go
This is a simple test which verifies that the latest build of must-gather-operator can be sucessfully installed in the cluster.
> e2e install verification test for MGO

- pkg/common/runner/results.go
- pkg/common/runner/results_test.go
- pkg/e2e/openshift/config.go
- pkg/e2e/openshift/disruptive.go
- pkg/e2e/openshift/images.go
This commit does several things:
- Fixes all of the tests to be configured as cluster admin
- Stops overriding the user account in use away from cluster admin
- Changes the way that we determine failure from exit status to
parsing the junit XML. Unparsable xml, lack of xml, or failures
in XML will cause the test to fail.
> fix: use junit data to determine openshift-suite pass/fail status

- pkg/e2e/addons/addon_test_harness.go
This is a temporary measure to confirm that the slack notification feature
is working as intended.
> addons: always notify of test results

- pkg/common/versions/upgradeselectors/latest_version_selector.go
- pkg/common/versions/upgradeselectors/latest_version_selector_test.go
- pkg/common/versions/upgradeselectors/latest_y_selector.go
- pkg/common/versions/upgradeselectors/latest_y_selector_test.go
- pkg/common/versions/upgradeselectors/latest_z_selector.go
- pkg/common/versions/upgradeselectors/latest_z_selector_test.go
I didn't update the basic "latest" filter with the same logic I did y/z. :upside_down_face:
> SDCICD-583: update latest filter to follow latest-y and latest-z filters

- pkg/common/runner/results.go
- pkg/common/runner/results_test.go
This ensures that whatever logs are available actually make it into the
artifacts for a given run even when the junit data is missing or indicates
problems.
Fixes [SDCICD-587](https://issues.redhat.com/browse/SDCICD-587)
> fix: ensure results fetch returns partial results on error

- pkg/common/helper/addons.go
- pkg/common/runner/results.go
- pkg/common/runner/results_test.go
- pkg/e2e/openshift/app_builds.go
- pkg/e2e/openshift/conformance.go
- pkg/e2e/openshift/disruptive.go
- pkg/e2e/openshift/images.go
- pkg/e2e/operators/operators.go
I had previously altered RetrieveResults to validate that there
was a present, valid, passing Junit XML in the results, but it
turns out that RetrieveResults is often used for other things.
Changing its behavior broke a lot of stuff throughout the code-
base, so I instead introduced a new method with the additional
validation.
> fix: introduce RetrieveTestResults

- pkg/common/versions/version_selector.go
This introduces an error guard before we attempt to use the results of
selectedVersionSelect.SelectVersion(). This used to be unnecessary, as
we immediately returned from the function, but we recently need to
add new logic.
This should prevent crashes like:
https://prow.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-ocp-osd-aws-nightly-4.7/1362027280439709696
> fix: ensure we do not panic when selecting versions

- pkg/e2e/osd/dedicatedadmin.go
[OSD-4789](https://issues.redhat.com/browse/OSD-4789) 
- dedicated-admin SA can create a projectRequest
- dedicated-admin SA can grant "admin" and "edit" to other subjects
- dedicated-admin user can grant "admin" and "edit" to other subjects
- dedicated-admin user can delete user project
> Add dedicated-admin permission checks

- cmd/osde2e/main.go
This shouldn't make lines *too* much longer, but will greatly aid
in the tracing of errors through the test harness
> feat: log file and line number for each log line

- pkg/e2e/e2e.go
- pkg/reporting/ginkgorep/ginkgorep.go
This was originally broken because our parsing method only
accepted xml with a single <testsuite> tag, but it's valid
for Junit xml to contain a <testsuites> tag with multiple
child <testsuite> tags.
I first tried to simply use the new parsing library (junit-go)
to do the parse, and that worked fine. However, once parsed
that library cannot re-serialize the xml, so our approach of
loading, transforming, and then saving the XML was no longer
viable.
To work around this, I implemented a custom wrapper type for
ginkgo's report generator that injects the phase names at the
time of initial XML creation. This seems to produce the same
XML and is cleaner to read.
> fix: accept multi-suite junit xml in e2e harness

- pkg/e2e/operators/operators.go
Currently, if there are multiple CSVs in a namespace checked by the pollCsvList function, it can mistakenly return false. Even if the correct CSV is present, if there are subsequest CSVs still in the list to check, err will be set to `No matching clusterServiceVersion in CSV List`. 
To fix this, a name is applied to the outer for loop and a break to that loop is added to the switch case where the CSV is found.
> Fix CSV checking loop

- ci/create-ocp-cluster.sh
- ci/destroy-ocp-cluster.sh
- ci/prow-ocm-adoption.sh
This adds ocp create and delete helper scripts to be used in Prow and with the `osde2e-credentials` secret.
This also cleans up the adoption test logic. :tada:
> SDCICD-387: Break out create/delete to separate scripts

- ci/create-ocp-cluster.sh
- ci/destroy-ocp-cluster.sh
- ci/prow-ocm-adoption.sh
Some variables are expected in the environment and therefore need to be exported.
Additionally, some other variables aren't needed in certain phases of the test so they've been removed.
> SDCICD-387: export variables expected in env, remove unnecessary secrets

- pkg/e2e/e2e.go
> fix: avoid double concatenating failed string

- pkg/e2e/verify/samesite_cookie.go
- pkg/e2e/verify/strict_transport_security.go
These tests have been passing in production for well over a week now.
> [e2e/verify] Promoting samesite and hsts verification to e2e suite

- pkg/e2e/e2e.go
Previously we put this into the err branch of the if statement,
but we actually needed the cluster id for this to work.
> fix: mark clusters as completed properly

- pkg/common/helper/addons.go
- pkg/common/runner/results.go
- pkg/e2e/openshift/conformance.go
- pkg/e2e/openshift/disruptive.go
- pkg/e2e/openshift/images.go
We should write results before evaluating errors, don't fail writing results when there's an error downloading from a directory
Also adjusting conformance timeouts to be in line with one another.
> SDCICD-603: Better handle retrieving and writing test artifacts

- cmd/osde2ectl/get/cmd.go
> fix: improve output formatting of getting kube config

- pkg/common/cluster/clusterutil.go
- pkg/common/cluster/healthchecks/pods.go
- pkg/common/cluster/healthchecks/pods_test.go
Made changes within PollClusterHealth to only reflect on pending pod failures if the same pod remains in 'pending' state 10 times in a row. Otherwise, pending pod alerts are ignored in the clean run iteration. Key points to note here:-
1. The pending pod threshold for the same pod failing 10 times is set by the constant "pendingPodThreshold" in pkg/common/cluster/clusterutil.go.
2. In pkg/common/cluster/healthchecks/pods.go, the function checkPods returns the list of pending pods which is used by the function CheckClusterPodHealth which then returns the list of pending pods if they exist rather than returning the bool of the length of this list. This list is used by PollClusterHealth to keep track of the pending pods to see if any pod crosses the given threshold of being in pending state …
> Added support for better pending pods check before failing them

- pkg/common/runner/results.go
- pkg/e2e/openshift/config.go
- pkg/e2e/openshift/conformance.go
This changes the error handling to not stall any downloading when there's an error grabbing any files (I missed a spot from the other PR)
Additionally, this updates our conformance tests by adding similar logic to the upstream ci-step-registry.
> SDCICD-603: Update conformance tests, improve error handling when downloading files

- pkg/common/events/events.go
- pkg/e2e/e2e.go
- pkg/e2e/version.go
Adding some verbose logging to conditions that may cause BeforeSuite to fail without any logging as to why.
Additionally, adding a check to validate that the OpenShift version string isn't nil, hopefully preventing other error conditions observed.
:tada:
> SDCICD-595: Add additional logging into BeforeSuite, check for nil during version selection

- docs/Addons.md
> fix: correct the secret name for aws secret access key

- pkg/e2e/state/alerts.go
The documentation for wait.PollImmediate indicates that it does
not retry if the condition function returns an error. There was
no code path in which we did not either return an error or true,
so this PollImmediate invocation would always exit after one try.
> fix: actually retry talking to prometheus

- pkg/common/cluster/clusterutil.go
- pkg/common/cluster/healthchecks/pods.go
Added a few changes on reviewing the PR comments for the initial pull request on the same -  https://github.com/openshift/osde2e/pull/737.
Changes made:-
1. The key in the pod error counter has been changed from pod name to pod UID.
2. The pod error counter deletes pod entries once a pod changes from "pending" state.
3. The healthcheck only passes if the pod error counter is entirely empty.
> Modified pending pods health check

- pkg/common/config/config.go
- pkg/common/providers/ocmprovider/cluster.go
- pkg/common/providers/ocmprovider/cluster_image_sources.go
This allows us to specify/use the `install_config` option within OCM now. It also allows us to specify an ImageContentSource as a config (with several options pre-populated as a key-value pair in the ocmprovider.)
If no Image Source is specified, it will default to a random entry within the ocmprovider map. 
Note: This is only applicable in Int/Stage currently.
> SDCICD-459: Add install_config option, randomize imagecontentsource

- pkg/common/providers/ocmprovider/cluster.go
Don't set install_config in prod or if a job name has "addon" in it. :)
> fix: Don't set install_config for addon jobs

- go.mod
- go.sum
- pkg/common/events/events.go
- pkg/e2e/e2e.go
We were getting errors when attempting to run Ginkgo a second time post-Upgrades. Since the use case for SynchronizedBeforeSuite is not needed anymore, we should remove it. 
Ran a full set of upgrade tests locally after this change and things came back solid. 
During debugging, also upgraded `gomega` and `ginkgo` packages.
> SDCICD-595: Refactor out synchronizedbeforesuite to a new function

- pkg/common/cluster/clusterutil.go
- pkg/common/cluster/healthchecks/healthcheckjob.go
- pkg/common/config/config.go
- pkg/e2e/e2e.go
This is always failing with an error that indicates it can't find the cron job, but I can see it if I look manually. I'm pretty confused.
Here's an example of the error:
```
cluster failed health check
Unexpected error:
<*fmt.wrapError | 0xc000565140>: {
msg: "failed looking up job: the server could not find the requested resource (get jobs)",
err: {
ErrStatus: {
TypeMeta: {Kind: "", APIVersion: ""},
ListMeta: {
SelfLink: "",
ResourceVersion: "",
Continue: "",
RemainingItemCount: nil,
},
Status: "Failure",
Message: "the server could not find the requested resource (get jobs)",
Reason: "NotFound",
Details: {
Name: "",
Group: "",
Kind: "jobs",
UID: "",
Causes: [
{
Type: "UnexpectedServerResponse",
Message: "unknown",
Field: "",
},
],
RetryAfterSeconds: 0,
},
Code: 404,
},
},
}
failed …
```
> Use healthcheck cron job to determine cluster readiness

- pkg/e2e/e2e.go
This symbol isn't actually part of the channel name, and causes this notification attempt to always fail.
> fix: remove # character from slack channel name

- pkg/common/providers/crc/crc.go
- pkg/common/providers/mock/mock.go
- pkg/common/providers/ocmprovider/cluster.go
- pkg/common/providers/ocmprovider/ocm.go
- pkg/common/providers/rosaprovider/wrapped_calls.go
- pkg/common/spi/provider.go
- pkg/e2e/osd/ocm.go
This removes code referring to the CS Metrics endpoint. It still leaves the OCM Metrics test as well as the SPI Metrics endpoint in place, for when AMS adds an endpoint to consume metrics from.
> SDCICD-628: Remove reliance on CS metrics, leave stubs for AMS metrics

- cmd/osde2ectl/create/cmd.go
- pkg/common/cluster/clusterutil.go
- pkg/common/cluster/healthchecks/healthcheckjob.go
- pkg/common/config/config.go
- pkg/common/upgrade/upgrade.go
- pkg/e2e/e2e.go
I believe that this *finally* resolves SD-CICD 577. Essentially, these changes alter our healthcheck in the following ways:
- waiting for OCM to finish provisioning a cluster has been broken out into its own reusable function
- the different reasons that we might wait on cluster health now have different functions. This allows us to specialize the implementation to use the healthcheck most appropriate for the circumstance
- `WaitForClusterReadyPostInstall` properly waits for OCM and then the healthcheck cron job.
> Sdcicd 577

- docs/Addons.md
Do not merge this until we get confirmation from leadership that all addon testing should be CCS-based.
/hold
> docs: update to ccs-only addon testing

- pkg/common/cluster/healthchecks/healthcheckjob.go
There's no timeout here, this is just an artifact of a previous code structure.
> fix: update incorrect error message

- pkg/common/providers/ocmprovider/cluster_image_sources.go
Also remove redundant test cases. We only need to test Regional Quay as the primary mirror and then Main Quay as the primary mirror.
> Fix: Swap ECR registries for Regional Quays in ICSP testing

- pkg/e2e/operators/configurealertmanager.go
- pkg/e2e/operators/operators.go
The `ClusterServiceVersion` for the `configure-alertmanager-operator` now contains the roles for the operator as part of the `permissions` field. This means that the name of the `Role` and the `RoleBinding` are not fixed but are prefixed with the CSV name. This PR changes the test so that the roles and role bindings are verified in the same namespace based only on the prefix.
> Check roles with prefix exist

- pkg/common/providers/ocmprovider/cluster.go
We should only pass this cluster property if it has content. :)
> Fix: Only pass install_config property if it's set

- pkg/e2e/state/prometheus.go
Added a minor fix for the wait poll check (to see if prometheus pods are up) that happens before the collect-prometheus pod tries to extract data from prometheus.
> Fix for prometheus pod check

- pkg/e2e/operators/osd_metrics_exporter.go
Added basic tests for [osd-metrics-exporter](https://github.com/openshift/osd-metrics-exporter) based on existing tests.
Also a test to verify that the exporter is exposing metrics on an endpoint through a service.
> Added basic tests for osd metrics exporter

- pkg/e2e/operators/operators.go
Even the presence of the CSV is verified before this test the CSV might be in the `Pending` state. It might take some time for the resources to be provisioned by the `catalog-operator` and `olm-operator`.
> Poll the roles and rolebinding instead of a one-time check

- pkg/e2e/operators/osdmetricsexporter.go
It appears the test don't actually run on the test cluster but instead from a separate location. While writing this test I initially assumed that the test binary would run in the cluster and added an HTTP call to verify that an endpoint is up and running. This PR removes that test.
> Removed HTTP call which may not be running on-cluster

- pkg/common/config/config.go
- pkg/common/load/load.go
- pkg/e2e/e2e.go
This will insert any non-OSDe2e-specific secrets specified by Addon Authors into the test cluster under the `osde2e-ci-secrets` namespace as a secret named `ci-secrets`
> SDCICD-624: Pass through non-osde2e secrets into test cluster for addon testing

- pkg/e2e/verify/oauth_tokens.go
The MCC changes needed for this may not happen as soon as I'd like (or at all) - skip these tests for now rather than pollute the results. Will revert this or remove the tests in the future
Apologies for the premature PR
> Skip oauth token timeout tests

- ci/create-ocp-cluster.sh
metadata.json is created during a openshift-install operation, but when the install-step fails, metadata.json isn't preserved. When this happens, the destroy-step doesn't have any knowledge of the cluster or resources created and thus can't clean up resources from a failed installation.
This will trap any error during cluster creation and, if it occurs, still copy the metadata.json and install-config into the shared directory for the destroy-step to work its magic.
> SDCICD-641: Preserve metadata.json during failed cluster installation

- pkg/common/cluster/clusterutil.go
- pkg/common/cluster/healthchecks/pod_predicates.go
- pkg/common/cluster/healthchecks/pods.go
- pkg/common/clusterproperties/statuses.go
- pkg/common/config/config.go
- pkg/common/helper/helper.go
- pkg/common/helper/projects.go
- pkg/common/providers/ocmprovider/cluster.go
- pkg/e2e/e2e.go
This is a small'ish PR with large-implications.
1. Upon Cluster creation, see if there are any `completed-passing` clusters that have the same version
2. If yes, re-use the cluster. If hibernated, resume the cluster and wait. If not, create a new cluster.
3. If all tests are passing (this logic is up for debate), set it to `completed-passing` so it can be reused -- otherwise, flag it `completed-failing`
4. Regardless of results, hibernate the cluster
There are conditions where a cluster could come up and trigger a (cron) job, which will fail during the wake-up phase. Because of this, we delete any Errored pods owned by Jobs after 10 minutes and before we begin health-checking.
Note: Once [SDA-4063](https://issues.redhat.com/browse/SDA-4063) has been resolved, we will need a follow-up PR …
> SDCICD-616, 617, 618 -- Hibernation support for CICD

- cmd/osde2e/test/cmd.go
- pkg/common/versions/version_selector.go
- pkg/common/versions/version_setup.go
- pkg/e2e/e2e.go
- pkg/e2e/version.go
This PR allows us to provide an exit code we want `osde2e test` to use during `RunTests` / `runGinkgoTests`. 
In addition, it updates version selection/errors to exit(130) when an issue arrises during version selection.
> SDCICD-581 / 647: Surface exit codes from RunTests, exit(130) if an issue with version selection

- pkg/common/clusterproperties/statuses.go
- pkg/common/config/config.go
- pkg/common/providers/ocmprovider/cluster.go
- pkg/e2e/e2e.go
Once we retrieve a cluster, we should immediately tag it with the current Job ID before doing any other operation. 
We should then validate via a second GET whether the Job ID is the same as the current job. If not, recuuuuuurse. 
Additionally, there is now a flag to allow Recycled Clusters for a job (default: True) which means some jobs we can set to always require a fresh cluster.
> fix(es): Prevent cluster claim conflicts, add flag preventing recycled clusters

- cmd/osde2ectl/expire/cmd.go
- cmd/osde2ectl/list/cmd.go
- cmd/osde2ectl/main.go
- pkg/common/providers/crc/crc.go
- pkg/common/providers/mock/mock.go
- pkg/common/providers/ocmprovider/cluster.go
- pkg/common/providers/rosaprovider/wrapped_calls.go
- pkg/common/spi/provider.go
- pkg/e2e/e2e.go
Apologies up front -- reviewing each commit might make more sense. 
1. Adds "expire" command to osde2ectl -- it will set the expiration timestamp to be now+1min
2. Makes `osde2ectl list` a lot more.... useful. Output example:
```
NAME           OWNER    ID                                 CLOUD     STATE          STATUS                VERSION                                        JOB_ID                   JOB
osde2e-momta   root     1jovh44rpvj38v7nhtf9jivnn55a082c   aws       ready          provisioning          4.7.4                                          -1                       
osde2e-rxain   root     1jovv8i379uaeaougb0mmcmrb9mvieqv   aws       ready          provisioning          4.7.4                                          -1                       
osde2e-2yaup   prow …
```
> An overly-bloated PR that I apologize for

- pkg/common/providers/ocmprovider/cluster.go
Since the heart of [SDCICD-183](https://issues.redhat.com/browse/SDCICD-183) is to convert our pipelines to choose a random machine type, but most machine types are a bit more expensive, this adds a weight so every 1 out of 3 times, when the machine type is set to `random`, it will actually pick a random machine type from OCM. Otherwise, it blanks the variable out internally and creates the cluster with the default.
> SDCICD-183: Add weight to choosing a random machine type

- pkg/common/runner/pod.go
In any runner pods, we will now pass "OSDE2E=true"
> SDCICD-665: Pass env var in runner pods

- pkg/common/providers/ocmprovider/cluster.go
There are instances where we have grabbed a cluster that will expire mid-test. This should prevent that by only ever grabbing a cluster that expires 4+ hours after the current time.
> SDCICD-672: Fix race condition grabbing expiring clusters

- pkg/e2e/e2e.go
Generating this data is computationally cheap, and we check whether to
insert it into the database elsewhere (at the point where we actually
do it). Having that logic in two places just creates opportunity for it
to get out of sync.
> fix: always generate testcase data

- assets/addons/addon-runner.template
There may be instances where we check for the state of a pod's containers before the pod has been created. 
Infamous words ring true: "If there's a race condition, just add another sleep to it."
> SDCICD-673: Add time between the apply and checking for pod state

- pkg/e2e/e2e.go
This ought to prevent segfaults like this:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/osde2e-stage-rosa-e2e-upgrade-to-latest/1402460567825813504#1:build-log.txt%3A7120
> fix: grab correct error string for test entries in db

- assets/upgrades/config.template
Based on PR https://github.com/openshift/managed-cluster-config/pull/853, adding entries in MUO Configmap with more entries for ignoring namespaces. Also, based on latest MCC configmap [file](https://github.com/openshift/managed-cluster-config/blob/master/deploy/managed-upgrade-operator-config/10-managed-upgrade-operator-configmap.yaml), changed the entries of some of the alerts to be ignored during control plane upgrade.
> Sync entries from MCC MUO ConfigMap

- assets/upgrades/config.template
This PR corrects the mistaken naming of the `openshift-route-monitor-namespace` for being ignored by the `managed-upgrade-operator` when checking active alerts pre-upgrade.
> Fix naming of RMO namespace in MUO config

- assets/reports/weather-report/markdown.template
- assets/reports/weather-report/sd-report.template
Summary job URLs open with `https://prow.svc.ci.openshift.org` by default which does not open. The URL with `https://prow.ci.openshift.org` works fine for it. This PR changes those default URLs being opened.
Example of faulty URLs opened by default: 
Summary Job: https://prow.svc.ci.openshift.org/?job=osde2e-prod-aws-e2e-default
> Changing summary job url to prow.ci.openshift.org

- ci/create-aro-cluster.sh
- ci/destroy-aro-cluster.sh
These scripts handle installation of requirements for, and creation/deletion of, ARO clusters. They make similar assumptions that the OCP scripts use. Once a cluster is created it generates and outputs a Kubeconfig for later steps to use without need of the Azure CLI/creds.
/assign @whereswaldon @jewzaam 
/hold
I explicitly want both @whereswaldon's and @jewzaam's reviews before this gets merged in.
> SDCICD-651: Add create/destroy scripts for aro cluster creation

- pkg/e2e/e2e.go
Ginkgo change their semantics around how skips are specified
such that now the empty string skips everything.
> fix: do not always skip tests

- pkg/common/helper/helper.go
- pkg/e2e/e2e.go
- pkg/e2e/operators/customdomains.go
- pkg/e2e/operators/managedupgrade.go
- pkg/e2e/verify/oauth_tokens.go
/assign @jeefy 
This should make it somewhat easier to find the code path that is failing our upgrade tests, albeit at the cost of very noisy logging.
> debug: log stack traces immediately before all calls to BeforeEach

- pkg/common/providers/crc/crc.go
- pkg/common/providers/mock/mock.go
- pkg/common/providers/mock/mock_test.go
- pkg/common/providers/ocmprovider/cluster.go
- pkg/common/providers/ocmprovider/config.go
- pkg/common/providers/ocmprovider/quota.go
- pkg/common/providers/ocmprovider/sku.go
- pkg/common/providers/rosaprovider/wrapped_calls.go
- pkg/common/spi/provider.go
This PR removes validation of available quota through the `resource_quota` endpoint and replaces it with validation of SKU quota using `quota_cost`.
`resource_quota` has been deprecated as a API endpoint in SDB-1979. As a result of this, cluster creation in Staging currently fails as the endpoint returns empty data.
If no SKU is specified (via the `OCM_SKU` environment variable or `ocm.skuRule` viper config), cluster creation **proceeds** with no quota validation taking place.
> Replace quota_summary validation with SKU quota validation

- pkg/common/providers/ocmprovider/cluster.go
- pkg/common/upgrade/managed.go
This PR introduces improved handling of managed upgrades to enable OSDE2E to better detect cases of an upgrade failing to start (culminating in the OCM provider cancelling the upgrade altogether), and passing that error back up the chain.
Presently in cases where the `managed-upgrade-operator` fails to initiate a control plane upgrade within a configurable time window, the operator reports this as a failed upgrade to OCM and the upgrade is cancelled, resulting in the eventual deletion of the `UpgradeConfig` CR on-cluster. `OSDE2E` does not currently handle this situation in a nice way, and will wait the full three hours hoping that the situation will resolve itself (but it won't). This will often exhaust the total Prow job time, resulting in no reporting at all for jobs such as these. …
> OSD-7652 Make E2E more resilient to upgrade failures

- configs/inspect-namespaces.yaml
- docs/Config.md
- pkg/common/config/config.go
- pkg/common/helper/helper.go
- pkg/common/helper/projects.go
- pkg/e2e/e2e.go
Presently during clean-up, E2E performs a `must-gather` on the cluster and an additional `oc adm inspect` on the `osde2e-xxxx` project it creates. However, neither of these include information on OSD operators which are installed as part of the cluster, which means useful information to troubleshoot failing tests is lost.
This PR adds a new configuration parameter defining a list of project namespaces that OSDE2E will perform an `oc adm inspect` on during E2E clean-up. This parameter is available as the `INSPECT_NAMESPACES` environment variable or the `cluster.inspectNamespaces` viper configuration parameter.
The gathered project output is build up in the `must-gather-additional-projects.tar.gz` in the test output dir.
A configuration of additional OSD projects has been added as …
> Add configurable list of projects to inspect on cleanup

- pkg/common/config/config.go
We have a number of cases where webhook tests are timing out (OSD-7451,
OSD-7452, OSD-7547, et al) where the osde2e framework itself appears to
be responsible. Increasing the timeout here is a "try it and see"
approach.
Signed-off-by: Lisa Seelye <lisa@users.noreply.github.com>
> Increase PollingTimeout to 60s

- pkg/e2e/operators/managedvelero.go
There are some test failures around permissions for the MVO tests. It appears that the ordering of tests was causing some issues with the Impersonation config not being reset.
```
------------------------------
• Failure [0.022 seconds]
[Suite: operators] [OSD] Managed Velero Operator
/go/src/github.com/openshift/osde2e/pkg/e2e/operators/managedvelero.go:26
velero
/go/src/github.com/openshift/osde2e/pkg/e2e/operators/managedvelero.go:272
Access should be allowed to edit Backups [It]
/go/src/github.com/openshift/osde2e/pkg/e2e/operators/managedvelero.go:273
Unexpected error:
<*errors.StatusError | 0xc001dd0a00>: {
ErrStatus: {
TypeMeta: {Kind: "", APIVersion: ""},
ListMeta: {
SelfLink: "",
ResourceVersion: "",
Continue: "",
RemainingItemCount: nil,
},
Status: "Failure",
Message: …
```
> Defer resetting the helper SA for MVO tests

- pkg/common/config/config.go
- pkg/common/helper/projects.go
This is a continuation of PR #881 to add a configurable list of OSD projects to perform an `oc adm inspect` on during E2E cleanup.
This PR defines a default collection of namespaces which are normally present on OSD clusters.
The process for performing the `oc adm inspect` has also been improved such that it will verify each project in the "to be inspected" list actually exists on the cluster before it attempts to inspect it (preventing any inadvertent error in the process executing).
> Add a selection of default OSD namespaces to inspect on cleanup

- assets/upgrades/config.template
I've been observing this alert hitching up E2E upgrades quite a bit lately, and there's no reason in my mind why the `managed-upgrade-operator` should really be treating this as an alert worthy of blocking upgrade commencement or completion.
This PR will add the alert to the ignore list so that it's no longer causing upgrades to get stuck either pre or post upgrade.
I'm unsure why the alert is firing is firing at all in E2E world - unfortunately at the moment with the `managed-upgrade-operator` upgrade never finishing due to the alert, it's difficult to catch in the wild due to the lack of a must-gather from the E2E job. My suspicion is maybe one of the SRE pruning E2E tests is colliding or causing inadvertent issues. 
I have also submitted a PR for `managed-upgrade-operator` to ignore …
> Ignore PruningCronjobErrorSRE during upgrades

- pkg/e2e/operators/customdomains.go
More stability improvements to catch flaky connection time outs to allow the pollImediate to continue trying.
https://issues.redhat.com/browse/OSD-7472
> Permit URL Op errors due to flaky network connections

- docs/Config.md
- pkg/common/config/config.go
- pkg/e2e/addons/addon_test_harness.go
PR #883 increased the polling timeout default to 60s, but this breaks some code in the add-on testing which relies on that default being 30 in order to bump the polling timeout to an hour.
This PR introduces an `ADDON_POLLING_TIMEOUT` configuration which defaults to 1h.
> Introduce Addon polling timeout configuration

- pkg/e2e/operators/mustgather.go
Error-ing test from some backplane changes - https://redhat.pagerduty.com/incidents/P2D8HJY
`osd-sre-cluster-admins` no longer exists
> SRE elevates with backplane-cluster-admin

- pkg/common/cluster/healthchecks/operators.go
* etcd operator sometimes reports RecentBackup condition as Unknown
* This is not critical for the operator but blocks the test run
* See [Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=2005952)
> Add workaround for etcd operator

- go.mod
- go.sum
- pkg/e2e/verify/encrypted_storage.go
Resolves: https://issues.redhat.com/browse/OSD-8357
---
Encrypted Storage tests were found to be failing because the e2e pipeline was running the test multiple times, which caused a conflict between old resources that weren't cleaned up properly and newly generated resources.  
To solve this problem, `CredentialsRequest` cleanup was added to the `AfterEach` function, the naming logic was improved to minimize the chance of collisions between tests, and logic was added to reuse GCP `cryptoKeys` if they exist already (`cryptoKeys` cannot be deleted from KMS, therefore they must be reused rather than recreated).
> OSD-8357 - Improve repeatability for encrypted storage testing.

- ci/aro-e2e-tests.sh
Sometimes our (ARO) e2e tests rely on code in master but not currently deployed to production yet.  This should fix failed e2e tests that run which currently don't have the feature enabled or released in production.
> Pin ARO e2e to the current deployed ARO RP version

- go.mod
- go.sum
- pkg/common/providers/ocmprovider/cluster.go
- pkg/common/providers/rosaprovider/cluster.go
- pkg/common/providers/rosaprovider/config.go
- pkg/e2e/operators/cloudingress/apischeme_cr.go
- pkg/e2e/operators/cloudingress/installed.go
- pkg/e2e/operators/cloudingress/public_private.go
- pkg/e2e/operators/cloudingress/publishingstrategies_cr.go
- pkg/e2e/operators/cloudingress/rhapi_endpoint.go
- pkg/e2e/operators/cloudingress/rhssh_endpoint.go
- pkg/e2e/operators/cloudingress/secondary_router.go
- pkg/e2e/operators/cloudingress/upgrade.go
- pkg/e2e/operators/managedvelero.go
Adds support for creating ROSA STS clusters.
Updates CIO and MVO tests to be skipped when it's an STS cluster.
Currently blocked by [SDA-4806](https://issues.redhat.com/browse/SDA-4806)
/hold
> SDCICD-607: Support creating and testing against STS clusters

- pkg/e2e/verify/prom_exporters.go
This PR addresses [OSD-8744](https://issues.redhat.com/browse/OSD-8744) which identified failing tests in our `osde2e-*-rosa-sts-e2e-default` jobs. The secrets that the `prom_exporters` test were checking for will not exist on STS clusters, so the test has been revised to not check for these secrets if the test cluster is STS.
> OSD-8744 Ignore prom-exporter secret check on STS clusters

- pkg/common/config/config.go
- pkg/common/load/load.go
- pkg/common/providers/ocmprovider/config.go
- pkg/common/providers/rosaprovider/config.go
This allows you to set multiple possible locations for a single viper variable.
```
config.RegisterSecret(AWSAccessKey, "aws-access-key-id")
config.RegisterSecret(AWSAccessKey, "ocm-aws-access-key")
```
Would now work, allowing you to look at multiple locations for the same variable/secret to load.
> Improve secret loading for OSDe2e`

- pkg/common/cluster/clusterutil.go
- pkg/common/cluster/healthchecks/healthcheckjob.go
- pkg/e2e/e2e.go
We shouldn't bomb an entire job if a healthcheck fails, so this will log if the healthcheck fails then proceed with testing.
Additionally, it will collect logs from the cluster-ready job so we can debug what went wrong.
> SDCICD-713 - Improve healthcheck behavior

- pkg/common/config/config.go
- pkg/common/load/load.go
We recently added the ability to call RegisterSecret multiple times for a (viper) key.
Using a map is probably the wrong call since we want to load things in the order that they're registered. This should fix some of the odd behavior we've seen with addons loading secrets. 
/assign @mrsantamaria
> Remove use of map causing secret loading to fail when specifying multiple secret locations

- cmd/ci-watcher-report/README.md
- cmd/ci-watcher-report/main.go
As per the [documentation](https://github.com/openshift/osde2e/tree/main/cmd/ci-watcher-report), exporting the PagerDuty token as variable `PAGERDUTY_TOKEN` results in below error:
```bash
failed listing incidents: failed listing incidents: failed listing incidents: HTTP response with status code 401 does not contain Content-Type: application/json
exit status 1
```
However, as from [code](https://github.com/openshift/osde2e/blob/main/pkg/common/config/config.go#L784-L786) I came across the variable `PAGERDUTY_API_TOKEN` which works fine. Thus, raised this PR to refer to that var name instead.
> Change PagerDuty Token variable

- pkg/e2e/verify/encrypted_storage.go
Relates to: https://issues.redhat.com/browse/OSD-8762
---
The encrypted_storage tests have been intermittently failing  while creating GCP KMS keys. It's difficult to consistently reproduce these errors, so the exact cause remains uncertain. Regardless, error-handling in this test could be improved, and hopefully the improvements help eliminate this transient error.
> OSD-8762 - Improve error-handling while creating KMS keys.

- pkg/e2e/state/prometheus.go
- pkg/e2e/verify/sccs.go
The `cluster-monitoring-operator` has deprecated the `app=prometheus` label, so it is no longer a reliable way of finding Prometheus pods as of 4.10. [0]
Use `app.kubernetes.io/name=prometheus` instead to find the pods.
[0] https://github.com/openshift/cluster-monitoring-operator/commit/8596875ad058723dcc7719bf37ecdc5d2234c442
> Use the correct label selector for finding prometheus pods

- pkg/e2e/verify/namespace_webhook.go
Due to webhook changes in https://github.com/openshift/managed-cluster-validating-webhooks/pull/171, the namespaces need to be real privileged namespaces and need to match up with the namespaces in managed-cluster-config.
https://issues.redhat.com/browse/OSD-9304
> Update Namespace Webhook Test

- assets/registry/replaces.template
This PR attempts to clean up a stale `grpcurl-query` pod before creating a new one, to reduce the number of failed `should update from previous version` operator tests that occur.
I have observed that our PR check cluster(s) get impacted by stale or leftover `grpcurl-query` pods that are spawned as part of the test to verify operator version upgrades ([example](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_osde2e/944/pull-ci-openshift-osde2e-main-verify/1469980786529669120)). Even though the `oc run` command for the pod has `--rm=true` on it, somehow they're not being cleaned up. Once they're not cleaned up, the `should update..` test will fail forever until someone manually cleans up the leftover pods.
So this PR will delete any leftover pod before running a …
> Clean up stale grpcurl-query pods if they exist

- pkg/common/cluster/healthchecks/pod_predicates.go
- pkg/common/cluster/healthchecks/pods.go
This PR excludes new (< 1 minute old) pods from the health check when looking for not-running pods.
Sometimes frequently-running jobs (ie. `osd-delete-backplane-serviceaccounts`) will regularly cause the health-check to restart due to unfortunate timing of the job spawning right as the health check runs. 
The PR adds a new pod predicate which will only consider pods with a creation timestamp older than a particular time duration, currently hard-coded at NOW()-1 minute. This should cut down on the number of times the health-check has to restart for reasons that will very likely self-resolve.
> Ignore recently-created pods in health check

- pkg/e2e/operators/splunkforwarder.go
This updates the Splunk Forwarder Operator owners to the security team.
https://issues.redhat.com/browse/OSD-9340
> Update Splunk Forwarder Operator Owners

- pkg/e2e/operators/operators.go
This should cause the checkUpgrade function to fail if a latestCSV isn't returned within 5 minutes of looking at an operator's subscription.
> SDCICD-706: wait for a latestCSV status before moving forward or fail

- pkg/e2e/operators/rbac.go
This PR updates the owner of the `rbac-permissions-operator` suite of tests, per OSD-9338.
> Update ownership of rbac-permissions-operator

- pkg/e2e/operators/cloudingress/rhapi_lb.go
This test deletes the Loadbalancer associated with rh-api service and ensures that cloud-ingress-operator recreates it
> OSD-8474 test cloud-ingress-operator rh-api loadbalancer protection

- pkg/e2e/workloads/guestbook/guestbook.go
- pkg/e2e/workloads/redmine/redmine.go
This PR improves the reliability of the `guestbook` workload test and does a general tidy-up of both the `redmine` and `guestbook` workload tests.
I've been observing that the `guestbook` workload test has been failing regularly in E2E lately, after taking a closer look it seems that it makes one attempt to contact the service and if it doesn't respond then the test fails. The test should take into account that the service might take a little while to become ready, though.
So this introduces a minute-long loop of polling the service.
The `redmine` test already had this logic in place, but I noticed it was implemented in a way that could be greatly simplified by just throwing it in a `wait.PollImmediate` block - so I refactored both.
Change has been successfully tested on a staging …
> Handle workload tests more reliably

- pkg/e2e/osd/inhibitions.go
- pkg/e2e/osd/machinehealthcheck.go
using
https://onsi.github.io/ginkgo/MIGRATING_TO_V2#removed-async-testing as a
guide
> update the mhc and inhibition tests for ginkgo v2

- docs/Config.md
- pkg/e2e/operators/certman.go
- pkg/e2e/operators/cloudingress/certificate.go
- pkg/e2e/operators/cloudingress/deletetapps2.go
- pkg/e2e/operators/cloudingress/public_private.go
- pkg/e2e/operators/cloudingress/rhapi_endpoint.go
- pkg/e2e/operators/cloudingress/secondary_router.go
- pkg/e2e/operators/operators.go
- pkg/e2e/operators/routemonitor.go
- pkg/e2e/osd/rebalance_infra_nodes.go
- pkg/e2e/state/prometheus.go
- pkg/e2e/verify/pod_webhook.go
- pkg/e2e/verify/sccs.go
- pkg/e2e/verify/storage.go
- pkg/e2e/verify/user-workload-monitoring.go
- pkg/e2e/workloads/guestbook/guestbook.go
This PR follows up on #936 by
- adding sensible default timeouts to tests that didn't have any
- updating the timeouts in existing tests where the timeouts were too small for what the test is actually doing
> ginkgov2 update test timeouts

- pkg/e2e/verify/encrypted_storage.go
- pkg/e2e/verify/fips.go
Updates timeouts for the `FIPS` and `Encrypted Storage` tests in the `e2e` suite. 
Renames the polling constants in the `Encrypted Storage` test to be less generic and reduces the timeout to 10 minutes.
> Apply appropriate timeouts for the encrypted_storage and fips tests

- pkg/e2e/verify/pods.go
Pods go is attempting to check that all pods for the cluster are up. Increasing this timeout to 30 minutes in order for the Cluster to fully spin up and update if needed.
> Increasing pods.go timeout to 30 minutes

- pkg/e2e/operators/cloudingress/certificate.go
- pkg/e2e/operators/cloudingress/dnsname.go
- pkg/e2e/operators/cloudingress/public_private.go
- pkg/e2e/operators/cloudingress/routeSelector.go
removes time.Sleeps statements, they are unnecessary. removes annotation[owner]-"cloud-ingress-operator" because the test is redundant. Updated the test to adopt GinkgoV2
> Removed time.Sleep statements and Annotation check

- pkg/e2e/operators/ocmagent.go
- pkg/e2e/operators/operators.go
- pkg/e2e/operators/osdmetricsexporter.go
This PR adds initial tests for ocm agent operator as per [OSD-8942](https://issues.redhat.com/browse/OSD-8942). 
Currently `checkService` and `checkUpgrade` tests are disabled and pending investigation    
For reference here's a list of available checks in osde2e (some may not apply to this operator)
```
func checkClusterServiceVersion
func checkConfigMapLockfile
func checkDeployment
func checkPod
func checkServiceAccounts
func checkClusterRoles
func checkClusterRoleBindings
func checkRole
func checkRolesWithNamePrefix
func checkRoleBindingsWithNamePrefix
func checkRoleBindings
func checkSecrets
func checkUpgrade
func checkService
func CheckUpgrade
func CheckPod
```
As part of this PR I've also [updated](https://github.com/openshift/ops-sop/pull/1730/files) testing sop which can be …
> [OSD-8942] add ocm agent e2e test

- ci/create-aro-cluster-ovn.sh
- ci/create-aro-cluster.sh
[SDCICD-752](https://issues.redhat.com/browse/SDCICD-752)
Fixes Disk Encryption Set issues in e2e tests.
Adds a new shell script creating the ARO cluster with the OVN-Kubernetes SDN.
Requires a new secret "des-id"
> Sdcicd 752 fixdes

- pkg/common/config/config.go
Provides a way to specify addon-parameters in vault - in case the parameters contain secret, so it can't be specified in GH repo.
> Add a way to specify the ADDON_PARAMETERS in secret as addon-parameters 

- pkg/common/cluster/healthchecks/pods.go
- pkg/common/cluster/healthchecks/pods_test.go
The compliance operator currently creates [standalone pod resources not associated with a job/cronjob](https://github.com/openshift/compliance-operator/blob/78f9bc867a8a3d67566fa59ab70d11accb98d6b6/pkg/controller/compliancescan/aggregator.go#L24), which end up in a `Succeeded` state, however by way of `osd-cluster-ready`, the following error appears since it calls this checkPods function:
```
2022/03/16 12:40:36 Error(s) running health checks: 1 error occurred:
* pod aggregator-pod-ocp4-moderate in unexpected phase Succeeded: reason:  message:
```
Currently we only allow "Succeeded" pods if it's associated with a job/cronjob, but a standalone pod is another way it could end up in a succeeded state.
> [OHSS-10367] Handle edge case for standalone pod resources

- pkg/common/cluster/healthchecks/pods.go
Because:
* Pod installer-7-ip-... in unexpected phase Failed: reason:  message:
is not all that useful as an error message, and requires an all-namespace search to get a hint at which component's static-pod installer got stuck.
> pkg/common/cluster/healthchecks/pods: Include namespace in error messages

- pkg/common/cluster/healthchecks/pod_predicates.go
- pkg/common/cluster/healthchecks/pods.go
- pkg/common/cluster/healthchecks/pods_test.go
In #940 a PodPredicate for filtering `Completed` pods was removed in order to implement smarter CronJob pod health checks (returning healthy even previously unhealthy CronJob pods, if the most recent one is healthy). However, there was a [bug](https://github.com/openshift/osde2e/compare/main...mjlshen:image-pruner-bugfix?expand=1#diff-140e0200e3dd96daa38c05e5a3877f19ec4b3b11337d50db24ac917f619b2020L133-R160) which resulted in `Completed` job pods to be forwarded along via https://github.com/openshift/osde2e/blob/main/pkg/common/cluster/clusterutil.go#L454-L465 to `CheckPendingPods`. That function does no further checks on the status of the pod, so it's important to only send pending pods to it.
By breaking out the smarter CronJob pod health check to its own function, CheckJobPods, it can …
> [OHSS-10367] CheckClusterPodHealth was incorrectly passing non-pending pods along

- .github/dependabot.yml
Always allow dependabot to run CI tests
> Allow dependabot to run tests

- pkg/common/cluster/healthchecks/pods.go
Completed pods get filtered out by logic after the existing line and before the moved line.
Currently this will log that "X number of pods are not running or complete", but will include completed pods, which causes confusion
> Fix misleading log message as completed pods have not been filtered out yet

- pkg/e2e/osd/machinehealthcheck.go
[OSD-8885](https://issues.redhat.com/browse/OSD-8885) changed the functionality of MHCs in https://github.com/openshift/managed-cluster-config/pull/1085
This updates the osde2e tests to reflect that change to configuration.
fixes [OSD-10459](https://issues.redhat.com/browse/OSD-10459)
> Update MHC tests

- pkg/e2e/osd/machinehealthcheck.go
We know exactly what the configuration should look like, including length, so use `ConsistOf` as the matcher. This may help deflake this test.
> Assert full configuration of MHCs

- pkg/common/cluster/healthchecks/clusterversionoperator.go
- pkg/common/cluster/healthchecks/clusterversionoperator_test.go
In recent E2E runs I observed clusters began failing the cluster health check due to the presence of a new `ReleaseAccepted` condition in CVO which was `true`.
This condition is valid to be true and is not an indication of an unhealthy cluster. This PR allows that condition to be in a `true` state without failing the health check.
The original code that did the analysis of CVO conditions seemed quite confusing to me, so I've tried to refactor and comment it a little to make it read a little cleaner as to what it was trying to do. One omission I noticed in the original code is that it seemed to not care about any situation where 'Available' could be 'False', which seems somewhat wrong to me. So the revised logic is:
- if `Available` is false, that's an unhealthy CVO (hopefully there's not …
> SDCICD-772 allow ReleaseAccepted as a valid CVO condition

- ci/prow_pr_check.sh
- pkg/common/cluster/healthchecks/pods.go
- pkg/common/cluster/healthchecks/pods_test.go
`openshift-marketplace` commonly creates jobs that are 63 characters long, like `c50a055663942c74bda6a897a5331c076ec93c668b2fcc4b5a2c5e0acd6326f`, which was not being handled correctly by the pod healthcheck logic, causing osd-cluster-ready to fail.
> OSD-10981 Handle case when job names are 63 characters long

- go.mod
- go.sum
- pkg/common/helper/helper.go
- pkg/e2e/operators/cloudingress/rhapi_lb.go
Squashed version of https://github.com/openshift/osde2e/pull/1078 
jira https://issues.redhat.com/browse/OSD-8474
Following [OSD-8431](https://issues.redhat.com/browse/OSD-8431), tests need to be added to ensure the code logic is correct.
Done Criteria:
e2e test to delete the rh-api lb on a live cluster and ensure that the lb is recreated in GCP
> osd-8474 e2e test added for GCP CIO load balancer reconcile

- .github/dependabot.yml
There's a number of dependabot PRs that are open but aren't going to be merged quickly due to dependency conflicts. This is preventing other checks for things that are more important (like the ocm sdk).
This doubles the max number of dependabot PRs open
/assign @MrSantamaria
> Double the number of dependabot PRs

- pkg/common/cluster/clusterutil.go
- pkg/common/cluster/healthchecks/pods.go
- pkg/common/cluster/healthchecks/pods_test.go
This removes the `CheckClusterPodHealth` check.
We check other things in `PollClusterHealth` like the state of nodes, clusteroperators, daemonsets/replicasets. These things provide us with a clearer signal, than static pod configurations.
> Remove clusterwide pod healthcheck

- configs/fedramp.yaml
Ticket: https://issues.redhat.com/browse/OSD-10233
This sets up a config file for manual runs(for now) inside the FedRAMP environment. This is the initial config and we will most likely be expanding it with more tests as time goes on and the fedramp env matures some.
> [OHSS-10233] Initial FedRAMP configuration file

- go.sum
- pkg/common/aws/session.go
This gets rid of a dep on prom's log library that is not required and not used in other places in osde2e
/assign @MrSantamaria
> Remove unneeded dependency on promlog

- cmd/osde2e/test/cmd.go
- configs/proxy-suite.yaml
- docs/Config.md
- pkg/common/config/config.go
- pkg/common/providers/crc/crc.go
- pkg/common/providers/mock/mock.go
- pkg/common/providers/ocmprovider/proxy.go
- pkg/common/providers/rosaprovider/wrapped_calls.go
- pkg/common/spi/provider.go
- pkg/e2e/proxy/postinstall.go
This PR adds a new test suite `proxy` which will form the bulk of tests relating to epic [SDE-1634](https://issues.redhat.com//browse/SDE-1634) for testing cluster-wide proxy features on OSD/ROSA clusters.
- `TEST_HTTP_PROXY`: Represents the address of a HTTP Proxy to configure the cluster with.
- `TEST_HTTPS_PROXY`: Represents the address of a HTTPS Proxy to configure the cluster with.
- `USER_CA_BUNDLE`: Represents the User CA Bundle to configure the cluster with.
Documentation for all three parameters has been added.
A new test has been added to the `proxy` suite which will use the OCM API to add a proxy to a pre-existing cluster.
The test verifies that:
- the cluster received the requested configuration change correctly
- the cluster successfully passes a cluster health check …
> OSD-8788 Add proxy test suite and day-2 add-proxy test

- docs/Config.md
- go.mod
- pkg/common/config/config.go
- pkg/common/providers/crc/crc.go
- pkg/common/providers/mock/mock.go
- pkg/common/providers/ocmprovider/cluster.go
- pkg/common/providers/ocmprovider/ocm.go
- pkg/common/providers/ocmprovider/proxy.go
- pkg/common/providers/rosaprovider/cluster.go
- pkg/common/providers/rosaprovider/config.go
- pkg/common/providers/rosaprovider/wrapped_calls.go
- pkg/common/spi/provider.go
- pkg/e2e/operators/cloudingress/rhapi_endpoint.go
- pkg/e2e/osd/dedicatedadmin.go
- pkg/e2e/proxy/postinstall.go
Append the proxy related parameters to the ocm and rosa provider.
To test with OSD cluster:
```
export OCM_CCS=true
export OCM_AWS_ACCOUNT=$AWS_ACCOUNT_ID
export OCM_AWS_ACCESS_KEY=$AWS_ACCESS_KEY_ID
export OCM_AWS_SECRET_KEY=$AWS_SECRET_ACCESS_KEY
export CLOUD_PROVIDER_ID=aws
export OCM_AWS_VPC_SUBNET_IDS=subnet-052ad08ae5fd1b9bd,subnet-0b73c8670379ea008
export TEST_HTTP_PROXY=<test http proxy server>
export TEST_HTTPS_PROXY=<test https proxy server>
export USER_CA_BUNDLE=@ca.pem
export CLOUD_PROVIDER_REGION=us-east-1
export OCM_TOKEN=$(ocm token)
./osde2e test --configs stage -e stage --focus-tests "RBAC Operator"
```
The cluster will be created as 
```
$ ocm describe cluster 1s8f9ur5jq5s83bqe7cuigsfbvgbbdon
ID:			1s8f9ur5jq5s83bqe7cuigsfbvgbbdon
External ID: …
```
> [OSD-11524] enable cluster provision with proxy enabled for osd and rosa

- pkg/e2e/e2e.go
The `oc adm inspect` routines to gather `osde2e-*` project state and `openshift-*` project states are must-gather-like things, and are time consuming to execute at the end of a job. If someone has deliberately disabled the must-gather collection for a job, it is almost assured that they don't want to be gathering this data either.
Therefore, this PR moves those two actions under the control of the Must Gather viper config.
> Only gather project/olm state if must-gather is enabled

- docs/Config.md
- pkg/common/config/config.go
- pkg/common/providers/ocmprovider/cluster.go
- pkg/common/providers/rosaprovider/cluster.go
- pkg/e2e/proxy/postinstall.go
This PR has two goals:
- Add a configuration parameter (`USE_PROXY_FOR_INSTALL`) that controls whether to conduct a proxy-based cluster install. This is being done so that the "Day 2" proxy suite can use the Proxy configuration parameters without the cluster having been installed with a proxy.
- Transform the "Day 2" proxy suite into a test that executes the Add Proxy feature followed by the Remove Proxy one. This is so that we can guarantee that the Add Proxy feature is executed and runs successfully before the Remove Proxy feature is tested.
This has been successfully tested in a staging cluster.
> Add control config param for proxy-based installs

- pkg/common/providers/rosaprovider/wrapped_calls.go
This addresses what looks like a code panic bug in the ROSA provider's OCM-wrapped proxy calls. These functions in their pre-PR state would appear to just be calling themselves over and over and probably blow the stack. They should be using the `ocmProvider`, as is the `wrapped_call` file's intended purpose.
> Fix code panic in ROSA day-2 proxy calls

- pkg/e2e/operators/mnmo.go
This PR adds tests for Managed Node Metadata Operator.
This satisfies [OSD-10051](https://issues.redhat.com//browse/OSD-10051)
> Adds tests for Managed Node Metadata Operator

- pkg/e2e/operators/cloudingress/rhapi_lb.go
The test added in #985 ([OSD-8474](https://issues.redhat.com/browse/OSD-8474)) covering load balancer deletion doesn't currently clean up the security groups left over from deleted load balancers, causing them to become "orphaned" and pile up over time. This PR fixes this bug by recording which security groups are associated with a load balancer pre-deletion, removing any references to said groups (required by AWS in order to delete group), and then deleting these orphan security groups post-LB-recreation.
This PR addresses [OSD-11485](https://issues.redhat.com/browse/OSD-11485), where it was noticed that this bug was causing us to rub up against [AWS's limits](https://docs.aws.amazon.com/vpc/latest/userguide/amazon-vpc-limits.html#vpc-limits-security-groups) on security group quantity. …
> Clean up security groups orphaned by AWS LB deletion test

- Makefile
We're using a bit of an older version, and I've seen some flakes.
I tested this version locally and it works like a charm. Hopefully CI agrees.
> Bump golangci-lint version

- pkg/e2e/operators/cloudingress/publishingstrategies_cr.go
* Test doesn't seem to be necessary as cluster-admins shouldn't create publishing strategies themselves
* Publishing strategies should be pushed by OCM
* This test breaks the OpenShift console, resulting in an alert that fails osde2e
Jira: [OSD-11389](https://issues.redhat.com//browse/OSD-11389)
> Disable cluster-admin publishing strategy test

- go.mod
- go.sum
- pkg/common/providers/rosaprovider/cluster.go
Bumps the github.com/openshift/rosa from 1.2.2 to 1.2.4, and fixes the rosaprovider to use the correct logging methods
/assign @MrSantamaria
> Bump github.com/openshift/rosa from 1.2.2 to 1.2.4

- pkg/e2e/state/prometheus.go
Completes: https://issues.redhat.com/browse/OSD-12641
---
Refactors the runner pod's command to copy data in `openshift-monitoring/prometheus-k8s-0`'s `/prometheus` directory directly to the runner. This is required for `4.11`, as prometheus's `securityContext` has been updated to include `readOnlyRootFilesystem: true`.
> Update copy method to avoid ReadOnly disk issues

- pkg/common/cluster/healthchecks/replicas.go
- pkg/common/cluster/healthchecks/replicas_test.go
This will reduce some alert noise for the primary oncall. Indeed KubePodCrashLooping incidents are currently fired to us for DS and RS namespaces we (SREP) do not manage.
> Making sure healthchecks only concern daemon sets and replica sets managed by OSD (i.e. in a namespace starting with "openshift-")

- pkg/e2e/operators/operators.go
- pkg/e2e/osd/olm.go
- Rewrites the operator `checkUpgrade` function to be more resilient to bad Subscription states.
- Introduces a new `informing` test to validate the state of all managed operator subscriptions on the cluster.
The `should upgrade from the replaced version` operator tests have long been a randomly failing, flaky test in our E2E suite. It finally dawned on me that [BZ1980755](https://bugzilla.redhat.com/show_bug.cgi?id=1980755) could have been the culprit all along. After checking a few must-gathers from runs where the test failed, this theory turned out to be correct.
I have rewritten the `checkUpgrade` test to be able to operate successfully even if a cluster's subscriptions are in a state impacted by BZ1980755. It has been successfully tested on a cluster that is impacted by BZ1980755 and …
> Rewrite Operator "CheckUpgrade" test

- pkg/common/config/config.go
No longer treat the RDS postgres DB port as a secret.
We regularly end up with test failures in TestGrid that fail for reasons of being unable to parse the junit xml. [0] [1] [2]
This has been bugging me for a while. The XMLs validated schema checks in `xmllint`. So I ended up writing a simple client to run the xml through TestGrid's parsing function [3], and could then reproduce the error. From there, I was able to hone in on the problem: every junit file that has failed features a test with `XXXX` randomly inserted into the `<testcase>` timestamp.
The reason is because we treat the E2E RDS DB postgres port as a secret. As soon as this number appears in a test artifact file, it is replaced with `XXXX`. Whenever we get a timestamp with the number `5432` in it (which amazingly happens on a …
> Do not treat postgres port like a secret

- pkg/e2e/verify/sccs.go
Increase the timeout for the `new SCC does not break pods` test from 3 minutes to 4 minutes.
This is another quite flaky test. My analysis of failed runs has shown that the current 3 minute wait period is just slightly too short. As in, by barely 5-10 seconds each time. The test bounces the Prometheus pods and then waits for them to come back Ready. From checking the must-gathers of failed runs, I can see that it's transitioning to a `ContainersReady` state barely 5 seconds after the test timeout.
By bumping the test timeout by a minute I'm hoping that it addresses this.
A valid question is, "why is it taking 3 minutes for Prometheus to restart?". The answer to which I am not sure, or at least it is difficult to discern that quickly from the events in the namespace via the must-gather.
> Increase timeout for SCC RBAC test

- pkg/e2e/verify/namespace_webhook.go
Adds pod-security labels when creating namespaces
TRT is tracking down failed jobs / tests cause by the recent [Pod Security Admission changes](https://docs.openshift.com/container-platform/4.11/authentication/understanding-and-managing-pod-security-admission.html).
A [search](https://search.ci.openshift.org/?search=forbidden%3A+violates+PodSecurity&maxAge=336h&context=1&type=build-log&name=.*ocp-osd.*&excludeName=pull.*&maxMatches=5&maxBytes=20971520&groupBy=job) turned up hits for this project.
```
release-openshift-ocp-osd-aws-nightly-4.12` (all) - 54 runs, 100% failed, 54% of failures match = 54% impact
release-openshift-ocp-osd-gcp-nightly-4.12 (all) - 54 runs, 100% failed, 41% of failures match = 41% impact
```
```
pod Create API error: pods "pvc-tester-8bbqd" is forbidden: violates …
```
> Address Pod Security Admission Failures

- configs/pr-check.yaml
pr-check config in order to not run the full e2e-suite during PRs
> Adds pr-check config

- pkg/common/config/config.go
Moving Hibernation to be available behind flags.
Clusters will now delete post e2e suite being ran.
> Putting-hibernation-behind-flags

- docs/Config.md
- pkg/common/providers/rosaprovider/cluster.go
- pkg/common/providers/rosaprovider/config.go
```
Flag --compute-nodes has been deprecated, use --replicas instead
Flag --master-iam-role has been deprecated, use --controlplane-iam-role instead
```
resolves #1340
> rosaprovider: replace deprecated arguments

- pkg/common/providers/rosaprovider/cluster.go
Remove redudant `operator-roles` and `oidc-provider` create command executions as these are already ran when running the create cluster command[1]. This is currently causing a prompt to show (shown below) due to another bug of not enough arguments being supplied to the `create operator-roles` cmd (permission boundary). Since `mode` is set to `auto`, `create cluster` command does the heavy lifting for cluster setup.
```
export CLEAN_CHECK_RUNS="3"
export POLLING_TIMEOUT="5"
export PROVIDER=rosa
export ROSA_STS=true
dlv debug ./cmd/osde2e/ -- test --configs "e2e-suite"
```
```
...
I: Cluster 'osde2e-uqybc' has been created.
...
I: Preparing to create operator roles.
I: Creating roles using 'arn:aws:iam::..:user/osdCcsAdmin'
...
I: Preparing to create OIDC Provider.
I: Creating OIDC provider …
```
> rosaprovider: remove redudant sts cluster setup

- Makefile
go get \<binary\> is deprecated
required for https://github.com/openshift/release/pull/33570
failing for:
```
GOFLAGS='' go get github.com/markbates/pkger/cmd/pkger
pkger --include /go/src/github.com/openshift/osde2e/assets --include /go/src/github.com/openshift/osde2e/configs
make: pkger: Command not found 
```
> go install pkger

- pkg/common/cluster/clusterutil.go
- pkg/common/config/config.go
- pkg/common/providers/rosaprovider/cluster.go
- pkg/e2e/e2e.go
The current use of the DestroyAfterTest flag is causing the pipeline to show as failed since it's not exiting gracefully. 
We need to be able to destroy clusters after runs in order to clean up STS resources during the same run as the delete cluster functions won't clean up the Cloud accounts.
> SDCICD-821 - DestroyAfterTest flag Debug

- .golang-ci.yml
- Makefile
deadcode and structcheck are both deprecated/abandoned and replaced by unused
> bump golangci-lint to v1.50.1

- pkg/common/alert/alert.go
all of the calls to RegisterGinkgoAlert are setting threshold to 4 anyway, so no behavior is changing with this but let's actually use the parameter to set the threshold in case it will be set to something different in the future.
```
pkg/e2e/openshift/images.go
17:	alert.RegisterGinkgoAlert(imageRegistryTestName, "SD-CICD", "Diego Santamaria", "sd-cicd-alerts", "sd-cicd@redhat.com", 4)
18:	alert.RegisterGinkgoAlert(imageEcosystemTestName, "SD-CICD", "Diego Santamaria", "sd-cicd-alerts", "sd-cicd@redhat.com", 4)
pkg/e2e/openshift/app_builds.go
47:	alert.RegisterGinkgoAlert(appBuildsTestName, "SD-CICD", "Diego Santamaria", "sd-cicd-alerts", "sd-cicd@redhat.com", 4)
pkg/e2e/openshift/conformance.go
33: …
```
> actually use failure threshold for alerts

- pkg/common/helper/helper.go
> fix core/v1 api imported twice

- go.mod
- go.sum
- pkg/common/providers/rosaprovider/cluster.go
- pkg/e2e/operators/cloudingress/rhapi_lb.go
It is no longer needed to create specific roles which will help with the cluttering of the AWS account
/hold
> SDCICD-760: remove unneeded sts account setup

- Dockerfile.osde2e
This commit addresses the following:
1. Bump the golang image tag to 1.18 to stay inline with go.mod go version defined
2. Bump ubi to version 8 as 7 full support has ended and is only in extended life cycle support
> Bump osde2e dockerfile parent images tags

- pkg/common/logging/logging.go
std log is set up in cmd/osde2e/main.go, any new loggers created should
match those settings for consistency
> common/logging: add Lshortfile flag for consistency

- pkg/common/aws/s3.go
- pkg/common/providers/ocmprovider/cluster.go
When the jobName setting is defined, osde2e attempts to write metrics to s3 bucket. When updating with cluster properties, it was silently continuing on when the upload to s3 was failing. Added a conditional check to return when errors occur.
Also includes checking the error returned when uploading to s3 bucket. When successful, then print the message to the console stating the upload to message. This helps to clean up the logs.
> Handle error when writing metrics to s3 bucket for cluster properties

- pkg/common/runner/runner.go
- pkg/e2e/addons/addon_test_harness.go
- pkg/e2e/e2e.go
skip over printing that is not relevant (local run, no addons) and use the same settings on common/runner logger as the rest of the codebase
> various logging cleanup

- pkg/common/providers/ocmprovider/cluster.go
- pkg/common/providers/ocmprovider/config.go
remove the ccs.overwrite setting and logic as it is no longer needed/used
> providers/ocmprovider: remove ccs overwrite logic

- docs/Config.md
- pkg/common/config/config.go
- pkg/e2e/e2e.go
allow for controlling the ginkgo reporter output which can be set to one
of `succinct` (default), `v` (verbose, printing GinkgoWriter output) and
`vv` (very-verbose, including skipped and pending tests). This will
allow tests to then use the `GinkgoWriter` and improve the output of
osde2e.
https://onsi.github.io/ginkgo/#controlling-ginkgos-output
> support setting ginkgo loglevel

- pkg/e2e/operators/cloudingress/apischeme_cr.go
- pkg/e2e/operators/cloudingress/certificate.go
- pkg/e2e/operators/cloudingress/deletetapps2.go
- pkg/e2e/operators/cloudingress/dnsname.go
- pkg/e2e/operators/cloudingress/installed.go
- pkg/e2e/operators/cloudingress/public_private.go
- pkg/e2e/operators/cloudingress/publishingstrategies_cr.go
- pkg/e2e/operators/cloudingress/rhapi_endpoint.go
- pkg/e2e/operators/cloudingress/routeSelector.go
- pkg/e2e/operators/cloudingress/secondary_router.go
- pkg/e2e/operators/cloudingress/upgrade.go
half of the tests are already set to skip on STS being configured and CIO is not deployed to an STS cluster so these tests fail anyway. No pipeline is currently testing ROSA STS so it hasn't been noticed/fixed.
> e2e/operators/cloudingress: skip on STS

- docs/Config.md
This PR reformats the markdown file declaring osde2e configuration settings.
Includes:
* Update table formatting making it cleaner when looking at the raw file
* Alter the aws specific values to be a proper table
> Reformat Config.md

- pkg/e2e/osd/machinehealthcheck.go
OSD has added support for metal instance types with a separate machinehealthcheck. this updates the worker rule matchers and adds tests to confirm the presence of the metal mhc
> OSD-13922 update machinehealthcheck tests for metal instance support

- pkg/e2e/osd/dedicatedadmin.go
Removes two broken tests from the dedicated-admin informing test suite.
Whilst reviewing #1404, I noticed these had been failing for what seems like forever in the testgrid results.
As best I can tell, they are not really valid:
1. They purport to test `dedicated-admin`'s ability to update the `cluster-admins` group, but they are not actually testing any changes to the `cluster-admins` group.
2. This is something that our RBAC explicitly allows anyway [0], so these tests are expecting a failure condition that will never occur.
[0] https://github.com/openshift/managed-cluster-config/blob/74e57e82ff5cabd78a1d0410396d857e88fda704/deploy/rbac-permissions-operator-config/05-dedicated-admins-aggregate-cluster.ClusterRole.yaml#L213
> Remove unneeded dedicated-admin tests

- pkg/common/util/util.go
according to the documentation, Offset allows `... you to adjust the location of a node reported by Ginkgo (this is useful when building shared libraries that generate their own Ginkgo nodes).` which fixes the incorrect test location being printed by the test name.
before:
```
[Suite: operators] CloudIngressOperator publishingstrategies dedicated admin should not be allowed to manage publishingstrategies CR
/var/home/bpratt/git/openshift/osde2e/pkg/common/util/util.go:44
```
after:
```
[Suite: operators] CloudIngressOperator publishingstrategies dedicated admin should not be allowed to manage publishingstrategies CR
/var/home/bpratt/git/openshift/osde2e/pkg/e2e/operators/cloudingress/publishingstrategies_cr.go:30
```
> common/util: set ginkgo.Offset for GinkgoIt helper

- pkg/e2e/operators/dvo.go
this gets ran immediately since it is outside of a test and setup/teardown
also remove log outside of tests (printed on start)
before
```
$ TEST_KUBECONFIG=rosa-kubeconfig ROSA_STS=true ginkgo run -v --focus "dvo"
Enterned Check Pod Logs
2022/11/22 06:32:59 Deleting namespace for namespace validation webhook (osde2e-dvo-test)
Assertion or Panic detected during tree construction
var _ = ginkgo.Describe(deploymentValidationOperatorTestName, func() {
/var/home/bpratt/git/openshift/osde2e/pkg/e2e/operators/dvo.go:31
Ginkgo detected a panic while constructing the spec tree.
You may be trying to make an assertion in the body of a container node
(i.e. Describe, Context, or When).
Please ensure all assertions are inside leaf nodes such as BeforeEach, …
```
> e2e/operators/dvo: delete ns afterall

- cmd/osde2e/test/cmd.go
- pkg/common/config/config.go
- pkg/e2e/e2e.go
This PR adds the initial ground work for enabling the ability to use ginkgo labels. It provides the ability for osde2e to accept a label filter query to pass to ginkgo. Where ginkgo can use that to decide which test cases it should execute.
Labels are going to play a large role as we work towards defining standardization and consistency across all OSD operator tests. Labels are a way to easily tag test cases.
With the use of labels, we can fine tune new tests and existing tests cases based on a standard set of supported labels (list will be provided next week for review/discussion).
Labels can be applied to both ginkgo describe nodes (test suites) and ginkgo it nodes (test cases).
*Example*: Test suites can define a label such as `operators` or `<specific-operator>`, then within the …
> Add support for using ginkgo labels

- pkg/e2e/osd/dedicatedadmin.go
Add test case for dedicated admin user:
-  can patch **consoles.operator.openshift.io**
_Fix_ :  [OSD-13651](https://issues.redhat.com/browse/OSD-13651)
> [OSD-13651] add test for dedicated admin can patch console

- pkg/common/config/config.go
- pkg/common/helper/helper.go
loading kubeconfig on helper setup allows for running the tests directly with ginkgo and an existing cluster (outside of the framework) which is easier for development
also add additional check to no-op `LoadKubeconfig` after the first call (we call helper.Setup() a lot)
> common: load kubeconfig on helper setup

- pkg/common/cluster/clusterutil.go
- pkg/common/providers/rosaprovider/cluster.go
1. Set the install time for HCP clusters to 30 minutes. 
2. Increased the uninstall wait time to 30 after seeing an increase in pipeline failures:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/osde2e-hypershift-stage/1597651843805089792
Locally running the hypershift pipeline there was an average uninstall time of 22 minutes.
> OSDe2e update hypershift un/install times

- pkg/common/helper/helper.go
deletion is happening after the namespace deletion which takes this service account with it, an error is always printed for this failed:
"Error deleting dedicated-admin serviceaccount for 'osde2e-omwhi': serviceaccounts "osde2e-omwhi" not found"
> common/helper: remove dedicated-admin service account deletion

- pkg/common/constants/constants.go
- pkg/e2e/operators/cloudingress/apischeme_cr.go
- pkg/e2e/operators/cloudingress/certificate.go
- pkg/e2e/operators/cloudingress/cloudingress.go
- pkg/e2e/operators/cloudingress/deletetapps2.go
- pkg/e2e/operators/cloudingress/dnsname.go
- pkg/e2e/operators/cloudingress/installed.go
- pkg/e2e/operators/cloudingress/public_private.go
- pkg/e2e/operators/cloudingress/publishingstrategies_cr.go
- pkg/e2e/operators/cloudingress/rhapi_endpoint.go
- pkg/e2e/operators/cloudingress/rhapi_lb.go
- pkg/e2e/operators/cloudingress/routeSelector.go
- pkg/e2e/operators/cloudingress/secondary_router.go
- pkg/e2e/operators/cloudingress/upgrade.go
As we work towards improving the quality of the tests and test standards. Test case tagging will be applied eventually to all tests. What this means is, test suites will no longer need to define the type of test (e.g. informing, operator, e2e) within the string and will be applied using a label.
These constants being removed have only been used by a handful of tests and others were hard coded into the string in their test suite names. These tests have been updated to hard code the string for now as these will eventually be removed in a future PR (when labels are applied).
> Drop the constants package in efforts for test case tagging

- pkg/common/label/label.go
Add a common label package defining a set of Ginkgo labels that can be used for classifying tests based on what they are doing, what they support, and how important they are. These labels will be introduced to tests in following patches to provide a path forward for converting from mainly using the focus filter to utilizing labels.
Labels provide a great way of grouping tests while not losing the focus ability currently used today. This should enhance the ability to pick tests based on the specific criteria when used in combination with the focus-filter flag.
This list is not all encompassing, new labels can be added as required and old labels that are no longer relevant should be removed. This list roughly covers the initial requirements for refactoring a handful of tests. Any label …
> common/label: initial commit of ginkgo labels

- pkg/common/helper/helper.go
Hotfix to let the hypershift pipeline return to green. 
Currently created RoleBindings are not available for projects using HostedControlPlanes. 
This PR should be reverted once it is enabled for those clusters. 
Context: https://coreos.slack.com/archives/CMK13BP4J/p1670013812995159
> Hypershift - Skip check for RoleBindings in Project

- go.mod
- go.sum
- pkg/e2e/e2e.go
The current implementation will generate the junit report during the
RunSpecs function call using the standard junit report config settings
defined.
With the introduction of labels "test tagging", the labels are now
going to be appended to the test case name within the junit xml. Every
time a label is either added/modified/deleted, it will alter the test
case name. Presenting different test case names when viewing results
from local runs, runs in prow or results in test grid.
This commit modifies osde2e to generate the junit report with config
settings after the test have finished. Allowing for customizing the way
the junit report is built.
Initial junit report config settings are:
1. Omit labels from displaying within test case names
Needed to tag ginkgo to a specific commit to get the …
> Generate junit report with customized settings after tests finished

- pkg/e2e/osd/machinehealthcheck.go
- pkg/e2e/osd/ocm.go
- pkg/e2e/state/alerts.go
- pkg/e2e/state/prometheus.go
- pkg/e2e/verify/encrypted_storage.go
- pkg/e2e/verify/fips.go
- pkg/e2e/verify/imagestreams.go
- pkg/e2e/verify/namespace_webhook.go
- pkg/e2e/verify/pods.go
- pkg/e2e/verify/prom_exporters.go
- pkg/e2e/verify/routes.go
- pkg/e2e/verify/samesite_cookie.go
- pkg/e2e/verify/sccs.go
- pkg/e2e/verify/storage.go
- pkg/e2e/verify/strict_transport_security.go
- pkg/e2e/verify/validation_webhook.go
- pkg/e2e/workloads/guestbook/guestbook.go
- pkg/e2e/workloads/redmine/redmine.go
Amend the `label.E2E` to each `Describe` within the `Suite: e2e` to
allow executing these tests based on label rather than focus-filter.
Focus filter will continue working as is. Eventually (once the initial
label introduction is complete), the configs will be updated to use
labels and/or focus where applicable.
depends on #1432
/hold
> Introduce e2e label

- pkg/common/label/label.go
- pkg/e2e/operators/certman.go
- pkg/e2e/operators/cloudingress/apischeme_cr.go
- pkg/e2e/operators/cloudingress/installed.go
- pkg/e2e/operators/cloudingress/publishingstrategies_cr.go
- pkg/e2e/operators/cloudingress/rhapi_endpoint.go
- pkg/e2e/operators/cloudingress/rhapi_lb.go
- pkg/e2e/operators/configurealertmanager.go
- pkg/e2e/operators/customdomains.go
- pkg/e2e/operators/managedvelero.go
- pkg/e2e/operators/mustgather.go
- pkg/e2e/operators/osdmetricsexporter.go
- pkg/e2e/operators/prunejob.go
- pkg/e2e/operators/rbac.go
- pkg/e2e/operators/splunkforwarder.go
- pkg/e2e/osd/inhibitions.go
This change is amending to the existing operator tests describe nodes.
Which allows the suite of tests to be executed using ginkgos label
filter feature over using the focus filter.
Focus filter will continue to work as the string `Suite: operators`
still exists within the test case names. It will eventually be removed
in replacement of the label identifiers.
Closes [SDCICD-860](https://issues.redhat.com//browse/SDCICD-860)
> Introduce the operators label to the existing operator tests

- pkg/common/label/label.go
- pkg/e2e/osd/daemonsets.go
- pkg/e2e/osd/nodelabels.go
- pkg/e2e/osd/privileged.go
- pkg/e2e/verify/regularuser_webhook.go
This change is amending to the existing tests describe nodes. Which allows the suite of tests to be executed using ginkgos label filter feature over using the focus filter.
Focus filter will continue to work as the string Suite: service-definition still exists within the test case names. It will eventually be removed in replacement of the label identifiers.
Closes [SDCICD-861](https://issues.redhat.com//browse/SDCICD-861)
> Introduce the service definition label to the existing tests

- pkg/common/providers/rosaprovider/cluster.go
ROSA cli using STS as default was reverted and the STS pipeline is failing to deploy
https://github.com/openshift/rosa/commit/d7e5ce180cdbfbc38cc3c6a2d347f1b90ec5b465
> common/providers: set `--sts` if STS is set

- pkg/e2e/operators/splunkforwarder.go
SFO is not deployed the same as on non-hypershift clusters, these tests will need to be skipped until a solution comes out of [OSD-11605](https://issues.redhat.com//browse/OSD-11605)
[SDCICD-868](https://issues.redhat.com//browse/SDCICD-868)
> e2e/operators/splunkforwarder: skip on hypershift

- pkg/common/label/label.go
- pkg/e2e/openshift/app_builds.go
This change is amending to the existing tests describe nodes. Which allows the suite of tests to be executed using ginkgos label filter feature over using the focus filter.
Focus filter will continue to work as the string Suite: app-builds still exists within the test case names. It will eventually be removed in replacement of the label identifiers.
For [SDCICD-862](https://issues.redhat.com//browse/SDCICD-862)
> Introduce the app builds label to the existing tests

- go.mod
- go.sum
Previously was locked to a given commit for features that were not released yet. Those features are now available in latest official tag.
Features osde2e required were released as part of ginkgo [2.6.0](https://github.com/onsi/ginkgo/releases/tag/v2.6.0).
> Switch ginkgo back to using the official tag for install

- pkg/common/util/util.go
- pkg/e2e/openshift/app_builds.go
- pkg/e2e/openshift/disruptive.go
- pkg/e2e/openshift/images.go
- pkg/e2e/verify/pods.go
- pkg/e2e/verify/storage.go
- pkg/e2e/verify/strict_transport_security.go
Jira: https://issues.redhat.com/browse/SDCICD-869 
1. Replaced occurrences of hardcoded timeouts with viper config
2. Updated GinkgoIt wrapper to default timeout to viper config when not provided.  - reverted
> sdcicd-869 remove hardcoded timeouts, default timeout to POLLING_TIMEOUT

- configs/hypershift.yaml
- pkg/e2e/openshift/hypershift/verifyInstall.go
This change covers the following:
1. Add the HyperShift label to the verifyinstall test suite
2. Use label filter for selecting HyperShift tests to run over using focus strings
3. Uses the kubernetes-sigs/e2e-framework client to interface with the cluster. Used to get the list of worker nodes in the cluster.
4. Reformatted test case name to remove duplicate words
**Before**
```
<testcase name="[Suite: hypershift] Verify Hypershift worker node in CCS Account Worker nodes are available in AWS" classname="OSD e2e suite" status="passed" time="0.703881072">
```
**After**
```
<testcase name="HyperShift worker nodes are available in aws ccs account" classname="OSD e2e suite" status="passed" time="0.702320559">
```
For [SDCICD-878](https://issues.redhat.com/browse/SDCICD-878)
> HyperShift tests maintenance

- pkg/e2e/openshift/hypershift/verifyInstall.go
Since the test suite is ordered, we can use beforeall to initialize the helper/client once before running any of the test cases. Changed requested for commit https://github.com/openshift/osde2e/commit/e281f614b76eb55040ad051fc1ac22e664d26a74#r95514958
> Initialize variables using beforeall for hypershift install tests

- pkg/e2e/osd/nodelabels.go
As part of the [openshift dedicated service definition](https://docs.openshift.com/dedicated/osd_architecture/osd_policy/osd-service-definition.html#node-labels_osd-service-definition), users are unable to add custom node labels after the nodes are created. This same service definition applies to hypershift clusters.
Uses the kubernetes-sigs/e2e-framework client to interface with OpenShift objects and cleans up the test case name.
For [SDCICD-884](https://issues.redhat.com/browse/SDCICD-884)
```
<testcase name="[Suite: service-definition] [OSD] Node labels cannot be modified after node creation" classname="OSD e2e suite" status="passed" time="0.281066853">
<system-err>> Enter [BeforeAll] [Suite: service-definition] [OSD] Node labels - /home/rywillia/osd/osde2e/pkg/e2e/osd/nodelabels.go:26 …
```
> Enable node labels tests as part of hypershift suite

- assets/terraform/setup-vpc.tf
This is ripped straight from hackday. Eventually we can hook this up to
run on cluster creation/deletion to allow more dynamic hypershift
cluster provisioning. If the regions validation falls out of date, we can
remove it and depend on the input provided by osde2e to be correct/validated
ahead of time against the api. It'd probably be worth adding additional
variables to allow further customization but this works for now.
thanks @wgordon17 :)
> add terraform for BYOVPC

- pkg/e2e/osd/privileged.go
This commit adds the privileged containers tests to be included as part of the hypershift suite. These tests validate the service definition for privileged containers for osd.
Includes:
* Remove unneeded test verifying unprivileged container
* Use kubernetes-sigs/e2e-framework client
* Restrict pod to ignore container restarts
* Add new test to verify cluster-admin users can created privileged containers
For [SDCICD-891](https://issues.redhat.com/browse/SDCICD-891)
JUnit results
```xml
<testcase name="[Suite: service-definition] [OSD] Privileged Containers are not available by default" classname="OSD e2e suite" status="passed" time="0.215065118">
<system-err>> Enter [BeforeAll] [Suite: service-definition] [OSD] Privileged Containers - /home/rywillia/osd/osde2e/pkg/e2e/osd/privileged.go:28 …
```
> Enable privileged containers tests as part of hypershift suite

- pkg/common/expect/expect.go
this was misplaced causing an error instead of decorating the expect
> common/expect: fix NoError description

- pkg/e2e/osd/nodelabels.go
Hypershift clusters do not have the clusterrole dedicated-admin available. Only cluster-admin is available. Since this test requires the use of the dedicated-admin clusterrole, it will always fail. Resulting in not being able to perform actions against nodes.
Both these clusterroles exist on regular rosa clusters, resulting no impact to that cluster configuration. Test runs as expected.
**HyperShift**
```
[rywillia@t14s tf-stage]$ oc get clusterroles | grep dedicated-admin
[rywillia@t14s tf-stage]$ oc get clusterroles | grep cluster-admin
cluster-admin                                                                                       2023-01-13T14:12:26Z
```
**Rosa cluster**
```
[rywillia@t14s tf-stage]$ oc get clusterroles | grep dedicated-admin
dedicated-admins-aggregate-cluster …
```
> Remove node labels service definition test as part of hypershift suite

- pkg/e2e/verify/routes.go
it seems to not exist at first on a cluster. Also turn this into a table test!
/assign @ryankwilliams
> e2e/verify/routes: wait for console route to exist

- cmd/osde2e/test/cmd.go
- configs/informing-suite.yaml
- pkg/common/helper/impersonate.go
- pkg/e2e/operators/ocmagent.go
- pkg/e2e/operators/ocmagent/ocmagent.go
- pkg/e2e/operators/operators.go
This commit modifies the existing ocm agent operator tests to follow the
new consistent set of standards for writing test cases. Changes consist
of the following:
1. Reformatted the test case names
2. Uses the kubernetes-sigs/e2e-framework client (kclient) allowing the
tests to dynamically interact with the objects.
3. Use the available wait for conditions provided by
kubernetes-sigs/e2e-framework to verify objects reach desired state.
4. Fix operator upgrade test to increase upgrade poll count. Seeing
inconsistent times when performing upgrades. Average time takes
around 18 minutes.
5. Removed test case where it was checking for pods in the operators
namespace (redundant).
6. Labels working as expected:
* --label-filter "Operators && Informing" --focus-tests "OCM Agent
Operator"
* …
> Apply test case standards to ocm agent operator tests

- pkg/common/providers/rosaprovider/cluster.go
A recent commit has started to append openshift-v prefix to the version string passed to rosa create cluster. This results in rosa create cluster to fail as it is looking for a string with the format of <major.minor.patch>. Prefix openshift-v is acceptable for standard osd clusters provisioned by ocm.
**Failure example**
https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/periodic-ci-openshift-osde2e-main-rosa-stage-e2e-default
```
2023/01/16 18:01:11 cluster.go:213: [--cluster-name osde2e-492j4 --region XXXXXXXXX --channel-group stable --version openshift-v4.11.21 --expiration-time 2023-01-17T00:01:11Z  --replicas 2    --host-prefix 0 --mode auto --yes --properties JobID:-1 --properties OwnedBy:1006210000 --properties InstalledVersion:openshift-v4.11.21 --properties …
```
> Remove openshift-v prefix from version option for rosa create cluster

- pkg/e2e/operators/certman.go
- pkg/e2e/operators/cloudingress/apischeme_cr.go
- pkg/e2e/operators/cloudingress/certificate.go
- pkg/e2e/operators/cloudingress/deletetapps2.go
- pkg/e2e/operators/cloudingress/dnsname.go
- pkg/e2e/operators/cloudingress/installed.go
- pkg/e2e/operators/cloudingress/public_private.go
- pkg/e2e/operators/cloudingress/publishingstrategies_cr.go
- pkg/e2e/operators/cloudingress/rhapi_endpoint.go
- pkg/e2e/operators/cloudingress/rhapi_lb.go
- pkg/e2e/operators/cloudingress/routeSelector.go
- pkg/e2e/operators/cloudingress/secondary_router.go
- pkg/e2e/operators/cloudingress/upgrade.go
- pkg/e2e/operators/configurealertmanager.go
- pkg/e2e/operators/customdomains.go
- pkg/e2e/operators/dvo.go
- pkg/e2e/operators/managedupgrade.go
- pkg/e2e/operators/managedvelero.go
- pkg/e2e/operators/mustgather.go
- pkg/e2e/operators/ocmagent/ocmagent.go
- pkg/e2e/operators/osdmetricsexporter.go
- pkg/e2e/operators/prunejob.go
- pkg/e2e/operators/rbac.go
- pkg/e2e/operators/routemonitor.go
- pkg/e2e/operators/splunkforwarder.go
skip operator tests on hypershift since these are not deployed to the hosted cluster
- certman
- customdomains
- managedupgrade
- cloudingress
- configurealertmanager
- ocmagent
- prunejobs
- rbac
- managedvelero
[SDCICD-897](https://issues.redhat.com//browse/SDCICD-897)
```
❯ HYPERSHIFT=true TEST_KUBECONFIG=autumn2-kubeconfig ginkgo run
2023/01/17 05:12:19 Setup called for osde2e-4i9k6
2023/01/17 05:12:19 Created SA: dedicated-admin-project
2023/01/17 05:12:19 Created SA: dedicated-admin-cluster
2023/01/17 05:12:19 Created SA: cluster-admin
Running Suite: osde2e - /var/home/bpratt/git/openshift/osde2e
=============================================================
Random Seed: 1673953935
Will run 110 of 110 specs …
```
> e2e/operators: skip on hypershift

- pkg/e2e/scale/mastervertical.go
- pkg/e2e/scale/nodes_and_pods.go
- pkg/e2e/scale/performance.go
these tests are either currently not supported on hosted clusters or they are failing (http)
```
$ oc logs scale-ci-http-bxtf4 -n scale-ci-tooling
exec /root/workload/run.sh: permission denied
```
```
...
TASK [Get cluster name] ********************************************************
task path: /src/github.com/openshift-scale/workloads/workloads/podvertical.yml:46
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "oc get machineset -n openshift-machine-api -o=go-template='{{index (index .items 0).metadata.labels \"machine.openshift.io/cluster-api-cluster\"}}'\n", "delta": "0:00:00.857721", "end": "2023-01-17 13:34:31.373731", "msg": "non-zero return code", "rc": 1, "start": "2023-01-17 13:34:30.516010", "stderr": "error: the server doesn't have a resource type \"machineset\"", …
```
> e2e/scale: disable on hypershift

- pkg/common/helper/helper.go
this print is incredibly noisy since it this code path is called every time we create a new helper (every test) and the tests mainly use one namespace anyway
> common/helper: remove setting project print

- README.md
- configs/e2e-suite.yaml
- configs/informing-suite.yaml
Now that all test cases have been tagged with an initial label based on their previous test type (e.g. e2e, operator). This commit updates the configs selecting these tests to use label filters over focus strings.
This will now allow for cleaner test case names, removing the need to have (e.g. Suite: e2e, Suite: operator) within the name. These classifications are controlled by the tags "labels".
Updates both the e2e-suite and informing-suite configs as they are the primary configs used by the periodic jobs.
Includes an updated README describing how users of osde2e can select tests to run.
For [SDCICD-899](https://issues.redhat.com/browse/SDCICD-899)
Tested locally against rosa stage sts cluster. Below is for the `e2e-suite`.
* Focus strings
```xml
<?xml version="1.0" encoding="UTF-8"?> …
```
> SDCICD-898: Use label filters for osde2e configs over focus strings

- .github/dependabot.yml
The version in dependabot wasn't meant to be upped with changes to the yaml but dependabots api version.
> Change dependabot version to 2.

- configs/fedramp.yaml
- configs/fips.yaml
- pkg/common/config/config.go
- pkg/common/providers/rosaprovider/cluster.go
- pkg/e2e/verify/fips.go
fips is supported on ROSA and should be tested. This adds support for deploying fips enabled clusters through osde2e
> SDCICD-915: support fips through rosaprovider

- pkg/common/providers/ocmprovider/cluster.go
[SDCICD-848](https://issues.redhat.com/browse/SDCICD-848)
It seems the logic to append the newcluster with CCS enabled must have been deleted. 
Edit: It was removed when I reworked the subnetID gating the CCS logic over here:
https://github.com/openshift/osde2e/commit/c78f92ec7dd4540aaeb149b64d2c18da2b1ddafc
> SDCICD-848 - Fix OSD CCS flow

- pkg/e2e/e2e.go
Currently after test execution finishes, some clean up tasks are performed and then it checks if test failures occurred, it will return back a failure. Causing osde2e to end with no cluster clean up performed.
When the user supplies the option `destroyAfterTest` as true, no matter what the results are of the tests, the cluster should be destroyed. The default value for `destroyAfterTest` is true. So clusters should be deleted for every run.
This commit fixes this issue by moving the destroy cluster block above the checking if any test failures occurred. Allowing osde2e to properly destroy the cluster and then analyze the test failures/return.
For [SDCICD-919](https://issues.redhat.com/browse/SDCICD-919)
_Current behavior (with test failures)_
```
Ran 7 of 232 Specs in 33.034 seconds
FAIL! …
```
> Destroy cluster after tests with failures when flag is enabled

- pkg/e2e/operators/operators.go
[SDCICD-903](https://issues.redhat.com//browse/SDCICD-903) introduced retry logic when querying grpc service to handle intermittent 503 HTTP errors returned. The latest runs still seem to be getting these HTTP errors. This commit bumps the retry/delay up to 6 retries with 5 second delay between.
If errors still occur after this PR, then we will need to dig deeper into the logic to see if there is any other way we can look to resolve this. I have been testing locally and unable to reproduce this issue.
https://testgrid.k8s.io/redhat-osd#osde2e-main-aws-prod-e2e-default&width=90
> Extend grpc query for operator previous csv retries

- pkg/common/providers/rosaprovider/cluster.go
This causes an error if trying to use govcloud because it is forcing us-east-1 instead of what is specified by the user
> providers/rosa: use region set in config file

- pkg/common/helper/helper.go
this causes a 1 minute delay any time it is ran even though we know it will fail, skip it for now
> common/helper: wrap entire rbac wait in hypershift conditional

- pkg/common/cluster/clusterutil.go
this is actually an `os.IsTimeout` instead of from apierrors
```
2023/02/21 04:45:51 e2e.go:134: *******************
2023/02/21 04:45:51 e2e.go:135: Cluster failed health check: HyperShift healthcheck: Get "https://api.autumn.xyza.s3.devshift.org:443/api/v1/nodes": dial tcp 54.222.222.116:443: i/o timeout
2023/02/21 04:45:51 e2e.go:136: *******************
```
> common/cluster: fix hosted-cp healthcheck timeout check

- docs/Config.md
- pkg/common/aws/session.go
- pkg/common/config/aws_config.go
- pkg/common/providers/rosaprovider/util.go
This commit adds support to osde2e users allowing them to use aws profiles to authenticate with aws. This gives an additional option over just using access keys for authentication.
When the profile is set, access keys can be ignored, when profile is not set access keys will need to be set to authenticate.
For [SDCICD-932](https://issues.redhat.com/browse/SDCICD-932)
> SDCICD-932: Add support to use aws profile for rosa and aws authentication

- docs/Self-Service-MOPs/Adding-Testgrid-Pipelines-Through-Ci-Operator.md
This PR introduces the doc to add OSDe2e pipelines into testgrid for the redhat-openshift-osd dashboard.
> SDCICD-894 - MOP for adding pipelines into Testgrid

- pkg/common/config/config.go
- pkg/common/providers/ocmprovider/cluster.go
- pkg/common/providers/ocmprovider/kubeconfig.go
This commit provides a workaround to osde2e to allow testing to carry on with the open bug where the cluster certificate does not match the one the API provides. By default this is not enabled, meaning osde2e will fail when trying to authenticate with the server. Users will need to enable this workaround manually by either:
* Set environment variable `HYPERSHIFT_IGNORE_INVALID_CERT`
```shell
export HYPERSHIFT_IGNORE_INVALID_CERT="true"
```
* Set `HypershiftIgnoreInvalidCert` in a custom config to authenticate successfully against the server.
```yaml
HypershiftIgnoreInvalidCert: True
```
For [SDCICD-940](https://issues.redhat.com/browse/SDCICD-940)
Requires https://github.com/openshift/release/pull/36991
> SDCICD-940: Allow osde2e to workaround hypershift admin kubeconfig self cert bug

- cmd/osde2e/test/cmd.go
- docs/Config.md
- pkg/common/config/config.go
- pkg/e2e/e2e.go
When test execution is complete, a cluster will be destroyed by default. If a user wants to leave a cluster up, they can use the updated flag `--skip-destroy-cluster`. When passed, the cluster will be left up. Users can also set this within a custom config or by setting the environment variable `SKIP_DESTROY_CLUSTER`.
This commit addresses the inconsistency between the default value set within config.go and the value set by the CLI flag.
For [SDCICD-944](https://issues.redhat.com//browse/SDCICD-944)
_Using the CLI option to the leave cluster up_
```
osde2e test --custom-config my-custom-config.yml --skip-destroy-cluster
```
_Using the custom config to the leave cluster up_
```
cat my-custom-config.yml
cluster:
skipDestroyCluster: true
```
```
osde2e test --custom-config …
```
> SDCICD-944: Rename destroy-cluster flag to skip-destroy-cluster

- pkg/common/providers/rosaprovider/cluster.go
The current implementation will fail trying to create a rosa cluster when getting the latest version available over the default one set. Whether using candidate channel or nightly channel, it will append the channel group to the end of the version string. This behavior works for traditional OSD cluster installs.
This commit will address the issue with a simple solution to start (which can later follow with a more concrete implementation based on the provider for filtering the versions). This change does the following:
1. Queries only for the versions based on the channel group defined
2. Attempts to remove channel group that may exist within the version string
* For [SDCICD-939](https://issues.redhat.com//browse/SDCICD-939)
* Required for https://github.com/openshift/release/pull/36987
* …
> SDCICD-939: Fix for rosa to use latest ocp version when not using stable channel

- assets/terraform/setup-vpc.tf
- pkg/common/providers/mock/mock.go
- pkg/common/providers/ocmprovider/cluster.go
- pkg/common/providers/rosaprovider/cluster.go
- pkg/common/providers/rosaprovider/vpc.go
- pkg/common/providers/rosaprovider/wrapped_calls.go
- pkg/common/spi/provider.go
- pkg/common/terraform/terraform.go
This PR adds support to OSDE2E to auto create the VPC for ROSA hosted control plane clusters over requiring the user to BYOVPC.
When a user calls OSDE2E with the options for a HyperShift cluster and provides the VPC subnet ids, it will not create any VPC and use the one provided.
```
provider: rosa
Hypershift: True
config:
aws:
vpcSubnetIDs: "subnet-1,subnet-2"
region: us-east-1
rosa:
env: stage
STS: true
cluster:
name: hcp
version: 4.12.4
```
When a user calls OSDE2E with the options for a HyperShift cluster and does not provided any VPC subnet ids, it will automatically create the VPC and destroy the VPC when finished.
```
provider: rosa
Hypershift: True
config:
aws:
region: us-east-1
rosa:
env: stage
STS: true
cluster:
name: hcp
version: 4.12.4
```
When OSDE2E goes to create the VPC it …
> SDCICD-933: Auto create ROSA hosted control plane VPC when undefined

- .gitignore
As a contributor to osde2e and using custom configs. They are easily subject to being tracked/checked into git. To avoid this, this commit updates the gitignore file to ignore custom configs that have a prefix of `custom-*`.
> Ignore custom configs used while working on development tasks

- pkg/common/config/config.go
- pkg/e2e/e2e.go
the jobs in prow currently time out after 1 hour (the ginkgo default)
but they are not showing as skipped correctly in testgrid. Bumping the
suite timeout to 3hrs should allow the tests to finish or at least time
out at a test level.
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-ocp-osd-aws-nightly-4.13/1637686778385141760
```
Ran 28 of 232 Specs in 3630.017 seconds
FAIL! - Suite Timeout Elapsed -- 20 Passed | 8 Failed | 0 Pending | 204 Skipped 
```
> set ginkgo suite timeout

- pkg/common/config/config.go
the tests take longer than 3 hours to timeout completely
```
Ran 121 of 222 Specs in 13624.890 seconds
FAIL! -- 76 Passed | 45 Failed | 0 Pending | 101 Skipped
```
> bump suite timeout to 6 hours

- pkg/e2e/operators/certman.go
- pkg/e2e/operators/managedupgrade.go
- pkg/e2e/operators/managedvelero.go
- pkg/e2e/operators/mustgather.go
- pkg/e2e/operators/osdmetricsexporter.go
- pkg/e2e/operators/rbac.go
- pkg/e2e/operators/routemonitor.go
- pkg/e2e/operators/splunkforwarder.go
- operators/rbac: ordered install tests
- operators/mustgather: ordered install tests
- operators/certman: check poll err
- operators/routemonitor: ordered install tests
- operators/managedvelero: ordered install tests
- operators/managedupgrade: ordered install tests
- operators/splunkforwarder: ordered install tests
> ordered operator installs

- pkg/common/versions/installselectors/specific_image.go
- pkg/common/versions/version_selector.go
Current implementation throws a panic error causing osde2e to exit when trying to parse version into a semantic version object.
This commit will:
* Switch from using `MustParse` to `NewVersion` to allow osde2e to handle the error
* Delete printing out all available versions when unable to select a version from the versions list provided. Aims to keep the output clean when it tries for 30 minutes.
Sample custom config used to test PR:
```yaml
cluster:
channel: nightly
releaseImageLatest: "registry.build01.ci.openshift.org/ci-op-9irmvgyv/release@sha256:e1574eee260c2fa2f72e00a82aad0200a99d524dd9fb73afd732d34fa7489227"
skipDestroyCluster: true
hibernateAfterUse: false
```
_Current Implementation_
```
2023/03/20 14:06:18 versions.go:34: Querying cluster versions endpoint.
2023/03/20 14:06:18 …
```
> Avoid panic error when specific image selector fails to parse version

- pkg/e2e/operators/operators.go
this polls the deployment twice, back to back, if it has to wait for the full duration which results in 10 minutes per operator just to check the deployment
> e2e/operators: collapse deployment install test

- pkg/e2e/operators/managedupgrade.go
these tests are stable and can be moved to the e2e suite with the other operator tests
> operators/managedupgrade: move out of informing suite

- pkg/common/util/versionutil.go
- pkg/common/util/versionutil_test.go
- pkg/e2e/verify/prom_exporters.go
- common/util: drop EOL OCP version constraints
> drop eol version contraints

- pkg/common/config/config.go
- pkg/common/versions/installselectors/latest_xy.go
This change adds a new install selector to select a version to install for rosa/osd based on a major.minor version supplied. It will get the latest available one based on the channel group provided as well.
Needed for https://github.com/openshift/release/pull/36987 now that 4.11 is the default version again. This change will allow the HyperShift jobs to install the latest 4.12 version available since it only supports >= 4.12.
1. Get latest 4.12 version available for candidate channel
```yaml
cluster:
installLatestXY: "4.12"
channel: candidate
```
```
2023/03/23 15:58:58 cluster.go:486: created OCM client
2023/03/23 15:58:59 version.go:103: Using the latest X.Y version available '4.12.9-candidate'
2023/03/23 15:58:59 version.go:130: No upgrade selector found. Not selecting an upgrade …
```
> New version selector to get latest X.Y version available

- pkg/e2e/e2e.go
not sure why the expectation would be a graceful exit, but it causes
false negatives like this in job runs:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-ocp-osd-aws-nightly-4.12/1636143394818363392
in which the job effectively failed (did not run), but reports success.
There is some weird history on this change. It was originally introduced deliberately(tor eturn success) here:
https://github.com/openshift/osde2e/commit/44503b8cc4b890eb9f756c83380aee0796d45a56
But the "reason" points to this jira ticket:
https://issues.redhat.com/browse/SDCICD-639
which contains no further context beyond pointing to this slack thread:
https://coreos.slack.com/archives/CCX9DB894/p1618515431158100
which appears to be deleted.
Hopefully another maintainer on this repo can …
> Exit with failure if version cannot be chosen

- configs/test-harness.yaml
- pkg/common/label/label.go
- pkg/e2e/harness_runner/harness_runner.go
Addresses the error around harnessess and adds a new label for TestHarness. Which can be used to tell osde2e to run the test harness suite.
> Fix spelling error with test harness and include a new label

- pkg/common/providers/ocmprovider/cluster.go
- pkg/common/spi/cluster.go
- pkg/e2e/e2e.go
- pkg/e2e/operators/configurealertmanager/configurealertmanager.go
Configure alertmanager operator secrets (_dms-secret_ and _pd-secret_) are not applied to clusters that are deployed using nightly openshift builds. This is design to avoid paging SRE. Example can be seen [here](https://github.com/openshift/pagerduty-operator/blob/4e6ba964ab8dbd49b2fc1185f6c2af2673bec77a/hack/olm-registry/olm-artifacts-template.yaml#L95-L98)
Channel group is fetched from OCM cluster resource as it contains the channel group used when provisioned. Allowing the test case to be skipped properly if a cluster ID is provided and no channel group is defined.
For [SDCICD-956](https://issues.redhat.com/browse/SDCICD-956)
> SDCICD-956: Skip configure alertmanager operator secret exists tests for nightly build clusters

- pkg/common/metadata/metadata.go
[SDCICD-717](https://issues.redhat.com//browse/SDCICD-717)
Converting addon harness to generic test harness also changed the default addon metadata filename to test-harness metadata. Addon-metadata.json file is already being used by addons to generate metadata, and main metadata file is generated based on their test phases.
To fix this, I have reintroduced the filename and included it in the condition to update the main metadata file. This creates the metadata file with the data that addons are expecting. 
Internal thread https://redhat-internal.slack.com/archives/CMK13BP4J/p1680590567087939?thread_ts=1680534911.725599&cid=CMK13BP4J
> Provision for addon-metadata files created in addon harnesses

- pkg/common/aws/session.go
- pkg/common/providers/ocmprovider/cluster.go
- pkg/common/providers/rosaprovider/cluster.go
- pkg/common/providers/rosaprovider/rosa.go
This PR adds onto the previous commit for supporting aws profiles to support using profiles across additional functions communicating with aws. Functions that were previously getting the keys from config will now get the credentials from the aws session (which loads from config object). This keeps accessing aws credentials in one location over multiple.
For [SDCICD-959](https://issues.redhat.com/browse/SDCICD-959)
> SDCICD-959: Extend the use of AWS profiles where access key/secret access key are used

- pkg/e2e/verify/pods.go
The verify pods test is focused on verifying no pods are in a failed state that are required to mark the cluster is operational "healthy".
If a prior test case ran but had a pod end up in a failed state/the pod was never properly cleaned up. It causes the verify/pod test to fail. The prior test should handle its clean up to not pollute following tests.
This commit ignores any pods that are within an osde2e prefixed namespace.
Job that presented this issue can be seen [here](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-ocp-osd-aws-nightly-4.13/1644192397413847040)
> verify/pods: ignore pods that are in osde2e prefixed namespaces

- pkg/e2e/workloads/workloads.go
the redmine workload frequently times out within the alloated 60
seconds, double the timeout and clean up the error description for
waiting until the deployment is available
> e2e/workloads: bump timeout and improve err desc

- pkg/common/config/config.go
- pkg/e2e/e2e.go
Ginkgo does not support calling RunSpec twice which is what osde2e is attempting to do for upgrade use cases. Ginkgo does allow to run the same spec multiple times in a row when invoked from the cli. To remove the failures in CI jobs/local osde2e runs. This commit adds a new option to toggle on/off running post upgrade tests. It sets the default to never run them until a permanent solution is in place.
```
[1681759212] OSD e2e suite - 9/222 specs SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS•••••••••SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SUCCESS! 11.563394383s 2023/04/17 15:21:10 e2e.go:427: Route Monitors created.
2023/04/17 15:21:10 e2e.go:439: Running e2e …
```
> SDCICD-971: add an option to toggle on/off running post upgrade tests

- go.mod
- go.sum
- pkg/common/providers/ocmprovider/cluster.go
As of 0.1.332 and onward, it pulls in an updated [api model](https://github.com/openshift-online/ocm-sdk-go/pull/755/files#diff-ed8217452b8a809c249edac917b68daea27f1fb5be59319b1a989dbab72caf66) which removed the cluster field for the AddOnInstallation collection. This is returned back when posting to ocm to install an add on. It was used to get the cluster body to update osde2e cluster cache collection.
Since this field no longer exists, this commit performs an api request to ocm after the add on is installed to get the updated cluster body.
Fixes https://github.com/openshift/osde2e/pull/1761
Tested osde2e locally using the test harness example
```yml
addons:
ids: "reference-addon"
config:
aws:
region: us-east-2
ocm:
env: stage
ccs: true
cluster:
id: 2363ni12cukpprpedi3s1sgmcqumgq32 …
```
> Bump ocm-sdk-go to version 0.1.333

- assets/workloads/e2e/pdb/pdb-1.yaml
- assets/workloads/e2e/pdb/pdb-2.yaml
- pkg/common/helper/workloads.go
Part of the testing of OSD upgrades, osde2e can apply load onto the cluster before starting. The API currently used is deprecated in v1.21+ and will be removed in v1.25+.
```
W0412 13:47:39.097499      13 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget403W0412 13:47:39.144702      13 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget 
```
This change updates the api version to use policy/v1.
```
[rywillia@t14s ~]$ oc get pods -n osde2e-kzhnu
NAME                               READY   STATUS    RESTARTS   AGE
node-drain-test-6ccfcc788f-87sw9   1/1     Running   0          23s
pdb-case-1-74cbb9b4d8-wff25        1/1     Running …
```
> Use policy v1 api over v1beta1 for pod disruption budget

- assets/tests/tests-runner.template
- pkg/common/helper/testRunner.go
expose the OCM_CLUSTER_ID to the job running the tests which would allow
a test to talk with OCM regarding the specific cluster
https://go.dev/play/p/biZUnU0lni8
> common/helper/testrunner: expose OCM_CLUSTER_ID env

- docs/Config.md
- pkg/common/aws/session.go
- pkg/common/config/aws_config.go
- pkg/common/providers/ocmprovider/cluster.go
- pkg/common/providers/rosaprovider/oidcconfig.go
https://issues.redhat.com/browse/SDCICD-977
Adds AWS account ID as a member of CcsAwsSession. checks for   AWS_ACCOUNT_ID env var . Renames previously "AWS_ACCOUNT" to "AWS_ACCOUNT_ID". Replaces direct calls to viper config from elsewhere in code. 
Secret key name and config name are still aws-account and. config.aws.account respectively. No change there.
> SDCICD-977 access AWS account ID through CCS session struct

- scripts/parameterized-job.sh
added job script for parameterized job to be run in app-interface ci-int job
https://issues.redhat.com/browse/SDCICD-972
The execution of this script will be configured in a app-interface MR which creates the jenkins job which will run this.
The following env vars are to be passed in from jenkins job secrets
OCM_TOKEN
AWS_SECRET_ACCESS_KEY
AWS_ACCESS_KEY_ID
Following will be provided by job parameters
CLOUD_PROVIDER_REGION
INSTANCE_TYPE
Dependent app-interface PR https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/65444#note_6391654
> added job script for parameterized job  

- pkg/common/providers/mock/mock.go
- pkg/common/providers/ocmprovider/ocm.go
- pkg/common/providers/ocmprovider/upgrades.go
- pkg/common/providers/rosaprovider/rosa.go
- pkg/common/providers/rosaprovider/wrapped_calls.go
- pkg/common/spi/provider.go
- pkg/common/upgrade/managed.go
- pkg/common/versions/common/utils.go
This change adds support to osde2e to be able to provide cluster acknowledgements prior to performing a cluster upgrade. Depending on the cluster upgrade path being performed. Cluster acknowledgement is performed for both OCM upgrades and local managed upgrade operator upgrades.
Cluster gate agreement is not performed if the upgrade is a z stream upgrade, only y stream. In the event a version gate does not exist for the version to upgrade to, it will still carry on and attempt to perform the upgrade. To present any errors that are helpful to the user to debug.
_Errors seen by current OSD upgrade job_
```
2023/04/12 13:47:45 pods.go:90: 0 pods are currently not running or complete:4112023/04/12 13:47:46 e2e.go:277: OSDE2E failed: error performing upgrade: failed triggering upgrade: can't …
```
> Add cluster gate agreement when performing cluster upgrades

- pkg/common/config/config.go
- pkg/e2e/e2e.go
This change allows cluster upgrade workflows to skip running pre upgrade tests and just run post upgrade tests. OSDE2E currently has a limitation where it cannot run the test suite more than once (w/ginkgo).
Since its critical to verify the operator tests post upgrade, this change switches the behavior to always run post upgrade tests and skip running pre upgrade tests when cluster upgrades are enabled.
With this change, upgrade workflows will perform the following (by default):
1. Deploy cluster
2. Verify cluster health checks
3. Skip pre upgrade "install" tests
4. Perform cluster upgrade
5. Perform cluster upgrade post health checks
6. Run post upgrade tests
7. Destroy cluster
For [SDCICD-979](https://issues.redhat.com/browse/SDCICD-979)
> Add the ability to toggle on/off pre upgrade tests

- pkg/common/config/config.go
- pkg/common/providers/ocmprovider/versions.go
- pkg/common/versions/installselectors/latest_y_from_delta.go
- pkg/common/versions/installselectors/latest_z_from_delta.go
- pkg/common/versions/installselectors/utils.go
This change brings two new install version selectors. They are added to support the following upgrade paths:
* Latest Y-1 to latest Y
* Latest Z-1 to latest Z
The selectors added are:
* Install latest Y from delta
* Install latest Z from delta
They allow the user to define a positive/negative delta to locate the version to install. These can be used outside of upgrade workflows as well.
In addition to these version selectors, when querying ocm for openshift versions, the sorting was switched to be in descending order.
For [SDCICD-981](https://issues.redhat.com/browse/SDCICD-981)
1. Install latest Y-1
```
cat custom-config.yml
cluster:
channel: stable
installLatestYFromDelta: -1
2023/04/21 11:15:14 version.go:103: Using the latest Y '4.11.36' from delta -1 '4.10.56'
2023/04/21 11:15:14 …
```
> Add new install version selectors for supporting upgrade workflows

- scripts/parameterized-job.sh
fixing report dir path - param under job config should be /osde2e-results  as job has it under /osde2e-results 
job log: https://ci.int.devshift.net/blue/organizations/jenkins/osde2e-parameterized-job/detail/osde2e-parameterized-job/9/pipeline/
jira: [sdcicd-972](https://issues.redhat.com//browse/sdcicd-972)
related job PR https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/65685/diffs
> fixed report dir name

- pkg/e2e/e2e.go
Recent commit added support to toggle on/off running install tests prior to performing osd upgrade. Allowing for upgrade scenarios to just run post upgrade tests. With this change, it introduced a bug where after upgrade finishes and tests run without any failures. Osde2e marks the run as failed. Problem is related to a `testsPassed` variable not being properly initialized.
This commit initializes the `testsPassed` variable with a default value of true. Resulting in this bug no longer being reproducible.
Example job with the bug can be seen [here](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/38614/rehearse-38614-periodic-ci-openshift-osde2e-main-osd-aws-upgrade-latest-y-minus-1-to-latest-y/1649529775389151232). Install tests are skipped, resulting in …
> Fix osd upgrade scenarios from being marked failed when all tests passed

- docs/CI-Jobs.md
This PR updates the CI jobs document to reflect the latest updates to the OSD upgrade jobs made by https://github.com/openshift/release/pull/38614. Links to test grid dashboards are currently not working due to dashboard does not contain the jobs yet.
https://github.com/openshift/release/pull/38681
For [SDCICD-978](https://issues.redhat.com//browse/SDCICD-978)
> Update jobs documentation to reflect latest OSD upgrade CI jobs

- pkg/common/providers/rosaprovider/accountroles.go
- pkg/common/providers/rosaprovider/cluster.go
This PR introduces support to auto create rosa account roles when creating rosa classic/rosa hcp clusters.
Prior to any account role creation, it will check the account first to see if any roles exist. Roles will only be created if they do not exist.
Roles to be created will be created using the default prefix "ManagedOpenShift-<version>". Which allows them to be reusable across clusters. With this approach, it keeps the roles clean/tidy in the account, resulting in less amount of roles (e.g. unique role per cluster created). This also eliminates the need to remove account roles at the end of an osde2e run. We can leave "ManagedOpenShift-<version>" prefixed roles in the account as they are global/used by multiple clusters.
For [SDCICD-923](https://issues.redhat.com//browse/SDCICD-923)
> SDCICD-923: Add support to automatically create rosa account roles

- Dockerfile.osde2e
- go.mod
This PR bumps the go version from 1.18 to 1.19. 1.18 is [no longer supported](https://endoflife.date/go) now that 1.20 is available. As go supports 2 versions at a time.
In addition to being unsupported, 1.18 also does not support atomic pointers (which was made available in 1.19). For PR #1800 to pass PR checks, it will need to be bumped to use latest k8s packages.
```
[root@9c07ab4a60de osde2e]# go version
go version go1.18.1 linux/amd64
[root@9c07ab4a60de osde2e]# make build
mkdir -p "/go/src/github.com/openshift/origin/osde2e/out"
go build -o "/go/src/github.com/openshift/origin/osde2e/out" "/go/src/github.com/openshift/origin/osde2e/cmd/..."
/go/pkg/mod/k8s.io/kube-openapi@v0.0.0-20230308215209-15aac26d736a/pkg/cached/cache.go:242:16: undefined: atomic.Pointer
make: *** [build] Error …
```
> Bump go from 1.18 to 1.19

- pkg/common/cluster/clusterutil.go
[Slack Ref ](https://redhat-internal.slack.com/archives/CMK13BP4J/p1683062458966729?thread_ts=1683060230.475769&cid=CMK13BP4J)
[SDCICD-1003](https://issues.redhat.com/browse/SDCICD-1003)
This PR updates the viper variable for the cluster name when we create a fresh cluster using Rosa
> Set cluster name var when creating through ROSA

- go.mod
- go.sum
Reverts back from V1.2.20 which introduced an os.Exit(0) on cluster creation, that is causing OSDe2e to end abruptly. 
Refer to this [thread](https://redhat-internal.slack.com/archives/CMK13BP4J/p1683575571686559) for reference
> Hotfix -Revert Rosa Back to v1.2.17

- pkg/e2e/operators/ocmagent/ocmagent.go
this was changed in https://github.com/openshift/ocm-agent-operator/commit/25ce50dfe89a1afd6879111a0b15f8ab76100abe
> e2e/operators/ocmagent: update configmap name

- pkg/common/providers/rosaprovider/accountroles.go
- pkg/common/providers/rosaprovider/cluster.go
This PR supplies the channel group to rosa when creating account roles (its a hidden flag). Current jobs attempting to deploy sts clusters with version 4.13 have been failing to create roles. Since those jobs are using candidate channel group and stable channel group does not have 4.13 builds available. We need to supply the channel group so rosa/ocm can accordingly find the 4.13 version and proceed to create the roles.
_Error_
Example [job](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-osde2e-main-rosa-stage-e2e-byo-vpc-proxy-install/1656011284635717632) failing.
```
2023/05/09 19:04:15 cluster.go:109: ROSA cluster version: 4.13.0-rc.7
2023/05/09 19:04:15 accountroles.go:26: Checking if account roles exist with prefix "ManagedOpenShift-4.13"
2023/05/09 …
```
> Include channel group when creating rosa account roles

- docs/CI-Jobs.md
This PR updates the CI Jobs document to include the ROSA Classic STS jobs that were recently added by https://github.com/openshift/release/pull/38941.
https://prow.ci.openshift.org/?job=*rosa-classic-sts*
For [SDCICD-557](https://issues.redhat.com//browse/SDCICD-557)
> Update CI jobs doc to include ROSA Classic STS TRT nightly jobs

- docs/CI-Jobs.md
https://github.com/openshift/release/pull/39702 enabled slack notifications for all remaining periodic jobs. This PR updates our CI jobs document to reflect the slack channel notifications are sent to for our jobs.
> Update ci-jobs doc to reflect the slack channel for notifications

- pkg/common/providers/rosaprovider/cluster.go
Increases default compute node count for multi az clusters from current default 2 to required count 3
> Fixes minimum compute node issue for multi AZ clusters

- go.mod
- go.sum
- test/mcscupgrade/mcscupgrade_test.go
1. Bump osde2e-common to the latest commit sha ([PR](https://github.com/openshift/osde2e-common/pull/13))
2. Update MC/SC upgrade test suite to alter the data type for cluster properties when passed to ROSA provider `createCluster` method.
> Bump osde2e-common to latest commit sha

- pkg/common/providers/rosaprovider/cluster.go
- pkg/common/providers/rosaprovider/oidcconfig.go
This PR resolves the bug where after a rosa clusters operator roles and oidc provider are deleted, it hangs trying to delete the oidc config if one was auto created when the cluster was created. The issue seemed to be the rosa oidc config delete command was thinking it was in an interactive mode, waiting for user prompt. Issue looks to be related to a global variable being set from prior rosa command calls, resulting it being set to true, entering interactive mode.
The fix is to add an additional option to explicitly set interactive mode to false.
In addition to this fix, updated create oidc config to accept the installer role arn as a parameter over defining a static one.
```
2023/06/28 12:21:21 cluster.go:366: Waiting for cluster 24kt65n1t9b7ehmqkcd0qeq4ke4gj2dq to be deleted
2023/06/28 …
```
> Fix the bug causing rosa cluster oidc config deletion to fail

- docs/CI-Jobs.md
This PR updates the CI jobs document to reflect the new changes to the OpenShift TRT nightly jobs.
Includes:
- Split jobs into 2 new sections based on platform (OSD & ROSA)
- Add 4.12 and 4.13 jobs for ROSA HCP
- Add 4.14 ROSA Classic STS job
Depends on:
- https://github.com/openshift/release/pull/40603
- https://github.com/openshift/release/pull/40822
- [SDCICD-1050](https://issues.redhat.com//browse/SDCICD-1050)
- [SDCICD-1054](https://issues.redhat.com//browse/SDCICD-1054)
> Update CI jobs doc to reflect new TRT nightly jobs

- docs/CI-Jobs.md
The ROSA HCP periodic job has been replaced by 2 TRT nightly build jobs. This PR updates the CI jobs docs to reflect the latest CI jobs the team has running.
Requires - https://github.com/openshift/release/pull/40852
> SDCICD-1019: remove rosa hcp periodic job from ci doc

- pkg/common/providers/rosaprovider/cluster.go
This change performs an ocm login and a rosa login prior to starting the process to delete the cluster.
This is required when a user of osde2e uses the cleanup command to delete the cluster (if they did not run osde2e test within the same container or machine). What happens is rosa is not logged in, resulting in operator role and oidc provider deletion commands to fail.
When osde2e test is called, prior to creating a cluster. Rosa login happens when checking for versions. Storing the login authentication details on the filesystem, resulting in following rosa calls to work.
```
osde2e cleanup ...
2023/07/13 20:14:12 cluster.go:366: Waiting for cluster 24uvja2q4uasmvme7eor4m3q61gshh07 to be deleted
2023/07/13 20:14:12 util.go:31: AWS_PROFILE is not set
2023/07/13 20:14:12 cluster.go:384: …
```
> ROSA provider: perform rosa login prior to deleting cluster/resources

- pkg/common/helper/runner.go
- pkg/e2e/harness_runner/harness_runner.go
This change organizes test harnesses as describeTable specs, so that when more than one harness is provided, each runs as a separate spec. This can allow us to run them in parallel if needed. 
This also separates each spec into a different namespace and keeps logs from each harness separate from each other
https://issues.redhat.com/browse/SDCICD-955
> use describeTable for better running multi harness jobs SDCICD-955

- configs/sts.yaml
This PR adds a new pre-canned config for enabling STS for ROSA cluster creation/deletion. Instead of calling osde2e setting the environment variable `ROSA_STS=true` to enable STS. Users can now just provided this as a config:
```
--configs "rosa,sts,stage"
```
For [SDCICD-1058](https://issues.redhat.com//browse/SDCICD-1058)
> Adds a new config for enabling rosa sts to deploy clusters

- docs/Self-Service-MOPs/TRT-OCP-Release-Gating.md
This PR updates the existing document explaining how to add/remove jobs that are triggered for every new OpenShift nightly build.
- https://github.com/openshift/release/pull/41245
- https://github.com/openshift/continuous-release-jobs/pull/1330
- https://github.com/openshift/ci-tools/pull/3543
- [SDCICD-1058](https://issues.redhat.com//browse/SDCICD-1058)
> Update self service doc for openshift release gate testing signal

- docs/CI-Jobs.md
This PR updates the existing CI jobs document to reflect the latest changes to the prow job renaming.
- https://github.com/openshift/release/pull/41245
- https://github.com/openshift/continuous-release-jobs/pull/1330
- https://github.com/openshift/ci-tools/pull/3543
- [SDCICD-1058](https://issues.redhat.com//browse/SDCICD-1058)
> Update ci jobs doc to reflect job renaming

- ci/acceptance-tests-template.yaml
A template that creates a job which executes the test harness for a
given image or images. This can be used from app-interface to gate an
operator release based on the results.
continued work on [SDCICD-1009](https://issues.redhat.com//browse/SDCICD-1009)
> osde2e operator harness job

- configs/complete-e2e.yaml
- docs/Config.md
- pkg/common/label/label.go
- pkg/e2e/harness_runner/harness_runner.go
- pkg/e2e/operators/customdomains.go
- pkg/e2e/operators/ocmagent/ocmagent.go
- pkg/e2e/operators/osdmetricsexporter.go
- pkg/e2e/operators/rbac.go
- pkg/e2e/operators/splunkforwarder.go
* changed harness timeout to use shorter suite timeout per harness
* Moved result retrieval to test spec from afterEach to avoid execution for fail pods
* Adding harness list in complete-e2e config file instead of env var for batch job
* Skip migrated operator tests using new label - only for complete-e2e test config. This is a temporary stop gap till we can remove operator label and tests from osde2e
> harness batch job related updates

- go.mod
- go.sum
- pkg/e2e/operators/managedvelero.go
Two changes:
- Bumps the velero dependency to match the version we are using in the MVO
- Removes some tests for CRs that have been removed or are otherwise unneeded. Seeing failures as the test expects these to be present and editable by folks, but some of these are internal CRs that have mandatory fields and don't need to be tested.
Failed test ref: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-osde2e-main-nightly-4.12-osd-aws/1683846376716242944
> Update MVO e2e tests

- pkg/e2e/workloads/workloads.go
The workloads test has been flaky on and off and more so recently from prow ci runs. To better improve the ci signal, this commit removes this suite from being included for hypershift and e2e suites.
These tests are testing the standard functionality which OpenShift provides. From a Managed OpenShift perspective, we should ensure this functionality already is covered by OpenShift QE/Dev and only focus on actually testing Managed OpenShift aspects. When the OSD operators get deployed, they are creating deployments, pods, etc, which would fail if there was an actual problem. Making this test redundant/obsolete.
For [SDCICD-1038](https://issues.redhat.com//browse/SDCICD-1038)
> Remove workload tests from hypershift/e2e test suites

- pkg/e2e/harness_runner/harness_runner.go
When a harness image provides a tag, the harness runner does not strip off the ':<tag>'. Which results in OpenShift failing to start the job. This commit updates generating the job name to take into account harness images that do or don't supply the image tag.
```
The Job "ci-tools-nvidia-gpu-operator:osde2e-9gxb5" is invalid: 
* metadata.name: Invalid value: "ci-tools-nvidia-gpu-operator:osde2e-9gxb5": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
* spec.template.labels: Invalid value: "ci-tools-nvidia-gpu-operator:osde2e-9gxb5": a valid label must be an empty string or …
```
> Harness Runner: Handle Image Tags When Generating Job Name

- configs/complete-e2e.yaml
Fixes following error in multi harness job config
```
2023/07/25 23:54:39 cluster.go:1306: Successfully added property[Status] - healthy 
2023/07/25 23:54:39 e2e.go:148: Cluster is healthy and ready for testing
Ginkgo detected configuration issues:
Syntax Error Parsing Label Filter
(E2E || Operators || TestHarness || ServiceDefinition || AppBuilds) &&
!(Informing || MigratedHarness)
Found two adjacent labels.  You need an operator between them.
```
> fixes ` Found two adjacent labels.` error

- pkg/common/helper/helper.go
- pkg/e2e/e2e.go
Before this PR change, if a user was to run osde2e test harness, it creates a namespace for the secrets that the tests can access. The namespace continues to live on the cluster after osde2e finishes. New runs would fail before running test harness due to the namespace already exists.
This change deletes the secrets namespace as part of the clean up operations and also attempts to delete the secrets namespace prior to creating it.
> Test Harness: support multiple reruns of osde2e against the same cluster

- pkg/common/config/config.go
- pkg/e2e/harness_runner/harness_runner.go
In a multi harness suite, individual harnesses must maintain short timeout limits, in order to allow other harnesses and other test suites to run within POLLING_TIMEOUT
Introducing HARNESS_TIMEOUT to use in such multi harness jobs. Current single harness jobs only specify POLLING_TIMEOUT. This PR allows that var to be used when HARNESS_TIMEOUT is not defined.
> use HARNESS_TIMEOUT var to specify individual harness timeout, POLLING_TIMEOUT if unspecified

- pkg/common/cluster/clusterutil.go
- pkg/common/helper/helper.go
- pkg/common/upgrade/upgrade.go
- pkg/e2e/e2e.go
- pkg/e2e/routemonitors/routemonitors.go
This PR aims to address osde2e not properly destroying a cluster when it has the settings enabled to do so. Osde2e ends up never deleting the cluster due to it fails to construct the ginkgo helper object to perform clean up operations.
Examples:
* https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/osde2e-stage-aws-nvidia-gpu-addon/1686346108575420416
* https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_osde2e/1938/pull-ci-openshift-osde2e-main-rosa-pr-check/1686395505984147456
Before this change, an end to end run may exhibit the behavior where the cluster is launched and fails at a certain point where its unable to get the kubeconfig for it. Which results in failing to construct the cleanup helper object and cluster deletion is never performed. Leaving …
> Attempt cluster deletion when failing to create cleanup helper object

- pkg/common/providers/ocmprovider/cluster.go
- pkg/common/providers/rosaprovider/cluster.go
- pkg/common/providers/rosaprovider/oidcconfig.go
Previously `DeleteCluster` method would query ocm for all odic configs and find the one pertaining to the cluster based on matching the cluster name is within the secretARN. In the event cluster name is not provided to osde2e (e.g. running `osde2e cleanup` command), this value is empty, resulting in unexpected behavior. Where it will attempt to delete another oidc config id.
This commit addresses this issue by directly getting the oidc config id from the cluster's ocm body response from the API. This will ensure us that we will always have the correct oidc config id.
Addresses failures with latest TRT ROSA HCP 4.12 and 4.13 runs ([example](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-osde2e-main-nightly-4.13-rosa-hcp/1687055861177913344)).
> Get rosa hcp cluster oidc config id from ocm cluster body

- pkg/common/providers/rosaprovider/cluster.go
- pkg/common/providers/rosaprovider/vpc.go
Previously the generated terraform files for a rosa hcp cluster aws vpc were being written to the report directory for osde2e. When osde2e is being used by a mutli step prow job, a step to run osde2e cleanup command would not be able to properly locate the terraform files due to that report directory does not exist within the container for the step.
This commit addresses this issue, where osde2e can write the terraform files to the shared directory. Making the files available to any step within a mutli step job. That would allow `osde2e cleanup` step to properly clean up an auto generated aws vpc.
> Write rosa vpc terraform generated files to either report/shared dir

- pkg/e2e/harness_runner/harness_runner.go
A new cleanup error is showing in the harness job
This is coming due to viper config contining a project name that harness-runner has already deleted, and helper erroring out here https://github.com/openshift/osde2e/blob/7194974b8cd0f600f98a3aea9eb75af950e0255e/pkg/e2e/e2e.go#L584C3-L584C3
Adding a After() function in harness runner to blank the deleted project name from viper
https://issues.redhat.com/browse/SDCICD-1069
> SDCICD-1069 clear deleted project name from config

- go.mod
- go.sum
- pkg/common/providers/rosaprovider/cluster.go
Changes for https://github.com/openshift/osde2e/pull/1983 to work. 
The getVersions() function changed to require a bool for a value that returns the default version first.
> Rosa 1.24 update

- .github/dependabot.yml
Ref Slack Thread: https://redhat-internal.slack.com/archives/CMK13BP4J/p1686258843460609
Dependabot has gotten too noisy with daily PRs. Failing pipelines also tend to leave leftover resources. 
This PR swaps the interval back to weekly in hopes of quieting down Dependabot.
> Swap dependabot back to weekly

- test/cluster_diff/cluster-diff.sh
job in prow is failing due to not logging in explicitly
> test/cluster_diff: run ocm login on start

- pkg/common/versions/installselectors/default_version.go
- pkg/common/versions/installselectors/delta_release_from_default.go
- pkg/common/versions/installselectors/interface.go
- pkg/common/versions/installselectors/latest_version_selector.go
- pkg/common/versions/installselectors/latest_xy.go
- pkg/common/versions/installselectors/latest_y_from_default_selector.go
- pkg/common/versions/installselectors/latest_y_from_delta.go
- pkg/common/versions/installselectors/latest_z_from_default_selector.go
- pkg/common/versions/installselectors/latest_z_from_delta.go
- pkg/common/versions/installselectors/middle_cluster_image_set.go
- pkg/common/versions/installselectors/next_version_after_prod_default.go
- pkg/common/versions/installselectors/oldest_cluster_image_set.go
- pkg/common/versions/installselectors/specific_image.go
- pkg/common/versions/installselectors/specific_nightlies.go
- pkg/common/versions/versionselector.go
adding additional logging to debug the nightly jobs picking up the wrong
version selector.
In the current nightly jobs, the wrong version selector is being picked
leading to the provided nightly image not being used. The specific image
selector has higher priority but it seems that the specific nightly
selector is somehow being picked instead.
> misc: add version selector logging

- pkg/common/versions/installselectors/specific_image.go
this selector can't be used when running from /pj-rehearse
a few weeks ago, work was done to fix the nightly jobs picking up the correct
selector [here](https://github.com/openshift/release/pull/42029) and Ryan was
able to demonstrate that the value provided when running /pj-rehearse is not
one that can be used by the `rosa` cli:
```
RELEASE_IMAGE_LATEST=registry.build03.ci.openshift.org/ci-op-q7xmji6y/release@sha256:65aaf49a90dabd30139f5dae1fc53f35d96d7cbee784be7f6c74fafed7d549ff
```
- https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/42029/rehearse-42029-periodic-ci-openshift-osde2e-main-nightly-4.13-rosa-hcp/1687550926727942144/artifacts/rosa-hcp/osde2e-test/build-log.txt
We know the format provided when triggered for a nightly job is …
> installselectors: only use specific img when triggered for nightly jobs

- pkg/e2e/e2e.go
controller-runtime is throwing a panic because we don't call SetLogger with a log sink
```
I0824 11:33:01.678216      13 cluster.go:519]  "msg"="Cluster is ready!" "cluster_id"="25qejcte4njk2mpl65ph5e6entn9itip" "cluster_name"="osde2e-86jli" "ocm_environment"="https://api.stage.openshift.com"
[controller-runtime] log.SetLogger(...) was never called, logs will not be displayed:
goroutine 1 [running]:
runtime/debug.Stack()
...
```
```
2023/08/24 12:11:54 cluster.go:1306: Successfully added property[UpgradeVersion] -
2023/08/24 12:11:54 e2e.go:154: Cluster is healthy and ready for testing
Harnesses to run:  []
2023/08/24 12:11:55 helper.go:116: Setup called for osde2e-ma08t
2023/08/24 12:11:55 helper.go:202: Created SA: dedicated-admin-project
2023/08/24 12:11:55 helper.go:212: Created SA: …
```
> e2e: fix logger panic

- pkg/common/providers/mock/mock.go
- pkg/common/providers/ocmprovider/cluster.go
- pkg/common/providers/rosaprovider/wrapped_calls.go
- pkg/common/spi/provider.go
- pkg/e2e/e2e.go
In nightly jobs, with the changes to run as a multi-step job, must-gather is now ran after the first osde2e process has completed. This introduced a bug due to osde2e setting an expiration time of 1 minute in the future which is not enough time for the must-gather to finish.
```
2023/08/25 06:23:49 cluster.go:1241: Successfully set cluster expiry time to Friday, 25 Aug 2023 06:24:48 UTC
```
Increase the time to 10 minutes to be sure that must-gather can run. If anything fails, the cluster will expire, otherwise osde2e will clean up the cluster in the post step.
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-osde2e-main-nightly-4.14-rosa-classic-sts/1694933384087736320
> fix: increase the delay for expiring clusters

- pkg/common/versions/installselectors/specific_image.go
- pkg/common/versions/installselectors/triggered_nightlies.go
- pkg/common/versions/versionselector.go
this selector is currently not polling for an additional period waiting for the image to be synced to CIS. This is just a hack until installing from a specific date is implemented or the ADR for installing from a specific image is accepted and implemented.
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-osde2e-main-nightly-4.14-rosa-classic-sts/1696469596409696256
```
2023/08/29 10:30:10 specific_nightlies.go:23: specific nightly value: "4.14"
2023/08/29 10:30:10 versionselector.go:164: Using version selector "specific nightly"
2023/08/29 10:30:10 versionselector.go:168: Unable to find image using selector `specific nightly`. Error: no valid nightly found for version 4.14
2023/08/29 10:30:10 versionselector.go:120: No install version found, skipping …
```
> versions: fix specific nightly selector polling

- pkg/common/versions/installselectors/triggered_nightlies.go
the nightly job failed to find the version because it is meant to have `-nightly` appended to it
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-osde2e-main-nightly-4.14-rosa-classic-sts/1697169102356877312
> versions: triggered nightly versions need -nightly appended

- pkg/e2e/e2e.go
10 minutes seems to be too short, the cluster was already not found by the time cleanup was running
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-osde2e-main-nightly-4.14-rosa-classic-sts/1701907186206117888/artifacts/rosa-classic-sts/osde2e-cleanup/build-log.txt
```
2023/09/13 14:12:13 retryer.go:25: error during OCM attempt: couldn't retrieve cluster '267k8n40rj3rea58jf44virq0363kmlh': status is 404, identifier is '404', code is 'CLUSTERS-MGMT-404' and operation identifier is '34680996-a3d2-4ef5-acc6-511a693e3ee7': Cluster '267k8n40rj3rea58jf44virq0363kmlh' not found
```
This will be one cause on why things are getting left up since hibernation will not delete the additional resources
> e2e: increase hibernation time for nightly clusters

- configs/int.yaml
added rosa.env=int  config to  int config file. This goes similar to stage.yaml config file. 
Why? : Without this config, rosa provider env is set to prod by default, which also gets copied to ocm provider. To fix this, it has to be specified here.
> added rosa.env to int config

- pkg/debug/diff.go
this was broken in fb6fe3d88f255f983f354ff1415a9632077e2e09 which caused us to curl an empty string which results in a failure. Put back the logic to handle the URL based on periodic or PR check.
> debug: fix getLastJobID

- go.mod
- pkg/common/helper/helper.go
- pkg/common/helper/pods.go
- pkg/common/runner/pod.go
- pkg/common/runner/runner.go
- pkg/common/runner/service.go
- pkg/e2e/operators/dvo.go
this allows for controlling the output based on test failure as to not spam the output for successful tests. Just naively swap the loggers around.
> common/runner: use ginkgo logr by default

- pkg/common/config/config.go
this value is incorrect and should point to https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs
> config: fix BASE_JOB_URL default value

- pkg/debug/diff.go
the structure of artifacts changed when the job became multi-step
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-osde2e-main-nightly-4.15-rosa-classic-sts/1706851512031907840
the job is diffing the HTML page against the new deps, we just need to format in the JOB_NAME_SAFE variable and the step name. `JOB_NAME_SAFE` can be found as an environment variable in the pod here https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-osde2e-main-nightly-4.15-rosa-classic-sts/1706851512031907840/artifacts/build-resources/pods.json
the file should be https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-osde2e-main-nightly-4.15-rosa-classic-sts/1706851512031907840/artifacts/rosa-cla …
> debug: fix pathing to dependencies.txt

- pkg/e2e/e2e.go
the functionality isn't needed during presubmit jobs
> e2e: only generate deps on periodic jobs

- pkg/e2e/operators/customdomains.go
The tests are sporadically being executed and failing. I can only guess that this label isn't set on the namespace by the time the tests run so we execute when we shouldn't
https://testgrid.k8s.io/redhat-openshift-ocp-release-4.14-informing#periodic-ci-openshift-osde2e-main-nightly-4.14-rosa-classic-sts
> e2e/operators/customdomains: rm ns check

- Dockerfile.osde2e
- Makefile
- go.mod
- pkg/debug/diff.go
- test/mcscupgrade/Dockerfile
1.19 is EOL https://endoflife.date/go
/hold
requires a release PR as well
> Bump to go 1.20

- pkg/common/providers/rosaprovider/cluster.go
- pkg/common/providers/rosaprovider/config.go
this will allow obo to create unique roles based on the cluster name as seen here:
https://github.com/openshift/osde2e-common/blob/8fc51be35b41a45e8e206dd70279e80619fadd8a/pkg/openshift/rosa/cluster.go#L124-L127
https://redhat-internal.slack.com/archives/CMK13BP4J/p1696942947257909?thread_ts=1694780540.450649&cid=CMK13BP4J
[SDCICD-1149](https://issues.redhat.com//browse/SDCICD-1149)
> rosaprovider: allow controlling when to use the default account role prefix

- configs/complete-e2e.yaml
- pkg/e2e/operators/managedupgrade.go
- pkg/e2e/operators/mustgather.go
- includes managed upgrade operator and MGO in harness
- added MigratedHarness to MUO and MGO to exclude from legacy tests
[SDCICD-1142](https://issues.redhat.com//browse/SDCICD-1142)
> include migrated harnesses in suite, exclude from legacy tests with label

- pkg/common/upgrade/managed.go
- pkg/common/upgrade/upgrade.go
- pkg/e2e/e2e.go
- pkg/e2e/routemonitors/routemonitors.go
current upgrade jobs are panicking when trying to create multiple helpers in the routemonitor launched goroutines
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-osde2e-main-osd-aws-upgrade-latest-default-z-minus-1-to-latest-default-z/1715359690713468928
> e2e: only create helper once in upgrade path

- pkg/e2e/operators/dvo.go
- pkg/e2e/operators/mustgather.go
- pkg/e2e/operators/rbac.go
- pkg/e2e/operators/routemonitor.go
- pkg/e2e/operators/splunkforwarder.go
the rolename scheme has changed in 4.15 so it makes testing that these are there more difficult. That brings the question of value in testing that the clusterroles exist, which is just something managed by OLM.
remove any checks for OLM created clusterroles
[SDCICD-1151](https://issues.redhat.com//browse/SDCICD-1151)
> e2e/operators: stop checking for olm clusterroles

- pkg/e2e/harness_runner/harness_runner.go
What:
Replaces RetrieveTestResults by RetrieveResults for reading harness pod results
Why: 
Removes the additional junit xml read error if a test spec has error. 
Also keeps pod artifacts even if test spec fails. 
example: 
CustomDomain Operator in this result 
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/44563/rehearse-44563-periodic-ci-openshift-osde2e-main-rosa-stage-complete-e2e/1717226050116653056
[SDCICD-1142](https://issues.redhat.com//browse/SDCICD-1142)
> fix: remove junit xml error if test errors out

- pkg/e2e/harness_runner/harness_runner.go
Some test harnesses directly use OCM_TOKEN env var to establish ocm client connection,  and are failing to get connection as it does not exist in pod.
PAssing this var to the pod
harness tests using this:
https://github.com/openshift/managed-node-metadata-operator/blob/ae83ee6f0ddf975cb7d61d2d9a78e5a00d40cd76/osde2e/managed_node_metadata_operator_tests.go#L41C2-L41C2
https://github.com/openshift/osd-metrics-exporter/blob/4f2abc0fd6522accda20c02751b84f69c3a1bca2/osde2e/osd_metrics_exporter_tests.go#L54
failure log
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/44563/rehearse-44563-periodic-ci-openshift-osde2e-main-rosa-stage-complete-e2e/1717658209818251264
[SDCICD-1142](https://issues.redhat.com//browse/SDCICD-1142)
> pass OCM token env var to harness pod to fix some tests

- pkg/e2e/osd/machinehealthcheck.go
follow up required to https://github.com/openshift/managed-cluster-config/pull/1916 to fix failing test
https://issues.redhat.com/browse/OSD-19449
/cc @tnierman @AlexVulaj @openshift/openshift-team-sd-cicada
https://testgrid.k8s.io/redhat-openshift-ocp-release-4.15-informing#periodic-ci-openshift-osde2e-main-nightly-4.15-rosa-classic-sts
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-osde2e-main-nightly-4.15-rosa-classic-sts/1721700980438863872
> e2e/osd/machinehealthcheck: bump infra timeout to 10m

- pkg/common/load/load.go
- Loads ocm token passthrough secret for harnesses
This code is designed to do this, but fails to do so, unless SECRET_LOCATIONS are provided. This env var is not set and is not necessary in tekton environment.
After removing this condition, ocm refresh token secret loads in osde2e-ci-secrets namespace for harnesses correctly. 
[SDCICD-1142](https://issues.redhat.com//browse/SDCICD-1142)
> update how ocm token passthrough is loaded for harness

- assets/tests/tests-runner.template
- pkg/common/helper/helper.go
- pkg/e2e/harness_runner/harness_runner.go
Load ci-secrets secret in harness namespace
Load the OCM_TOKEN from ci-secrets secret as env var on harness pod. 
Removes the need to query secrets from osde2e-ci-secrets namespace. 
Tested locally with osde2e / mnmo harness
Triggered by [SDCICD-1142](https://issues.redhat.com//browse/SDCICD-1142)
> load token in harness pod

- pkg/e2e/osd/machinehealthcheck.go
https://github.com/openshift/managed-cluster-config/pull/1919
https://issues.redhat.com/browse/OSD-19449
> e2e/osd/machinehealthcheck: bump expected worker timeout duration

- go.mod
- go.sum
Bump osde2e common to reflect the rosa cli minimum version bump to 1.2.29
https://github.com/openshift/osde2e-common/commit/c29fe617fe0d77b46f3c57a056601d8e7bb7ce36
> OSDe2e common version bump

- pkg/common/aws/s3.go
- pkg/common/aws/s3_session.go
- pkg/common/aws/session.go
- pkg/common/config/config.go
- pkg/common/helper/runner.go
- pkg/common/providers/ocmprovider/cluster.go
- pkg/e2e/e2e.go
- pkg/e2e/harness_runner/harness_runner.go
- pkg/reporting/generate_report.go
Why?:
- E2e harness jobs running on tekton do not provide any useful logs nor junit result files. Result files are immediately destroyed after job runs, pod logs are destroyed on hive on next run. 
- This s3 PR is a viable option to persist pod logs from tekton jobs at this point.
What?:
- IF “LOG_BUCKET” is provided, result files will get uploaded under job folder in s3
- Files will be deleted after one month, this is set by a Lifecycle Rule on the bucket.
- Reuses existing code to upload things to s3 
Alternative solution to blocking card https://issues.redhat.com/browse/APPSRE-8362
> Upload results to s3 bucket if LOG_BUCKET is set

- pkg/e2e/harness_runner/harness_runner.go
What: Adding harness report failures to top level junit report. Adding snippet in harness result handling to insert failures for respective harnesses in the main junit report file. 
Why:
Currently failed harness test specs don't reflect in the main result file giving a false overall positive/green tho a harness assertion fails. 
--
Blocks https://issues.redhat.com/browse/SDCICD-1161
> Fix false positive in harness osde2e runs

- configs/e2e-suite.yaml
In preparation to this change, an identical config named complete-e2e.yaml is [tested  reliably](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-osde2e-main-rosa-stage-complete-e2e/1724336521005240320) over last few weeks. 
This change updates e2e-suite.yaml config to use test harnesses (only) for the migrated operators. Provides all migrated harnesses, labels and a timeout. 
https://issues.redhat.com/browse/SDCICD-1161 
Converted to draft pending https://github.com/openshift/osde2e/pull/2247
> Update e2e-suite config to use migrated operators' test harnesses

- configs/complete-e2e.yaml
harness timeout should be tests.harnessTimeout not suiteTimeout as specified here https://github.com/openshift/osde2e/blob/9e6a51260aef0717635ea43448cbbc8e8f1baae4/pkg/e2e/harness_runner/harness_runner.go#L38
This is causing MNMO harness to timeout at 300 seconds 
Fixing this issue
> fix config name for harness timeout

- configs/e2e-suite.yaml
harness timeout should be tests.harnessTimeout not suiteTimeout as specified here https://github.com/openshift/osde2e/blob/9e6a51260aef0717635ea43448cbbc8e8f1baae4/pkg/e2e/harness_runner/harness_runner.go#L38
This is causing MNMO harness to timeout at 300 seconds 
Fixing this issue
> fix config name for harness timeout - for another config file

- pkg/e2e/operators/configurealertmanager/configurealertmanager.go
CAMO test is failing with roles not found and clusterroles not found
Fixes
- listing roles in openshift-moniroting namespace finds the role correctly
- clusterrole prefix has been truncated since 4.15. checking olm.owner of clusterrole instead of name fixes this
> 4.15 fix test failing on CAMO roles and clusterroles not found

- cmd/osde2e/cleanup/cmd.go
- pkg/common/aws/iam.go
Note to reviewers: Please view diff with w=1 (by default the diff is space-based and shows code replaced rather moved/indented) 
https://github.com/openshift/osde2e/pull/2300/files?w=1
- Added following iam cleanup related flags to existing osde2e cleanup command
```
--iam-dry-run                   Show dry run log of deleting iam resources (default true)
--iam                          Cleanup iam resources
--iam-older-than int         Cleanup iam resources older than this number of days (default 1)
```
`./osde2e cleanup --iam`   deletes 
- oidc provider
- role (and detaches any policies) 
- policy 
older than 24 hours
`./osde2e cleanup --iam --iam-older-than 0`   deletes 
all the above osde2e-related resources without time filter
`./osde2e cleanup --iam --iam-dry-run`   shows what will …
> osde2e cleanup command for iam resources

- pkg/e2e/e2e.go
provision only excution update: skip cleanup and metrics steps for a "provision only" job.  
[SDCICD-1201](https://issues.redhat.com//browse/SDCICD-1201)
> skip cleanup, return early for provision only

- pkg/common/cluster/clusterutil.go
Currently e2e test does not read cluster ID from prow job's SHARED_DIR
Added logic to load cluster ID, IF one exists in SHARED_DIR. 
[SDCICD-1200](https://issues.redhat.com//browse/SDCICD-1200)
> add logic in e2e to read cluster-id from shared_dir

- pkg/common/cluster/clusterutil.go
- pkg/e2e/e2e.go
added log statements to ensure osde2e is writing to and reading from shared-dir in multi step job
> logging to debug shared-dir

- pkg/common/cluster/clusterutil.go
- pkg/common/cluster/healthchecks/healthcheckjob.go
- pkg/e2e/openshift/osdclusterready.go
Reusing existing logic in osde2e-common for osdClusterReady check
Rewrite of this logic in osde2e is redundant.
> reuse existing osd-cluster-ready loop from osde2e-common

- pkg/common/aws/iam.go
Currently cleanup only deleted IDP if URL contains "cloudfront"  
This is leaving some of the cluster IDPs undeleted.
This change also deleted IDPs with "osde2e-" substring in their URL.
> Delete IDP containing "osde2e-" substring

- cmd/osde2e/cleanup/cmd.go
[sdcicd-1206](https://issues.redhat.com//browse/sdcicd-1206)
osdctl cleanup --iam  command should load configs so that AWS creds can be read into  aws session
> load secret locations from vault when running on prow jobs

- cmd/osde2e/test/cmd.go
- pkg/common/config/config.go
- pkg/e2e/openshift/conformance.go
Run ocp conformance tests as osde2e test suite in blocking/conformance job
1. `openshift test` is under osde2e "conformance" test suite. 
2. Label "OCPNightlyBlocking" is added to it
3. Suite name can be passed to osde2e, defaulted to "suite"
4. Test type is set to "openshift/conformance/parallel", same as openshift-e2e-test step default. 
[sdcicd-1224](https://issues.redhat.com//browse/sdcicd-1224)
> option 2: spike running ocp conformance with osde2e  

- pkg/common/cluster/clusterutil.go
clusterutil currently prints out following confusing message for GCP clusters on install failure. Change message to remove AWS specific reference. 
`2024/02/15 14:31:24 clusterutil.go:282: cluster is in error state, check AWS for more details` 
Discovered during https://issues.redhat.com/browse/OSD-20127
> fix error to give provider-neutral error on install fail

- cmd/osde2e/cleanup/cmd.go
- pkg/common/aws/s3.go
- pkg/common/aws/session.go
`osde2e cleanup --s3 --dry-run=false` 
finds buckets with prefix "osde2e-" or "managed-velreo" older than given duration, then deletes bucket objects and then buckets
repurposes dry-run and older-than flags from existing command by removing prefix "iam" 
[SDCICD-1225](https://issues.redhat.com//browse/SDCICD-1225)
> added s3 bucket cleanup to osde2e cleanup command

- pkg/common/cluster/clusterutil.go
- pkg/common/cluster/healthchecks/healthcheckjob.go
- pkg/common/providers/ocmprovider/cluster.go
- pkg/e2e/e2e.go
1. Polling cluster ocm status "ready" is moved immediately after provision, outside of healthcheck.
There should be no use case of osde2e that skips cluster becoming "ready" prior to any processing. 
Therefore, adding basic ocm ready wait immediately after provision, outside of old healthcheck logic. Healthcheck can still be skipped.  
2. Function cleanup: removing unused arg from ClusterHEalthcheck function
3. Function cleanup: Moving "install Timeout" initializing inside  WaitForOCMProvisioning instead of 4 duplicate lines everytime it's invoked. 
https://issues.redhat.com/browse/SDCICD-1192
> wait until ocm reports cluster install "ready" before proceeding with tests

- pkg/e2e/openshift/config.go
Conformance test errors with
`error converting to options: stat /tmp/kubeconfig: no such file or directoryerror: stat /tmp/kubeconfig: no such file or directory` 
This var is set after provision and doesn't need to be overridden here. 
[sdcicd-1192](https://issues.redhat.com//browse/sdcicd-1192)
> remove kubeconfig from conformance command

- pkg/common/cluster/clusterutil.go
- pkg/common/config/config.go
- pkg/e2e/e2e.go
- pkg/e2e/openshift/config.go
1. move shared clusterId loading to the top, after kubeconfig loading.
2. provide shared kubeconfig path to conformance command if one exists ( For this part, the conformance cmd has never been ran from current prow jobs so more things may need to be set for this command in followup PRs, through trial and error.) 
includes fix for [sdcicd-1192](https://issues.redhat.com//browse/sdcicd-1192)
> SDCICD-1192 Fix conformance job

- pkg/e2e/openshift/config.go
- pkg/e2e/openshift/conformance.go
- Added back test command settings, 
- Better error message for conformance xml result reading error
Testing - 
Run test command locally with osde2e 
create rosa cluster
copy admin kubeconfig to base dir/tmp 
with env:
SHARED_DIR=tmp
TEST_KUBECONFIG=tmp/kubeconfig
run osde2e with 
./osde2e test --configs=rosa,stage,blocking-suite
-- 
This should fail successfully, with log file indicating a panic at nodeLabel checks
[SDCICD-1192](https://issues.redhat.com//browse/SDCICD-1192)
> Conformance command fixes

- pkg/common/load/load.go
Fixes [sdcicd-945](https://issues.redhat.com//browse/sdcicd-945)
- We receive error message in the log:
`error loading passthru-secret file /usr/local/osde2e-dev/..data: read /usr/local/osde2e-dev/..data: is a directory`
- This is not mitigated by skipping directories, which we are doing currently.
https://github.com/openshift/osde2e/blob/3859fc4ad322b4d78aba89cfebe47c9986f1b659/pkg/common/load/load.go#L89
- The origin of this `..data` directory is in vault backend adding hidden keys to vault https://github.com/hashicorp/vault/blob/012c3422f8e1d5fa8d564010683fd9487c00f41f/ui/app/adapters/keymgmt/key.js#L80
- This solution will skip all hidden paths starting with ".",  and remove distracting passthrough key error message.
> sdcicd-945 eliminate error log related to hidden vault key `..data`

- pkg/e2e/osd/machinehealthcheck.go
new instance types were added here https://github.com/openshift/managed-cluster-config/pull/2061 
test is failing due to these 2 missing from expected instance types. updating test.
[SDCICD-1255](https://issues.redhat.com//browse/SDCICD-1255)
> sdcicd-1255 add new instance types in MHC

- configs/e2e-suite.yaml
Remove [Suite: app-builds] from e2e-suite 
What does this suite test? - customer workload build (requested in [OSD-2132](https://issues.redhat.com//browse/OSD-2132)) 
Why exclude it? - This suite never ran correctly for the past several months. It recently started running due to conformance test updates, and has been perma failing ever since. 
osde2e doesn't own the test and there;s no clear owner monitoring this test. 
It doesn't have a proper set up at this point. We also have a simpler workload test which would be the first step before testing more complicated customer workloads in regular nightlies https://github.com/openshift/osde2e/tree/main/pkg/e2e/workloads
> SDCICD-1260 remove workload ocp test from e2e-suite

- pkg/e2e/openshift/config.go
While running conformance tests for GCP in [SDCICD-1198](https://issues.redhat.com//browse/SDCICD-1198) I came across the hardcoded "aws" provider in ocp conformance test command
This PR updates the ocp test command to substitute cloud provider name from viper config
> SDCICD-1198 make conformance test command runner compatible with GCP 

- cmd/osde2e/cleanup/cmd.go
- cmd/osde2e/completion/cmd.go
resolve staticcheck lint ST1005 in cmd/osde2e. Error strings should not be capitalized as they can (and should) be used to build up a string of an error message when printed. No error is standalone and provides context to other errors messages.
```
cmd/osde2e/cleanup/cmd.go:138:11: error strings should not be capitalized (ST1005)
cmd/osde2e/cleanup/cmd.go:143:12: error strings should not be capitalized (ST1005)
cmd/osde2e/cleanup/cmd.go:147:12: error strings should not be capitalized (ST1005)
cmd/osde2e/cleanup/cmd.go:151:12: error strings should not be capitalized (ST1005)
cmd/osde2e/cleanup/cmd.go:157:12: error strings should not be capitalized (ST1005)
cmd/osde2e/completion/cmd.go:28:10: error strings should not be capitalized (ST1005)
```
https://staticcheck.io/docs/checks/#ST1005 …
> cmd/osde2e: error strings should not be capitalized (ST1005)

- pkg/common/providers/rosaprovider/rosa.go
klogr.New has been deprecated in favor of a new textlogger package
https://pkg.go.dev/k8s.io/klog/v2/klogr#New
```
pkg/common/providers/rosaprovider/rosa.go:63:5: klogr.New is deprecated: this uses a custom, out-dated output format. Use textlogger.NewLogger instead.  (SA1019)
```
[SDCICD-1266](https://issues.redhat.com//browse/SDCICD-1266)
> rosaprovider: klogr -> textlogger

- pkg/common/cluster/clusterutil.go
according to the deprecation message, usage of `PollImmediate` should be replaced with `PollUntilContext{Timeout,Cancel}` which behaves correctly when canceling the parent context. In cases that we don't use the context, just ignore it as a parameter.
[SDCICD-1266](https://issues.redhat.com//browse/SDCICD-1266)
> pkg/common/cluster: deprecated wait.PollImmediate

- pkg/common/aws/s3.go
- pkg/common/helper/runner.go
- pkg/common/providers/ocmprovider/cluster.go
- pkg/e2e/e2e.go
write logs when metrics upload to s3 fails. do not fail full test run or obstruct test execution. with current code, test never executes, times out after 3 hours (or preset timeout) wait.
Nightlies are currently reporting this error due to possible misconfiguration of metrics aws account.
```
2024/04/09 10:04:29 clusterutil.go:260: Error adding property to cluster: failed to upload cluster property metrics: AccessDenied: Access Denied
status code: 403, request id: 497BD0N97CWWVV40, host id: qBhmokwZcEYOqf3+2BN8t1UMaNeUFxfh2Z5uoZwRWeqT6r8k+vF7TtovHiOGYjy6z+nGvJpTB+8EZZ7EZ+Zq4A==
{"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:169","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 3h0m0s …
```
> do not fail test for errors coming from metrics bucket

- pkg/reporting/generate_report.go
- pkg/reporting/report_to_slack.go
- pkg/reporting/reporters/weather/weather_reporter.go
```
pkg/reporting/generate_report.go:37:2: should use sort.Strings(...) instead of sort.Sort(sort.StringSlice(...)) (S1032)
pkg/reporting/report_to_slack.go:24:16: x = append(y) is equivalent to x = y (SA4021)
pkg/reporting/reporters/weather/weather_reporter.go:311:2: should use sort.Strings(...) instead of sort.Sort(sort.StringSlice(...)) (S1032)
```
resolve the linting failures in `pkg/reporting`. We should investigate if the `weather` stuff can be removed later on
> SDCICD-1266: resolve lint issues in pkg/reporting

- pkg/e2e/openshift/config.go
gcp conformance tests require "gce" as cloud type and a gcp project id.
> SDCICD-1198 provide required gcp args to ocp tests

- pkg/common/providers/ocmprovider/cluster.go
1. skip waiting if cluster already uninstalling - this causes additional 15 min wait per cluster with no action 
2. replace pollImmediate with PollUntilContextTimeout ([SDCICD-1266](https://issues.redhat.com//browse/SDCICD-1266))
> SDCICD-1240 skip waiting if cluster already uninstalling

- Dockerfile.osde2e
- go.mod
- go.sum
1.20 went EOL 2 months ago
https://endoflife.date/go
When running from main
```
❯ go mod tidy -go=1.20
go: github.com/openshift-online/ocm-sdk-go@v0.1.410 requires go@1.21, but 1.20 is requested
```
the new version of ocm-sdk-go is requiring go 1.21, so bump to resolve this
> misc: bump go 1.21

- pkg/e2e/osd/machinehealthcheck.go
instance type r7i.metal-48xl was removed here  https://github.com/openshift/managed-cluster-config/commit/db422a977e93598a49cc9e8fdb6ef3c860df8718
test is failing due to this https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-osde2e-main-nightly-4.16-rosa-classic-sts/1780152469666402304
updating expected instance type list .
[SDCICD-1255](https://issues.redhat.com//browse/SDCICD-1255)
> SDCICD-1255 updating instance type list to match MCC

- pkg/e2e/e2e.go
we already carry around a variable named `cluster` while provisioning and testing the cluster, this was imported at somepoint and used without it's alias only in this case. Use the `clusterutil` import to be consistent
```
pkg/e2e/e2e.go:29:2: package "github.com/openshift/osde2e/pkg/common/cluster" is being imported more than once (ST1019)
pkg/e2e/e2e.go:30:2: other import of "github.com/openshift/osde2e/pkg/common/cluster"
```
> SDCICD-1266: duplicate import - pkg/common/cluster

- pkg/common/helper/crud.go
- pkg/common/helper/helper.go
- pkg/common/helper/projects.go
- pkg/common/helper/utilities.go
- pkg/common/helper/workloads.go
PollImmediate is deprecated, swap to using with context version for proper cancelation. Resolved all within the `pkg/common/helper` package.
A few places we weren't handling errors. Where it is obvious, use the return value; where it isn't (gcp) continue to ignore them but explicitly.
> SDCICD-1266: PollImmediate -> PollUntilContextTimeout

- pkg/common/runner/pod.go
these are deprecated for the respective function without the `Ptr`
suffix.
> SDCICD-1266: replace deprecated Int*Ptr func

- go.mod
- pkg/e2e/verify/encrypted_storage.go
the other import is deprecated in favor of this path
```
pkg/e2e/verify/encrypted_storage.go:41:13: "google.golang.org/genproto/googleapis/cloud/kms/v1" is deprecated: Please use types in: cloud.google.com/go/kms/apiv1/kmspb. Please read https://github.com/googleapis/google-cloud-go/blob/main/migration.md for more details.  (SA1019)
pkg/e2e/verify/encrypted_storage.go:256:45: kmsprotov1.GetKeyRingRequest is deprecated: Please use types in: cloud.google.com/go/kms/apiv1/kmspb  (SA1019)
pkg/e2e/verify/encrypted_storage.go:263:49: kmsprotov1.CreateKeyRingRequest is deprecated: Please use types in: cloud.google.com/go/kms/apiv1/kmspb  (SA1019)
pkg/e2e/verify/encrypted_storage.go:279:43: kmsprotov1.GetCryptoKeyRequest is deprecated: Please use types in: cloud.google.com/go/kms/apiv1/kmspb …
```
> SDCICD-1266: switch kms import out

- pkg/common/runner/pod.go
- pkg/common/runner/results_test.go
- pkg/common/runner/runner.go
- pkg/common/runner/service.go
- pkg/common/runner/service_test.go
pass down a context from the entrypoint of runner to each place it is used to allow taking advantage of context management with ginkgo in the future (cancelation/timeout on failure of test for example)
also resolve Int64Ptr/Int32Ptr deprecations while here
[SDCICD-1266](https://issues.redhat.com//browse/SDCICD-1266)
https://go.dev/blog/context
> SDCICD-1266: pass context down through the runner

- pkg/common/cluster/clusterutil.go
- pkg/common/cluster/healthchecks/healthcheckjob.go
- pkg/common/cluster/healthchecks/machines.go
- pkg/common/helper/olm.go
- pkg/common/helper/workloads.go
- pkg/common/prometheus/connect.go
- pkg/common/providers/mock/mock.go
- pkg/common/providers/ocmprovider/cluster.go
- pkg/common/providers/ocmprovider/quota.go
- pkg/common/runner/results.go
- pkg/common/upgrade/upgrade.go
- pkg/common/versions/upgradeselectors/latest_version_selector.go
- pkg/common/versions/upgradeselectors/latest_y_selector.go
- pkg/common/versions/upgradeselectors/latest_z_selector.go
- pkg/debug/diff.go
- pkg/e2e/operators/managedvelero.go
- pkg/e2e/operators/operators.go
change all error strings that start with a capital letter to lowercase. Errors are meant to be joined and wrapped, giving context to other errors. Capitalization and punctuation interupt the flow and lead to poorly formatted error messages.
```
$ staticcheck ./... | grep "error strings"
pkg/common/cluster/clusterutil.go:316:10: error strings should not be capitalized (ST1005)
pkg/common/cluster/healthchecks/healthcheckjob.go:26:10: error strings should not be capitalized (ST1005)
pkg/common/cluster/healthchecks/machines.go:36:17: error strings should not be capitalized (ST1005)
pkg/common/cluster/healthchecks/machines.go:46:18: error strings should not be capitalized (ST1005)
pkg/common/helper/olm.go:21:10: error strings should not be capitalized (ST1005)
pkg/common/helper/olm.go:26:10: …
```
> SDCICD-1266: resolve all error strings capitalized

- pkg/common/metadata/metadata.go
- pkg/common/upgrade/managed.go
- pkg/e2e/e2e.go
- pkg/e2e/harness_runner/harness_runner.go
- pkg/e2e/osd/dedicatedadmin.go
Resolve the lints below: S1036, S1039, S1005
```
❯ staticcheck ./... | grep unnecessary
pkg/common/metadata/metadata.go:213:2: unnecessary guard around map access (S1036)
pkg/common/metadata/metadata.go:232:2: unnecessary guard around map access (S1036)
pkg/common/upgrade/managed.go:278:18: unnecessary use of fmt.Sprintf (S1039)
pkg/common/upgrade/managed.go:309:17: unnecessary use of fmt.Sprintf (S1039)
pkg/common/upgrade/managed.go:325:17: unnecessary use of fmt.Sprintf (S1039)
pkg/e2e/e2e.go:503:5: unnecessary assignment to the blank identifier (S1005)
pkg/e2e/harness_runner/harness_runner.go:95:35: unnecessary use of fmt.Sprintf (S1039)
pkg/e2e/osd/dedicatedadmin.go:243:24: unnecessary use of fmt.Sprintf (S1039)
pkg/e2e/osd/dedicatedadmin.go:251:25: unnecessary use of fmt.Sprintf …
```
> SDCICD-1266: resolve unnecessary actions lint

- cmd/osde2e/cleanup/cmd.go
- pkg/common/aws/ec2.go
Adds "--elastic-ip" flag to cleanup subcommand. Accepts "--dry-run"
ReleaseElasticIPs releases elastic IPs from loaded aws session. If an instance is
associated with it, we skip its deletion and log tag name. Dryrun returns aws Error
from AWS api and is logged.
Dry run output:
```
Addresses found: 34
Address 35.153.58.98 not deleted: DryRunOperation: Request would have succeeded, but DryRun flag is set.
status code: 412, request id: 890746c9-6229-463a-80aa-df5e3804f4ed
Address 35.169.191.91 not deleted: DryRunOperation: Request would have succeeded, but DryRun flag is set.
status code: 412, request id: 76245cc6-5bbf-4373-833f-fec5f909de01
[....]
Finished elastic IP cleanup. Deleted 0 addresses.
```
Active run output
```
Addresses found: 34
Address deleted: 107.22.98.140
Address deleted: …
```
> SDCICD-1271 add elasticIP release process to cleanup command

- pkg/common/aws/ec2.go
some associations are not linked to instances resulting in empty values in logs. Use assoc id instead, which is always present.
> SDCICD-1271 update log for skipping deletion of associated ips

- cmd/osde2e/test/cmd.go
- pkg/common/config/config.go
- pkg/e2e/openshift/config.go
ocp tests dry run is currently the only way to skip tests. A list of all tests is generated using dry run and a test list file is created by inverse grepping it with the skipped test specs regex.
> SDCICD-1198 ocp test skip regex

- scripts/gap-analysis-jobs.sh
Final PR for the Gap Analysis work for 4.16, moving the script to the main branch now that the pipelines are working as intended. 
This script is a bit different from the full parameterized job on purpose. It is suppose to be simplistic and should allow for parallel executions in the future.
> SDCICD-1268 Enable multi job triggger for gap analysis in Jenkins

- .ci-operator.yaml
we can configure the build root from our repository instead of having to
bump in both places for go version bumps
https://docs.ci.openshift.org/docs/architecture/ci-operator/#build-root-image
> misc: add build root image config

- pkg/e2e/openshift/app_builds.go
- pkg/e2e/openshift/conformance.go
add ServiceAccountDir value to config instances
This value will be used to find ca.crt and token values  in command generator https://github.com/openshift/osde2e/blob/3983b960494e52019bed04aa3e9119070c55e26e/pkg/e2e/openshift/config.go#L39
[SDCICD-1275](https://issues.redhat.com//browse/SDCICD-1275)
> add ServiceAccountDir value to config instances

- pkg/common/versions/installselectors/triggered_nightlies.go
- pkg/common/versions/versionselector.go
currently we're using PROW_JOB_ID which may be unreliable if the job ID changes. RELEASE_IMAGE_LATEST is less likely to change.
Discovered during [SDCICD-1198](https://issues.redhat.com//browse/SDCICD-1198)
> use "RELEASE_IMAGE_LATEST" env to find version for nightly jobs

- pkg/e2e/openshift/config.go
- pkg/e2e/openshift/conformance.go
Fixes breaking conformance jobs where skip regex is not present
[sdcicd-1198](https://issues.redhat.com//browse/sdcicd-1198)
> allow origin test to run given suite of skip regex not provided

- pkg/common/config/config.go
- pkg/common/versions/installselectors/triggered_nightlies.go
"RELEASE_VERSION_LATEST" is only applied to direct job pod, osde2e pod does not have the desired value for this
eg: this is printed in osde2e pod: 
PROW_JOB_ID: "4.15.0-0.nightly-2024-05-23-090107-rosa-classic-sts-conformance"
2024/05/23 09:36:55 
RELEASE_IMAGE_LATEST: "registry.build05.ci.openshift.org/ci-op-mqrdrqz8/release@sha256:459d06cfc1a5b57553381d46279f7e6c43a43465ecf41b68704f9ffe92c0e890"
> use  "PROW_JOB_ID" only to find version for nightly jobs

- assets/tests/ocp-tests-runner.template
- pkg/common/runner/service.go
some jobs are adbruptly failing while polling runner pod with no clear root cause.
example https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-openshift-osde2e-main-nightly-4.15-conformance-rosa-classic-sts/1793144924145717248/artifacts/conformance-rosa-classic-sts/osde2e-test/build-log.txt 
implementing following checks
1. provide container name for `oc rsync` in case it is selecting "test-harness" container which should be terminated before collecting results
2. if test pod is completely gone, log it in runner output instead of erroring out
3. log pod status while polling
[sdcicd-1198](https://issues.redhat.com//browse/sdcicd-1198)
> avoiding abrupt pod exits

- pkg/common/cluster/clusterutil.go
- pkg/common/cluster/healthchecks/healthcheckjob.go
it seems that at some point this broke, the hive cluster is being queried looking for the cluster-ready job. Pass the specific clusterconfig directly to the new openshift client. All of the tests are being executed after this fails, then they subsequently fail.
```
2024/05/30 04:39:51 e2e.go:154: *******************
2024/05/30 04:39:51 e2e.go:155: Cluster failed health check: cluster failed health check: unable to get job logs for openshift-monitoring/osd-cluster-ready: failed to list pods for job osd-cluster-ready in openshift-monitoring namespace: failed to get API group resources: unable to retrieve the complete list of server APIs: v1: Get "https://api.hives02ue1.j5l5.p1.openshiftapps.com:6443/api/v1": dial tcp 10.163.143.192:6443: i/o timeout
2024/05/30 04:39:51 e2e.go:156: …
```
> healthchecks: use cluster restconfig

- pkg/common/runner/pod.go
- pkg/common/runner/runner.go
- pkg/common/runner/service_test.go
currently test pod doesn't have a specific owner. This causes garbage collector to clean the pod and related objects abruptly during test runs. Instead, create a job to own the pod and namespace objects.
Discovered in conformance job for [sdcicd-1198](https://issues.redhat.com//browse/sdcicd-1198)
> spin up a osde2e runner job as owner of test pod

- pkg/e2e/harness_runner/harness_runner.go
when focusing specific tests, this shouldn't be printed unless it is being executed
> e2e/harness_runner: log harnesses in beforeall

- pkg/e2e/osd/inhibitions.go
- pkg/e2e/state/alerts.go
the code in pkg/common/prometheus doesn't work with 4.16 clusters, use the one from osde2e-common which falls back to openshift/library-go. We should eventually deprecate all of pkg/common/prometheus
```
------------------------------
• [FAILED] [0.150 seconds]
[Suite: e2e] Cluster state [It] should have no alerts [E2E]
/var/home/bpratt/git/openshift/osde2e/pkg/e2e/state/alerts.go:39
[FAILED] error creating a prometheus client
Unexpected error:
<*errors.errorString | 0xc000066520>:
failed to find token secret for prometheus-k8s SA
{
s: "failed to find token secret for prometheus-k8s SA",
}
occurred
In [It] at: /var/home/bpratt/git/openshift/osde2e/pkg/e2e/state/alerts.go:43 @ 05/30/24 09:29:16.55
------------------------------
•••••••••
------------------------------
• [FAILED] [600.664 …
```
> e2e: use common prometheus client

- pkg/e2e/state/alerts.go
KUBECONFIG is never set in the setup of e2e so `openshift.New` fails trying to find config to use. Just use the helper directly and get the client created from it.
This worked locally because I had `KUBECONFIG` set
```
[Suite: e2e] Cluster state [BeforeAll] should have no alerts [E2E]
[BeforeAll] /go/src/github.com/openshift/osde2e/pkg/e2e/state/alerts.go:40
[It] /go/src/github.com/openshift/osde2e/pkg/e2e/state/alerts.go:49
[FAILED] unable to create openshift client
Unexpected error:
<*fmt.wrapError | 0xc000d2a140>:
failed to get kubernetes config: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
{
msg: "failed to get kubernetes config: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT …
```
> e2e/state: use helper client

- pkg/common/helper/helper.go
this will be useful to write provider specific tests
this came up during question from operator team regarding writing provider specific tests:
- harness test spec [here](https://github.com/openshift/aws-vpce-operator/pull/226/files#diff-497149bdd6d3190416c37b28ff982d6199a7bacd2795d34ea2cc655304858d0fR64) doesn’t have a label, osde2e doesn’t use that to select the spec.
- osde2e uses [this](https://github.com/openshift/osde2e/blob/ff7b6ccb4ebcb03ed8795efde58f8aa676446215/pkg/e2e/harness_runner/harness_runner.go#L35) TestHarness label and HARNESS_IMAGES env var to select harness test image
- adding labels to harness test spec might not take any effect,   because osde2e doesn’t run tests, only runs the image with [this entry poin](https://github.com/openshift/aws-vpce-operator/blob/1bf290f86 …
> give cloud provider id env var to harness images

- pkg/common/config/config.go
- pkg/common/config/gcp_config.go
- pkg/common/helper/helper.go
- pkg/common/providers/ocmprovider/cluster.go
- pkg/common/providers/ocmprovider/config.go
- pkg/e2e/openshift/config.go
We set gcp CCS account configs in viper (1) during cluster install and (2) in ocp conformance test
This change
1. moves gcp configs to their own config file
2. sets them in a retrieve function called before cluster create
> sdcicd-1198 improve gcp configs to properly set ccs creds

- pkg/e2e/verify/encrypted_storage.go
Non ccs cluster tests should not be accessing cloud credentials, as we do not give access to them through osde2e.
relates to [SDCICD-1136](https://issues.redhat.com//browse/SDCICD-1136)
> skip encrypted cloud storage access test for GCP non-CCS

- pkg/common/helper/helper.go
- pkg/common/load/load.go
- pkg/e2e/e2e.go
add cloud secrets to harness passthough - loaded from viper configs
compress code to load passthrough secrets - osde2e-ci-secrets namespace is not needed any more since a passthru secrets are loaded into harness pod thru the harness namespace secret. 
[SDCICD-885](https://issues.redhat.com//browse/SDCICD-885)
> add cloud secrets to harness passthough

- .tekton/osde2e-main-e2e-test.yaml
add the initial pipeline which will be used in an
IntegrationTestScenario on build of osde2e to validate the binary before release
https://redhat-appstudio.github.io/docs.appstudio.io/Documentation/main/how-to-guides/testing_applications/proc_creating_custom_test/
> SDCICD-1306: add tekton pipeline to execute osde2e

- cmd/osde2e/cleanup/cmd.go
The previous log output was:
```
Cluster will be deleted: 26hq23dvcrsueamlet9qmogg26g9cr20 (created 2023-09-280)
Error deleting cluster: cluster already uninstalling, skipped
```
To correct the date format in the log, change from `creationTime.Format("2006-01-20")` to `creationTime.Format("2006-01-02")`
> Update date format for cleanup cluster logs

- pkg/common/config/config.go
- pkg/e2e/e2e.go
Konflux supports reporting results based on a standard schema that
includes failures, successes, warnings during an integration test
scenario. Write out the results to `KONFLUX_TEST_OUTPUT_FILE` which will be
set to the `TEST_OUTPUT` result path.
This is just an initial attempt at something useable, it can be improved
upon to include things like `notes` and `warnings`.
Using it in a tekton task:
```yaml
...
results:
- name: TEST_OUTPUT
steps:
- image: $(params.COMPONENT_IMAGE)
command:
- /osde2e
env:
- name: KONFLUX_TEST_OUTPUT_FILE
value: $(results.TEST_OUTPUT.path)
```
```
$ KONFLUX_TEST_OUTPUT_FILE=/tmp/konflux-results/TEST_OUTPUT go run ./cmd/osde2e/ test
...
$ cat /tmp/konflux-results/TEST_OUTPUT
{"failures":1,"result":"FAILURE","successes":26,"timestamp":"2024-06-10T02:58:29-05:00"," …
```
> SDCICD-1306: write std konflux TEST_OUTPUT results

- .tekton/osde2e-main-pull-request.yaml
- .tekton/osde2e-main-push.yaml
- osde2e.Dockerfile
when trying to build the existing Dockerfile, it fails the enterprise-contract policy due to the base image not being allowed. We should migrate to using an image built from the allowed registries
```
[report]   - metadata:
[report]       code: base_image_registries.base_image_permitted
[report]       collections:
[report]       - minimal
[report]       - redhat
[report]       depends_on:
[report]       - base_image_registries.base_image_info_found
[report]       - base_image_registries.allowed_registries_provided
[report]       description: Verify that the base images used when building a container image
[report]         come from a known set of trusted registries to reduce potential supply chain
[report]         attacks. By default this policy defines trusted registries as registries …
```
> SDCICD-1306: add new EC compatible Dockerfile

- go.mod
- go.sum
- pkg/common/helper/impersonate.go
- pkg/e2e/webhooks/webhooks.go
use the dynamic client to create CustomDomain CRs and MustGather CRs so that we don't pull in the dependency of both operators
> e2e/webhooks: use dynamic client

- pkg/e2e/e2e.go
when running against an existing cluster, there is no reason to query
the versions endpoint to select cluster versions if we provide an
existing cluster.
```
$ time go run ./cmd/osde2e/ test --configs aws,stage,pr-check --skip-destroy-cluster --skip-health-check --skip-must-gather --cluster-id xxxxxxxxxxxxxxxxxxxxxxxx
```
before:
```
real	3m12.224s
user	0m14.185s
sys	0m1.931s
```
after:
```
real	1m20.389s
user	0m3.436s
sys	0m0.611s
```
> e2e: skip setup if cluster-id provided

- pkg/common/aws/s3.go
logs bucket is self-cleaning after 30 days, skip this from bucket removal.
Fixes s3 upload errors in self service and tekton jobs.
> do not delete harness logs bucket in s3 cleanup

- .tekton/osde2e-main-e2e-test.yaml
since this job is for validating osde2e, let's just run the minimum set of tests and skip must-gather (we have no where to store it currently)
> SDCICD-1306: set pr-check config/skip must-gather

- osde2e.Dockerfile
when using the ubi-minimal image build from the golang-builder, we are getting a `glibc not found` error when trying to run osde2e. Swap to the rhel9-2-els image that is used by other konflux builds
> SDCICD-1306: use els base image

- osde2e.Dockerfile
Resolve the preflight-checks failures. Brings osde2e image more inline with compliance requirements
```
{
"name": "HasLicense",
"elapsed_time": 0,
"description": "Checking if terms and conditions applicable to the software including open source licensing information are present. The license must be at /licenses",
"help": "Check HasLicense encountered an error. Please review the preflight.log file for more information.",
"suggestion": "Create a directory named /licenses and include all relevant licensing and/or terms and conditions as text file(s) in that directory.",
"knowledgebase_url": "https://access.redhat.com/documentation/en-us/red_hat_software_certification/2024/html-single/red_hat_openshift_software_certification_policy_guide/index#assembly-requirements-for-container-images_openshi …
```
> SDCICD-1306: copy license and set USER

- pkg/common/helper/helper.go
Fixes CIO failing test harness
both gcp and aws jobs need CLOUD_PROVIDER_REGION to work
tekton job and CIO harness are set up to use this, but osde2e was not passing it to the harness. Adding it.
> sdcicd-885 add missing cloud provider region var to harness image

- cmd/osde2e/cleanup/cmd.go
- pkg/common/aws/ec2.go
- pkg/common/aws/iam.go
- pkg/common/aws/s3.go
- pkg/common/config/config.go
- pkg/common/load/load.go
- The `--send-cleanup-summary` option enables the sending of a detailed summary of the cleanup status to [#sd-cicd-notifications](https://redhat.enterprise.slack.com/archives/C06HQR8HN0L)
- This summary includes information about the status of various AWS resources deleted/failed. Some of the errors and the build log link are provided in the same thread.
> SDCICD-1221 Slack notification functionality

- cmd/osde2e/cleanup/cmd.go
- pkg/common/config/config.go
- Set `JobID` Using `BUILD_ID` Instead of `BUILD_NUMBER`
- The `JobID` was previously set using the `BUILD_NUMBER` environment variable, which is not accessible to the osde2e code. Since `BUILD_ID` and `BUILD_NUMBER` are equivalent, we are replacing `BUILD_NUMBER` with `BUILD_ID`
> SDCICD-1335 Use BUILD_ID instead of BUILD_NUMBER for prow logs URL

- cmd/osde2e/cleanup/cmd.go
- pkg/common/aws/ec2.go
- pkg/common/config/config.go
- `--ec2` parameter terminates EC2 instances with tag `Name: osde2e*` and older than 24 hrs.
- Ignores EC2 instances with tag `Name: osde2e-proxy*`
- Notifcation sample: https://redhat-internal.slack.com/archives/C06HQR8HN0L/p1721926378565619
> SDCICD-1330 EC2 instance cleanup

- .tekton/osde2e-main-e2e-test.yaml
We're noticing some aws creds being rotated in the way that an OSD AWS CCS job would do, after this pr check job started running, eg this [run](https://console.redhat.com/application-pipeline/workspaces/osde2e-cicada/applications/osde2e/pipelineruns/osde2e-shbvw-r4vnd/logs).
Changing the type of this cluster to ROSA from OSD AWS to avoid unintentional creds rotation.
> change konflux e2e pr check to rosa

- scripts/gap-analysis-jobs.sh
currently code that auto creates vpc is broken. providing subnet IDs will unblock job execution for [OSD-24677](https://issues.redhat.com/browse/OSD-24677)
> SDCICD-1382 allow passing subnet IDs in jenkins gap analysis job

- scripts/parameterized-job.sh
SREs frequently need to spin up specific nighlty clusters for testing. 
To trigger specific nightly, we are now using INSTALL_LATEST_NIGHTLY instead of previous INSTALL_LATEST_XY 
Update parameterized job to accept it
> fix param name for specific nightly in parameterized jenkins job template 

- pkg/common/versions/versionselector.go
it still times out at 30 minutes sometimes
> pkg/common/versions: increase triggered nightly timeout

- test/sdn_migration/sdn_migration_test.go
Updates cluster wide proxy env vars so validate-sdn-ovn-migration-jobs.sh can run as a Jenkins jobs
> [OSD-25354-update-sdn-ovn-proxy-vars] update cluser wide proxy env vars

- test/sdn_migration/README.md
- test/sdn_migration/scripts/validate-sdn-ovn-migration-jobs.sh
Update validate-sdn-ovn-migration-jobs.sh env vars to match env vars in https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/resources/jenkins/osde2e/secrets.yaml?ref_type=heads#L29 so the script can run as a Jenkins job
> update validate-sdn-ovn-migration-jobs.sh vars

- test/sdn_migration/sdn_migration_test.go
```
test/sdn_migration/sdn_migration_test.go:13:2: package "github.com/onsi/ginkgo/v2" is being imported more than once (ST1019)
test/sdn_migration/sdn_migration_test.go:14:2: other import of "github.com/onsi/ginkgo/v2"
test/sdn_migration/sdn_migration_test.go:23:2: package "k8s.io/apimachinery/pkg/apis/meta/v1" is being imported more than once (ST1019)
test/sdn_migration/sdn_migration_test.go:24:2: other import of "k8s.io/apimachinery/pkg/apis/meta/v1"
```
> test/sdn_migration: resolve lint issues

- pkg/common/config/aws_config.go
- pkg/common/config/config.go
[SDCICD-1411](https://issues.redhat.com//browse/SDCICD-1411) add ability to alternate between two aws accounts when AWS_SHARED_CREDENTIALS are provided in env var
- AWSSharedCredentials is the base64 encoded AWS credentials file content.
- Variable should contain two named profiles: "profile-a" and "profile-b"
If provided, supersedes AWS secret set in env.
- This is used to optimize AWS resource spending by nuking each of the 2 accounts alternately.
-  Since simply checking whether current week is odd or even
within current year may result in unexpected outage if a year has
odd number of weeks, use odd/even based on a constant start date.
> SDCICD-1411 add ability to alternate between two aws accounts 

- test/sdn_migration/sdn_migration_test.go
This PR increases the wait timeout so clusters with 20+ replicas are given enough time to complete the upgrade. Also it adds a clusterOperatorHealthCheck function to ensure operators are healthy and all nodes are in a schedulable state before proceeding to the next step
> Add ClusterOperator health check

- osde2e.Dockerfile
- /.config/ocm dir
This fixes an issue for the CI in https://github.com/openshift/osde2e/pull/2822 to pass. We need to create the /.config/ocm dir in order to sign in using client-id and secret. 
2025/01/22 04:08:39 e2e.go:78: Error getting cluster provider: failed to construct rosa provider: login failed with "ERR: Failed to create OCM connection: error creating connection. Can't persist tokens to config: Failed to create directory /.config/ocm: mkdir /.config: permission denied\n": failed to wait for command to finish: exit status 1
Tested locally: 
```
2025/01/22 16:16:32 configs.go:24: Will load config hypershift
2025/01/22 16:16:32 e2e.go:354: Writing files to report directory: /tmp/osde2e-2boqjqtmbf
2025/01/22 16:16:32 e2e.go:376: Outputting log to build log at …
```
> Fix permission error by setting writable config directory

- cmd/osde2e/cleanup/cmd.go
when ran on a periodic, this panicks and fails before actually cleaning up the cluster
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-openshift-osde2e-main-nightly-4.19-rosa-classic-sts/1886627949675810816/build-log.txt
> cmd/osde2e: fix panic in cleanup

- go.mod
- go.sum
- osde2e.Dockerfile
- pkg/common/config/config.go
- pkg/common/providers/ocmprovider/config.go
- pkg/common/providers/ocmprovider/ocm.go
- pkg/common/providers/ocmprovider/versions.go
- pkg/common/providers/rosaprovider/rosa.go
- scripts/gap-analysis-jobs.sh
- scripts/parameterized-job.sh
Follow up to https://github.com/openshift/osde2e-common/pull/206
Follow up to https://github.com/openshift/osde2e/pull/2824 and https://github.com/openshift/osde2e-common/commit/0a3a3902b38f64bef745b1ad9a38d03395fb87a3
This PR refactors the logic that we were using for FedRamp's Keycloack to enable ServiceAccount login through OSDe2e. 
This change will be enabled by using the credentials currently stored under /ocm-sd-cicada-sa in vault.
This also bumps the latest osde2e-common dependancies
Added the OCM_CONFIG as part of the viper inits, this also sets the env variable for the container. 
Removed the ProdProvider from the old OCM Provider. The new SA does not support Prod, this is by design.
> SDE-4270 - Update osde2e ocm access to ClientID

- pkg/common/providers/ocmprovider/config.go
- pkg/common/providers/rosaprovider/config.go
This variable is passed from jenkins parameterized job and should be loaded to take effect
https://github.com/openshift/osde2e/blob/173723722a7da39d78f56c58b3272865429ad0aa/scripts/parameterized-job.sh#L19
> Fix: load INSTANCE_TYPE variable as machine type for cluster creation

- .golang-ci.yml
it is `timeout`, not `deadline`
https://golangci-lint.run/usage/configuration/#run-configuration
> fix: bump the golangci-lint timeout

- pkg/common/cluster/clusterutil.go
- pkg/common/config/config.go
- pkg/common/providers/mock/mock.go
- pkg/common/providers/ocmprovider/cluster.go
- pkg/common/providers/rosaprovider/wrapped_calls.go
- pkg/common/spi/provider.go
- pkg/e2e/e2e.go
Cluster hibernation is not used operationally in testing logic. In future, if hibernate and resume functionality is to be tested, test suite should be written for it more specifically.
> Remove cluster hibernate and resume references from osde2e

- pkg/common/helper/helper.go
- pkg/common/load/load.go
- pkg/common/runner/pod.go
- removing GINKGO_NO_COLOR since templating does not accept non-string values at the moment and fails to run job
- also add BAckOffLimit of 0 to runner pods. Rerunning this pod fails anyway for test harness jobs, due to duplicate configmap name in the namesace.
- add passthru secrets for SA into harness ns
> remove boolean env var from test suite pod template

- cmd/osde2e/test/cmd.go
- pkg/common/cluster/clusterutil.go
- pkg/common/clusterproperties/statuses.go
- pkg/common/config/config.go
- pkg/common/providers/ocmprovider/cluster.go
- pkg/e2e/e2e.go
1- rosa classic sts clusters with property "status: reserved" within given region will be candidates
2. only clusters created by "--provision-only" test command are created as candidate "reserved" clusters
3. once claimed, the "reserved" status is removed for good
3. there is no hibernation process, clusters are for one time use only
> SDCICD-1592: allow using "reserved" rosa sts clusters for testing

- pkg/e2e/adhoctestimages/adhoctestimages.go
- pkg/e2e/executor/executor.go
the old runner would create the rest config in the helper from the kubeconfig set by viper - do the same as a short term fix
> pkg/e2e: create executor from kubeconfig if set

- cmd/osde2e/main.go
- cmd/osde2e/provision/cmd.go
- cmd/osde2e/test/cmd.go
- pkg/common/cluster/clusterutil.go
- pkg/common/config/config.go
- pkg/common/providers/ocmprovider/cluster.go
- pkg/e2e/e2e.go
- new command: `osde2e provision --reserve`
- removed `--provision-only` from test command
- moved provision logic from e2e to clusterutil
- reserve count is a const
- one command run creates one cluster, command must be rerun in periodic job
Test jobs will claim clusters with "reserved" label in ready, pending, installing state.
Provision job will count  clusters with "reserved" label in ready, pending, installing state, and create more if they are less than RESERVE count.
> SDCICD-1592 Provision cluster reserve for testing

- configs/e2e-suite.yaml
This PR removes CAD from the e2e suite as it now runs independently.
> Remove CAD from e2e-suite

- pkg/common/config/aws_config.go
- pkg/common/providers/rosaprovider/cluster.go
Hypershift pr check job is failing using base AWS account as the billing account.
The billing account must be an account within the same org, but with HCP contract enabled. It should be the org account on stage.
https://issues.redhat.com/browse/SDCICD-1566
> SDCICD-1566 enable passing a separate billing account for hcp job

- cmd/osde2e/main.go
create a logger at the root of osde2e which can be fetched from the
context with `logr.FromContextOrDiscard`
> cmd/osde2e: set logger in context

- cmd/osde2e/main.go
- pkg/common/providers/ocmprovider/ocm.go
- pkg/common/providers/rosaprovider/rosa.go
- pkg/e2e/e2e.go
- **feat(logging): setup log file earlier**
- **feat(logging): register providers in main**
This ensures we now have a wholistic log file that _should_ contain anything we
log with the current loggers. I needed to move the registration of the
providers to somewhere I could pass context in - the init functions get messy.
> feat(logging): setup logfile early and pass logger around

- pkg/common/cluster/clusterutil.go
to allow more PD jobs to claim ready clusters
This means we'll keep 5 clusters ready on int and stage environments for PD jobs to claim
These are set to expire every 6 hours as new clusters get created
> up the PD reserved cluster count from 2 to 5 

- pkg/common/clusterproperties/properties.go
- pkg/common/clusterproperties/statuses.go
- pkg/common/providers/ocmprovider/cluster.go
- pkg/e2e/e2e.go
the existing property "status" is being used to indicate healthy/completed, which is getting mixed with the reserve/claim labels
> use new cluster property for reserve/claim
