README.md, docs/Writing-Tests.md
This PR provides instructions for developers on how to add additional tests.
Closes #2 
/cc @jeremyeder @jhernand
=> Document writing tests

test/verify/pods.go
=> Require all pods to be running in test

Makefile
Remove configuration to keep around clusters
=> Destroy clusters after testing

test/verify/pods.go
=> Allow Pods 10 minutes to be ready

e2e_test.go, pkg/helper/clientsets.go, pkg/helper/state.go, pkg/testgrid/builds.go, test/state/state.go
This PR:
* Adds helper method to collect defined set of resources from cluster
* Add test suite to call method and write results
* Add new test suite to osde2e
* Modify testgrid package to support gzip data 
Closes #32
=> Report cluster state as part of artifacts

pkg/helper/runner.go, pkg/runner/command.go, pkg/runner/runner.go, test/openshift/config.go, test/openshift/openshift.go, test/state/mustgather.go
This PR:
* modifies the runner to be more generic
* uses modified runner to run `oc adm must-gather` and report results
=> Run must-gather

pkg/runner/command.go, pkg/runner/pod.go, pkg/runner/runner.go, test/state/mustgather.go
Changes the name of the output of "must-gather" from `out.tgz` to `must-gather.tgz`
=> Rename must-gather output

glide.lock, glide.yaml, pkg/osd/osd.go, pkg/osd/versions.go, setup.go
=> Use default version from OSD for clusters

test/state/prometheus.go
=> Collect prometheus data

Makefile, ci/upgrade_events.sh, e2e.go, pkg/config/config.go, pkg/testgrid/artifacts.go, pkg/testgrid/builds.go, pkg/testgrid/latest.go, pkg/testgrid/testgrid.go, pkg/testgrid/testgrid_test.go, setup.go, version.go
=> Event driven builds

pkg/runner/command.go, pkg/runner/git.go, pkg/runner/pod.go, pkg/runner/runner.go, test/scale/nodevertical.go, test/scale/scale.go
This PR:
- modifies the runner to support customizing the PodSpec
- adds an initial implementation of running the NodeVertical scale test
- support cloning a set of repos into runner Pod
=> Infra for scale runner

Dockerfile, Makefile, cmd/osde2e-report/main.go, pkg/report/config.go, pkg/report/markdown.go, pkg/report/markdown_test.go, pkg/report/report.go, pkg/report/runs.go, pkg/testgrid/artifacts.go, pkg/testgrid/builds.go, pkg/testgrid/junit.go, pkg/testgrid/testgrid_test.go
This change adds a tool that:
- Retrieves TestGrid results looking for specific failures
- Creates a MarkDown report
=> Tool which generates reports on failures

pkg/runner/pod.go
This change:
* Fixes race between Project Service Account creation and creating the runner Pod
=> Fix race condition with service account

pkg/runner/git.go, pkg/runner/git_test.go, pkg/runner/pod.go, pkg/runner/runner.go, pkg/runner/runner_test.go, pkg/runner/service.go
This change:
- Allows specifying Git repos to be cloned by runner
- Clones using an InitContainer shared with the runner
- Adds runner integration tests
=> Support for cloning Git repos using Runner

Dockerfile, Makefile, cmd/osde2e-docs/Options.md.tmpl, cmd/osde2e-docs/docs.go, cmd/osde2e-docs/main.go, cmd/osde2e-docs/parse.go, docs/Options.md, pkg/config/config.go, pkg/config/load.go, pkg/config/testgrid.go
Adds a generator that uses Godoc style comments and tags to produce documentation.
=> Generate Docs

test/operators/dedicatedadmin.go
This is a test for expected clusterRoleBindings in the openshift-dedicated-admin operator after initial cluster spin-up.
=> adding clusterRoleBinding tests; formatting

.gitignore
=> ignore VSCode workspace and vi/vim swp files

version.go
=> fixing syntax error in version.go

test/operators/dedicatedadmin.go
- Adds tests and poller for clusterServiceVersion objects
- adds a check for deployment *by name*
- removes verbosity from pollers
- fixes a couple minor syntax errors.
=> Cluster service version

OWNERS
The OWNERS file is necessary for prow integration and has been added.
=> Adding in OWNERS file.

version.go
Addresses [SDAR-39](https://jira.coreos.com/browse/SDAR-39)
=> if upgrade and target are the same, look for the previous version

ci/prow_pr_check.sh, ci/prow_run_tests.sh
Prow test running scripts been introduced. This should allow prow tests to
run without as much custom scripting baked into the prow jobs themselves.
=> SDAR-33. Add prow test runners.

setup.go
Last SDAR-53 PR didn't update the message. Quick fix.
=> Update sleep message

pkg/osd/versions.go
We were previously using the release controller for int versions for
initial cluster provisioning. This is a problem because the versions
produced by the release controller are not necessarily present in OSD as
shown in the release controller. By using OCM directly, we can be
certain that the version is present in OCM before provisioning the
cluster.
=> SDCICD-40. Use OCM directly for int versions.

pkg/osd/versions.go
The cluster versions endpoint will now parse all pages from a cluster
versions endpoint as opposed to just getting the first 100 results.
=> SDCICD-58. Recognize paginated results from cluster versions endpoint.

ci/prow_pr_check.sh, ci/prow_run_tests.sh
The prow scripts will now pipe test output to the REPORT_DIR.
=> SDCICD-62. Pipe output to REPORT_DIR as part of prow scripts

pkg/helper/clusterversionoperator.go, pkg/helper/clusterversionoperator_test.go, pkg/helper/operators.go
I can't spell, and this causes another loop-till-timeout when checking Operators.
=> Fix typo, add one more operator test

pkg/helper/clusterversionoperator.go, pkg/helper/clusterversionoperator_test.go
Again, quick merge to unblock tests.
=> Fix another failed condition

pkg/config/load.go
Addressing comments from @meowfaceman post-merge of #146
=> CICD-73 - Better bool logic

pkg/config/load.go
Bool values are now properly parsed from the environment. Additionally,
config loading errors will now exit the application.
=> SDCICD-81. Config loader now handles 'false' bool values.

ci/prow_run_tests.sh
The prow run scripts can now run different test suites.
=> SDCICD-63. Update prow run script to run different test suites.

test/workloads/guestbook/guestbook.go
Bugfix. With the work done on scale testing we need to change the path of the workloads YAML.
=> SDCICD-50: Change filepath for artifacts

test/operators/curator.go
https://jira.coreos.com/browse/SREP-2457
=> Add e2e tests for operator curator

scripts/README.md, scripts/metrics-sync.sh
This is the preliminary metrics-sync.sh script. This will be used to
verify that the job that runs this script is working properly.
=> SDCICD-95. Preliminary metrics-sync.sh script.

ci/prow_run_tests.sh, cmd/osde2e-docs/main.go, common/e2e.go, docs/Options.md, go.mod, go.sum, pkg/config/config.go, scripts/README.md, scripts/metrics-sync.sh
The metrics will now be uploaded to a configurable S3 bucket.
=> SDCICD-54. Upload metrics to S3 bucket.

suites/e2e/e2e_test.go, suites/scale/scale_test.go, test/operators/operators.go
=> SDCICD-83 - Remove artifact from earlier attempt

pkg/upgrade/upgrade.go
=> SDCICD-111: Fail test run if upgrade times out

common/setup.go
We now get Hive logs after each test.
=> SDCICD-113. Get Hive logs after each test.

test/verify/infranodes.go
* test if infra nodes exist (exactly 2)
* test if following pods are scheduled to infra nodes:
* sre-machine-api-status-exporter
* sre-ebs-iops-reporter
* sre-stuck-ebs-vols
=> Add tests to ensure certain pods appear on infra nodes

ci/prow_pr_check.sh, ci/prow_run_tests.sh, ci/prow_setup.sh
Multiple secret locations are now supported as well as addon secrets.
=> SDCICD-115. Support multiple secrets locations, addon secrets.

Makefile, README.md
Updates README to better reflect project trajectory. Also now allows yaml configs to be used through `make test`
=> SDCICD-112 - Update README and Makefile

pkg/osd/cluster.go
The number of clean runs needed for a cluster has been increased to 10.
Additionally, it's been made a constant for easier managing in the
future.
=> SDCICD-123. Increase clean runs to 10.

README.md, docs/Addons.md
Updates readme and adds docs/Addons.md laying groundwork for the Addon testing guide. 
=> SDCICD-109 - First pass at addon testing doc

scripts/metrics-sync.sh
Stale metrics (greater than 48h old) will now be automatically removed
from the pushgateway.
=> SDCICD-153. Remove stale metrics from the pushgateway.

Makefile, suites/clusterimagesets/middle/imagesets_test.go, suites/clusterimagesets/oldest/imagesets_test.go
The cluster image set tests have not been running as expected. This will
make them function as intended.
=> SDCICD-163. Make cluster image set tests work.

common/version.go
=> SDCICD-169: Don't compare semver if upgrading to a nightly

pkg/e2e/operators/configurealertmanager.go, pkg/e2e/operators/dedicatedadmin.go, pkg/e2e/operators/operators.go
https://issues.redhat.com/browse/OSD-2398
These tests verify that upgrading for configure-alertmanager-operator and rbac-permissions-operator are successful
=> Test upgrades of SRE operators

pkg/e2e/e2e.go
Two bugs have been fixed here:
* The jUnit.xml file will always have the phase written out to it. Due
to the CLI change, the phase was only being written to the XML file if
the tests passed. This has been adjusted for.
* The osde2e CLI will now exit unsuccessfully if the tests have failed.
=> SDCICD-192. Fix osde2e CLI bugs.

scripts/gate-report.sh, scripts/metrics-sync.sh
A gate report script has been added that will wrap gate report
production and S3 uploading into an executable script. This will make
job creation of the gate report easier.
=> SDCICD-173. Gate report script.

scripts/gate-report.sh
Game command is "gate-report" instead of "gate" as it should be.
=> SDCICD-173. Fix gate command.

cmd/osde2e/gate/gate_report.go, cmd/osde2e/gate/gate_report_analysis.go, cmd/osde2e/main.go, cmd/osde2e/test/test.go, pkg/common/report/gate_report.go, pkg/common/report/output.go, pkg/gate/analyze_report.go, pkg/gate/generate_report.go, scripts/gate-report-analysis.sh
A command has been introduced that will analyze gate reports and
pass/fail based on the values in the gate report.
=> SDCICD-174. Introduce gate report analysis command and script.

pkg/gate/generate_report.go
If, when generating a gate report, no versions can be found in
Prometheus, we should fail.
=> SDCICD-195. Fail if no versions can be found for gate report.

scripts/gate-report-analysis.sh, scripts/gate-report.sh
We'll be using the AWS CLI docker container instead of using the AWS CLI
directly to get around permissions issues on prow.
=> SDCICD-174. Use AWS CLI docker container.

pkg/e2e/verify/prom_exporters.go
This test case tests for the presence and operation of the SRE Prometheus Exporters on OSD. Related ticket [OSD-3050](https://issues.redhat.com/browse/OSD-3050).
=> Added tests for SRE Prometheus exporters

scripts/metrics-sync.sh
This reverts commit 0d975b80ee0dfb951ca7553ad5b1e203a8a2cb9f, reversing
changes made to 27d02c0c1e61862de4554653293a2fdbe0fd624d.
=> Revert "Merge pull request #276 from meowfaceman/SDCICD-205"

cmd/osde2e/test/test.go, configs/e2e-suite.yaml, pkg/common/helper/clientsets.go, pkg/common/helper/helper.go, pkg/common/helper/projects.go, pkg/common/load/load.go, pkg/common/runner/git_test.go, pkg/common/runner/runner_test.go, pkg/common/util/util.go, pkg/e2e/osd/privileged.go
1. Expose the RandomStr generator to not be an internal-only method
2. Add Impersonate and AddProject methods to the Helper
3. Added the test itself
=> SDCICD-186: Test privileged container permissions

Makefile, scripts/.gitignore, scripts/gate-report-analysis.sh, scripts/gate-report.sh, scripts/metrics-sync.sh, scripts/shellcheck.sh
shellcheck has been introduced and the various scripts that osde2e uses
have been adjusted for this.
=> Introduce shellcheck.

scripts/metrics-sync.sh
The metrics sync expiration reduction with eliminated exit statement has
now been added.
=> SDCICD-205. Correctly add in metrics-sync expiration reduction.

pkg/e2e/operators/configurealertmanager.go, pkg/e2e/operators/operators.go, pkg/e2e/operators/rbac.go, pkg/e2e/operators/splunkforwarder.go
Looks like the short term fix for SDCICD-210 doesn't work well on prod.
=> Revert SDCICD-210 short term fix.

configs/e2e-suite.yaml, configs/openshift-suite.yaml
=> Remove openshift-extended tests from default e2e runs

pkg/e2e/scale/nodes_and_pods.go, pkg/e2e/scale/performance.go, pkg/e2e/scale/scale.go
You get cluster admin
And you get cluster admin
EVERYONE GETS CLUSTER ADMIN
=> Bugfix: Scale tests should run as cluster-admin

assets/addons/addon-runner.template, pkg/e2e/addons/addon_test_harness.go
Addon tests will now run properly with the helper refactoring work.
=> Fix addon tests.

pkg/common/metadata/metadata.go, pkg/common/phase/phase.go, pkg/e2e/e2e.go
The pass rate for a job is now calculated as a metadata metric.
=> SDCICD-235. Calculate pass rate as metadata metric.

Makefile
ezpz PR. Just adding conformance config.
=> SDCICD-218: Add conformance execution branch

pkg/common/osd/cluster.go
Addresses the error in this rehearsal: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_release/8111/rehearse-8111-periodic-ci-openshift-osde2e-master-e2e-stage-conformance-default/1#1:build-log.txt%3A166
=> SDCICD-228: Specify node amount with multi-az test

pkg/e2e/e2e.go
This reverts commit 2e78bc00910eb8001449a159a60b19d0a352f307, reversing
changes made to 4035e1987082882b9a9790467ab6180ead115353.
=> Revert "Merge pull request #324 from jeefy/SDCICD-229"

pkg/e2e/osd/daemonsets.go, pkg/e2e/osd/privileged.go
This should fix issues with the daemonset and privileged container test run in the upgrade phase.
=> SDCICD-247: Append unique string to object names

pkg/common/helper/pods.go, pkg/common/metadata/metadata.go, pkg/common/osd/cluster.go, pkg/common/osd/healthchecks/certs.go, pkg/common/osd/healthchecks/certs_test.go, pkg/common/osd/healthchecks/clusterversionoperator.go, pkg/common/osd/healthchecks/clusterversionoperator_test.go, pkg/common/osd/healthchecks/nodes.go, pkg/common/osd/healthchecks/nodes_test.go, pkg/common/osd/healthchecks/operators.go, pkg/common/osd/healthchecks/operators_test.go, pkg/common/osd/healthchecks/pods.go, pkg/common/osd/healthchecks/pods_test.go, pkg/e2e/workloads/guestbook/guestbook.go, pkg/e2e/workloads/redmine/redmine.go
Certman cert issuance is now part of osde2e's extended health checks
after cluster provisioning. Additionally, metadata has been added to
track this.
=> SDCICD-257. Add in health check for certman certs.

go.mod, go.sum, pkg/common/osd/cluster.go, pkg/common/osd/healthchecks/certs.go, pkg/common/osd/healthchecks/clusterversionoperator.go, pkg/common/osd/healthchecks/nodes.go, pkg/common/osd/healthchecks/operators.go, pkg/common/osd/healthchecks/pods.go, vendor/github.com/hashicorp/errwrap/LICENSE, vendor/github.com/hashicorp/errwrap/README.md, vendor/github.com/hashicorp/errwrap/errwrap.go, vendor/github.com/hashicorp/errwrap/go.mod, vendor/github.com/hashicorp/go-multierror/.travis.yml, vendor/github.com/hashicorp/go-multierror/LICENSE, vendor/github.com/hashicorp/go-multierror/Makefile, vendor/github.com/hashicorp/go-multierror/README.md, vendor/github.com/hashicorp/go-multierror/append.go, vendor/github.com/hashicorp/go-multierror/flatten.go, vendor/github.com/hashicorp/go-multierror/format.go, vendor/github.com/hashicorp/go-multierror/go.mod, vendor/github.com/hashicorp/go-multierror/go.sum, vendor/github.com/hashicorp/go-multierror/group.go, vendor/github.com/hashicorp/go-multierror/multierror.go, vendor/github.com/hashicorp/go-multierror/prefix.go, vendor/github.com/hashicorp/go-multierror/sort.go, vendor/modules.txt
All health checks are now performed each time when checking for cluster
readiness.
=> SDCICD-257. Perform all health checks each time.

pkg/e2e/openshift/app_builds.go, pkg/e2e/openshift/disruptive.go
Last bit of 187 -- nothing else was glaringly undocumented. 
We could certainly expound on some more, but I'm confident someone with decent fundamentals and an IDE wouldn't get lost.
=> SDCICD-187: More tiny comments

go.mod, go.sum, pkg/common/config/config.go, pkg/common/osd/cluster.go, pkg/common/osd/logs.go, pkg/common/osd/osd.go, pkg/common/osd/quota.go, pkg/common/osd/retryer.go, pkg/common/osd/versions.go, vendor/github.com/adamliesko/retry/.gitignore, vendor/github.com/adamliesko/retry/.travis.yml, vendor/github.com/adamliesko/retry/LICENSE, vendor/github.com/adamliesko/retry/README.md, vendor/github.com/adamliesko/retry/doc.go, vendor/github.com/adamliesko/retry/options.go, vendor/github.com/adamliesko/retry/retry.go, vendor/modules.txt
All interactions with OCM will now go through an exponential retryer in
order to try to whether intermittent errors.
=> SDCICD-271. Add in OCM retryer.

pkg/common/cluster/clusterutil.go
Used != when I should have used == in cluster wait.
=> SDCICD-274. Flip conditional on err in cluster wait.

cmd/osde2e/main.go, cmd/osde2e/query/query.go, pkg/common/config/config.go, pkg/common/prometheus/connect.go, pkg/common/report/generate_report.go
There's now a query subcommand that can be used for querying prometheus
and scripting around it.
=> SDCICD-272. New query subcommand.

pkg/e2e/verify/storage.go
=> SDCICD-282: Check sc.AllowVolumeExpansion to be nil

pkg/e2e/scale/mastervertical.go
MasterVertical projects have been set to 100 for now.
=> SDCICD-191. Set mastervertical projects to 100.

pkg/e2e/verify/routes.go
https://issues.redhat.com/browse/OSD-3432
=> verify console/oauth routes http protocol

docs/Writing-Tests.md
Quick PR to add docs on how to handle static files using pkger
=> SDCICD-318: Add docs on using pkger

pkg/common/providers/ocmprovider/ocm.go
The OCM provider has some utility functions that will be used by
external providers that also consume the OCM provider.
=> SDCICD-281. Introduce utility functions to OCM provider.

Makefile
Just made some small fixes to the Makefile to correct for a missing
space between the word "test" and the arguments for it.
=> Cobra fixes.

pkg/e2e/operators/rbac.go, pkg/e2e/osd/nodelabels.go, pkg/e2e/verify/user_webhook.go
These jobs have been successful for >=1wk, exceptions only being outage/environment related.
=> SDCICD-329: Promote successful informing jobs into blocking

pkg/common/cluster/clusterutil.go
Though this shouldn't happen, we now check if cluster is null and report
on it if it occurs. This should hopefully get us a bit more information
on the segfaults we're seeing while mitigating it.
=> SDCICD-327. Check if cluster is null during cluster wait.

cmd/osde2e/test/cmd.go
Must-gather has been fixed for prow jobs.
=> SDCICD-332. Fix must-gather for prow jobs.

scripts/clean-up-moa.sh
This script will remove velero buckets from the MOA AWS account.
=> SDCICD-337. MOA cleanup script.

scripts/clean-up-moa.sh
The cleanup script shouldn't use docker, as it doesn't really work that
well on prow.
=> SDCICD-337. Don't use docker for the cleanup script.

scripts/clean-up-moa.sh
Add in the exports for the clean up MOA script, because of course it
needs exports.
=> SDCICD-337. Add in exports to clean up MOA script.

go.mod, go.sum
`pkger --include ${pwd}/configs/region-random.yaml -o .`
=> SDCICD-343: Update pkged.go

pkg/common/metadata/metadata.go, pkg/common/metadata/metadata_test.go, pkg/e2e/metrics.go, pkg/e2e/metrics_test.go, pkg/e2e/setup.go
As we're now testing across multiple regions we need to track this in our metadata and metrics :)
=> SDCICD-345: Add region to metadata and metrics

scripts/check-vendor.sh
Allow empty commits so the PR can run against non-in flight code.
=> vendor check fix.

pkg/common/config/config.go, pkg/e2e/e2e.go
Prow job runs will automatically upload metrics by detecting the
existence of a job name.
=> SDCICD-200. Make metrics upload automatic as part for prow runs.

go.mod, go.sum, pkg/common/providers/moaprovider/cluster.go, pkg/common/providers/ocmprovider/cluster.go, vendor/github.com/openshift/moactl/pkg/aws/client.go, vendor/github.com/openshift/moactl/pkg/cluster/cluster.go, vendor/github.com/openshift/moactl/pkg/info/info.go, vendor/github.com/openshift/moactl/pkg/logging/logger.go, vendor/github.com/openshift/moactl/pkg/reporter/reporter.go, vendor/modules.txt
MOA clusters will now have tags. This will allow them to be operated on
by the prod cleaner.
=> SDCICD-347. Tag MOA clusters.

pkg/common/load/load.go
Log-metrics is always loaded at startup now. Additionally, the concept
of a set of default configs has been added to allow for loading a set of
configs that we always expect to be loaded.
=> SDCICD-355. Always load log-metrics at startup.

pkg/common/events/events.go, pkg/common/events/events_test.go
It looks like, when a failure event is triggered, a success event is
also triggered. This will fix that problem, and tests have been added to
cover it.
=> Fix recording both success and failure events on failure.

pkg/common/providers/ocmprovider/cluster.go
Currently metadata isn't capturing the region correctly. This should resolve that.
=> SDCICD-343: Update viper with selected region

go.mod, pkg/e2e/e2e.go
Output is now written to the report directory as well as stdout.
=> SDCICD-359. Redirect output to report directory.

pkg/common/config/config.go, pkg/common/report/generate_report.go, scripts/weather-report-to-slack.sh
The term "whitelist" has been replaced with "allowlist."
=> SDCICD-360. Replace whitelists with allowlists.

go.mod, go.sum, pkg/debug/diff.go
This restores the diff functionality by looking at the job history page of a specific job and returning the second row's ID column.
=> SDCICD-362: Lookup prow id/timestamp correctly

pkg/common/providers/ocmprovider/cluster.go, pkg/e2e/osd/ocm.go
Sometimes it's better to look at something with fresh eyes. And then refactor everything.
This fixes OCM metrics queries into a much simpler test. It also fixes some incorrect tests.
=> SDCICD-334: Update/refactor ocm cluster metric queries

cmd/osde2ectl/get/cmd.go, cmd/osde2ectl/list/cmd.go
Added support for the stage and int environments when using the get cluster info command under osde2ectl and modified print statements for the list clusters feature.
=> Added support for get and list commands of osde2ectl

pkg/e2e/e2e.go
The cluster ID variable being passed into the test runner was empty
because the original copy of the ID was empty at the time of retrieval.
This should move the retrieval of the ID to after where the cluster ID
should have been set.
=> SDCICD-371. Get cluster ID immediately before checking cluster state.

pkg/e2e/e2e.go
If a kubeconfig already exists, skip the provisioning logic in the
BeforeSuite. This should fix upgrades.
=> SDCICD-371. Skip provisioning logic if kubeconfig already exists.

cmd/osde2ectl/create/cmd.go
The batching math for multi-cluster allocation was highly suspect. This
should fix the problem.
=> SDCICD-371. Fix batching for multi-cluster allocation.

pkg/e2e/operators/operators.go
We now check that the installplan specified in a subscription has been deleted before moving on to create a new subscription. 
/assign @meowfaceman 
/cc @njhale
=> SDCICD-389: Update installplan deletion check for operator upgrades

cmd/osde2ectl/create/cmd.go
The panic in batch provisioning has hopefully been fixed for real this
time.
=> SDCICD-395. Fix panic in batch provision, part 2.

pkg/common/cluster/clusterutil.go
Batch cluster allocation panic has been fixed when using longish batch
wait times.
=> Fix batch cluster allocation panic.

cmd/osde2ectl/create/cmd.go
Batch wait will now work as expected and indicate the number of
successful clusters.
=> Fix batch wait.

cmd/osde2ectl/create/cmd.go
Batch wait no longer relies on channels, which were a questionable use
for what I was attempting to do. This should be more stable.
=> Fix batch wait 2.

cmd/osde2ectl/get/cmd.go
Modified get command output to resemble list command output for osde2ectl.
=> Cleaned get command output for osde2ectl

docs/Writing-Tests.md
tl;dr: test.go -> cmd.go 
:tada:
=> SDCICD-374: Update docs post-viper changes

pkg/common/cluster/clusterutil.go, pkg/common/config/log_metrics_test.go
=> SDCICD-398: Change default name from ci-cluster to osde2e

pkg/common/providers/ocmprovider/cluster.go
The cluster list in the OCM provider now supports paginated results.
=> SDCICD-412. Add pagination to OCM provider cluster list.

pkg/e2e/state/alerts.go
We don't want any Expects within an Eventually block. :)
=> SDCICD-409: Remove Expects within Eventually block

pkg/e2e/osd/dedicatedadmin.go
Must have been an artifact from copy/pasta'ing.
=> Bug fix: fix dedicated-admin test name

pkg/e2e/state/alerts.go
=> SDCICD-409: Fix boolean logic for critical alerts

Makefile, pkg/common/providers/moaprovider/cluster.go, pkg/common/providers/ocmprovider/cluster.go, scripts/increase-moa-limits.sh
MOA now supports random regions. Additionally, a script has been added
to increase MOA limits on all regions in AWS.
=> SDCICD-326. Support random regions in MOA.

Dockerfile.osde2e, Dockerfile.osde2ectl, Makefile, ci/build_deploy.sh, scripts/run-sd-scale-test.sh
There is now an osde2ectl specific container for running jobs. The SD
scale test job has been updated to use this container.
=> SDCICD-414. Add in osde2ectl container.

scripts/weather-report-to-slack.sh
Slack report syntax was incorrect.
=> SDCICD-416. Correct slack report syntax.

pkg/common/providers/ocmprovider/logs.go, pkg/e2e/e2e.go
OCM log retrieval has now been restored.
=> OCM log retrieval has been restored.

cmd/osde2ectl/get/cmd.go, cmd/osde2ectl/list/cmd.go, pkg/common/cluster/clusterutil.go, pkg/common/clusterproperties/properties.go, pkg/common/clusterproperties/statuses.go, pkg/common/providers/crc/crc.go, pkg/common/providers/ocmprovider/cluster.go, pkg/common/upgrade/upgrade.go
More properties have been added to clusters, which should allow for more
information to be presented to the user when querying the cluste.
Additionally, these properities should help identify which job the
cluster belongs to.
=> SDCICD-418. Add in more properties.

pkg/e2e/state/alerts.go
Checking cluster alert state is causing grief either not running OR coming back with errors, but there's not enough debugging info.
This removes the Eventually block and will both output additional failure info and also all active alerts when the cluster check occurs.
=> SDCICD-436: Refactor incluster alert check, output all active alerts

pkg/e2e/openshift/app_builds.go, pkg/e2e/openshift/conformance.go, pkg/e2e/openshift/disruptive.go, pkg/e2e/openshift/images.go, pkg/e2e/operators/certman.go, pkg/e2e/operators/configurealertmanager.go, pkg/e2e/operators/managedvelero.go, pkg/e2e/operators/prunejob.go, pkg/e2e/operators/rbac.go, pkg/e2e/operators/splunkforwarder.go, pkg/e2e/osd/daemonsets.go, pkg/e2e/osd/dedicatedadmin.go, pkg/e2e/osd/machinehealthcheck.go, pkg/e2e/osd/nodelabels.go, pkg/e2e/osd/ocm.go, pkg/e2e/osd/privileged.go, pkg/e2e/scale/mastervertical.go, pkg/e2e/scale/nodes_and_pods.go, pkg/e2e/scale/performance.go, pkg/e2e/state/alerts.go, pkg/e2e/verify/imagestreams.go, pkg/e2e/verify/namespace_webhook.go, pkg/e2e/verify/pods.go, pkg/e2e/verify/prom_exporters.go, pkg/e2e/verify/routes.go, pkg/e2e/verify/storage.go, pkg/e2e/verify/user_webhook.go, pkg/e2e/verify/validation_webhook.go, pkg/e2e/workloads/guestbook/guestbook.go, pkg/e2e/workloads/redmine/redmine.go
Slack channels expect the # symbol in front of them. This have been
added.
=> Add # in front of slack channels.

pkg/e2e/verify/user_webhook.go
We disable this in https://github.com/openshift/osde2e/pull/477, and now we have a [workaround](https://bugzilla.redhat.com/show_bug.cgi?id=1855500#c5) for this.
=> Add back user webhook test

pkg/common/cluster/clusterutil.go
Cluster readiness would fail when it encountered an error pinging OCM rather than continuing the loop. This now logs the errors and lets the polling proceed.
=> SDCICD-453: Clean up returns in cluster readiness check

pkg/e2e/osd/inhibitions.go
=> OSD-4616 inhibit KubeDeploymentReplicasMismatch

pkg/e2e/verify/namespace_webhook.go
This ensures that `updatedNamespace` doesn't complete until the change to a namespace object has been reflected in the API. If the namespace change hasn't been reflected within 2min, it should timeout (and thus error the job)
=> SDCICD-440: Force updateNamespace to wait for changes to occur

pkg/e2e/verify/identity_webhook.go, pkg/e2e/verify/user_webhook.go
=> Refactor user_webhook.go and add identity_webhook.go to test identity

pkg/e2e/operators/cloudingress/apischeme_cr.go, pkg/e2e/operators/cloudingress/cloudingress.go, pkg/e2e/operators/cloudingress/installed.go, pkg/e2e/operators/cloudingress/public_private.go, pkg/e2e/operators/cloudingress/rhapi_endpoint.go
the individual test files will be filled out by:
* https://issues.redhat.com/browse/OSD-5334 (installation verification)
* https://issues.redhat.com/browse/OSD-5335 (APIScheme CR verification)
* https://issues.redhat.com/browse/OSD-5336 (rh-api endpoint management verification)
* https://issues.redhat.com/browse/OSD-5337 (public/private management verification)
=> create package and skeleton tests for cloud-ingress-operator

pkg/e2e/operators/cloudingress/cloudingress.go, pkg/e2e/operators/cloudingress/installed.go
In this test we do a basic check on the cloud-ingress-operator deployment, verify that it is deployed with the correct number of replicas.
=> Test to check that the cloud ingress operator is installed.

pkg/common/upgrade/managed.go
The `managed-upgrade` Pod Disruption Budget timeout of 15 minutes (being enforced by OCM and implemented in #609) is causing worker node upgrades to take a long time (over an hour) and seems to be making cluster upgrades take too long in E2E testing.
This PR introduces an override for the Pod Disruption Budget that takes place during the periodic 'is cluster upgraded' checks. If the value is already overridden, no action is performed.
=> Minimise managed worker upgrade wait times

pkg/e2e/operators/cloudingress/rhapi_endpoint.go
https://issues.redhat.com/browse/OSD-5902
=> OSD-5902 add sleep for rhapi_endpoint

pkg/e2e/osd/machinehealthcheck.go
fixes [OHSS-2175](https://issues.redhat.com/browse/OHSS-2175)
=> Explicitly check for only SREP MHCs

OWNERS
Remove Mike, add Christoph.
My team has been working on tests, and we want to continue over the recharge break. I promise not to break anything.
=> Update osde2e owners

pkg/common/providers/ocmprovider/cluster.go, pkg/e2e/e2e.go
Credentials calls 157 -> 1
Logging Calls 1497 -> 45
Seems good right? :)
=> SDCICD-571: Reduce credentials and logging calls to OCM

pkg/e2e/addons/addon_test_harness.go
This adds the URL of the CI log output view to the slack notifications generated by failing addon tests.
=> generate job URLs in slack notifications for addons

pkg/common/cluster/healthchecks/machines.go
Change the machines healthcheck to:
- Explicitly specify the `openshift-machines-api` namespace.
- Fail if zero results are returned from the `List` operation.
=> healthcheck/machines: Specify namespace, check empty list

pkg/common/config/config.go
=> configure loading slack token from secret file

configs/before-suite-metrics.yaml, pkg/common/config/log_metrics.go
Added more before suite errors into the config file to be filtered into junit results.
=> Before Suite Errors into Junit Results

pkg/common/providers/ocmprovider/cluster.go
=> fix: properly return randomly chosen region

go.sum, pkg/common/helper/clientsets.go, pkg/e2e/verify/sccs.go
In this commit, I added a test that creates a new permissive Scc and then restarts the Prometheus and ssh pods. Next, the test verifies that the new pods came up as expected. This test was created to verify the fix for Bug 1868976 https://bugzilla.redhat.com/show_bug.cgi?id=1868976
=> Scc test to verify new Scc does not break pods

pkg/common/clusterproperties/statuses.go, pkg/e2e/e2e.go
=> feat: mark clusters as completed after CI finishes

pkg/e2e/addons/addon_test_harness.go
=> fix: ensure we log addon test slack notification errors

pkg/common/helper/clientsets.go, pkg/e2e/verify/hiveownership_webhook.go
Covers: https://issues.redhat.com/browse/OSD-6180
Ref: https://github.com/openshift/managed-cluster-config/pull/626
https://github.com/openshift/managed-cluster-validating-webhooks/pull/131
=> conditions on OSD-6180, covers hiveownership webhook cases

pkg/e2e/verify/hiveownership_webhook.go
refactor to use existing util random funcs.
=> refactor: hiveownership hook tests: remove unnecessary random logic

pkg/common/versions/version_setup.go, pkg/e2e/version.go
Should also re-address SDCICD-574
=> SDCICD-583: set channel to nightly when we know it's meant to be nightly

pkg/e2e/verify/hiveownership_webhook.go
+ convert this suite to _informing_ mode till MCC changes get promoted to production
=> refactor: osd-6180 reflect mcc tests

pkg/e2e/routemonitors/routemonitors.go
This PR adds all routes in openshift-monitoring namespace to the vegeta
implementation.
=> SDCICD-593 Add openshift-monitoring routes to e2e

pkg/e2e/e2e.go
This allows addon authors the ability to use/specify a Kubeconfig externally and test against any valid openshift cluster while using the `mock` provider. This isn't an ideal solution and, in the future, we need to create a "local" provider that expects a Kubeconfig and lets us remove all these conditional statements within the main e2e code. :)
=> SDCICD-591: skip certain cluster checks in e2e when using the mock provider

pkg/common/providers/ocmprovider/cluster.go
If a region is set to random, attempt to look up the opted-in regions available for the cloud provider.
If the credentials aren't set, default to a sane/typical region. 
If not random, fall through.
=> Fix: use cloud credentials to look up random regions

pkg/e2e/addons/addon_test_harness.go
=> feat: only notify of failing addon harnesses

pkg/e2e/osd/dedicatedadmin.go
[OSD-6477](https://issues.redhat.com/browse/OSD-6477)
verify dedicated-admins can manage secrets in selected namespaces
verify dedicated-admins can manage subscription in selected namespaces
To verify other namespaces in the future, add desired namespace to namespaceList
=> Verify dedicated-admin Secrets and Subscription permissions

Dockerfile.osde2e, Dockerfile.osde2ectl
=> feat: update GOFLAGS and go version for nonvendored build

pkg/common/pagerduty/pagerduty.go, pkg/e2e/e2e.go
=> feat: create PD alerts per test case failure

pkg/e2e/e2e.go
=> feat: provide richer metadata in cluster details

docs/Addons.md
=> docs: update addon testing onboarding documentation

pkg/e2e/state/alerts.go
=> fix: actually report error on attempted prometheus connection

pkg/e2e/verify/storage.go
In this commit, per [OSD-6467](https://issues.redhat.com/browse/OSD-6467), I added a test that lists all available storage classes on the cluster,  and then for each storage class creates a pod with a volume of that class attached. The test also creates a file in the volume to verify that it was attached correctly.
=> PV test/ OSD-6467

pkg/common/providers/ocmprovider/cluster_image_sources.go
This adds "ecr-primary" as a test case and changes "standard" to be "quay-primary"
=> SDCICD-459: Add fourth test case for icsp's

go.sum, pkg/common/config/config.go, pkg/common/pagerduty/pagerduty.go, pkg/e2e/e2e.go
=> feat: merge PD incidents automatically

pkg/e2e/verify/samesite_cookie.go
Baked in informing for a few days and tests are all green.
=> promoting to e2e

pkg/common/cluster/healthchecks/healthcheckjob.go
=> fix: avoid api server restart race that failed healthcheck

go.mod, pkg/e2e/e2e.go
Instead of re-implementing multiwriter, we should just use multiwriter. :)
=> SDCICD-637: Simplify build log output

pkg/common/providers/ocmprovider/cluster_image_sources.go
=> fix: use org namespace in icsp config

go.sum, pkg/common/helper/utilities.go, pkg/e2e/verify/pod_webhook.go
In this commit, I added tests to verify that the validation-webhook daemon set and service are running.
=> OSD-6594 [ Added test to verify validation-webhook service is running.]

go.sum, pkg/e2e/osd/ocm.go
=> feat: add test to check for icsp mirror functionality

pkg/common/config/config.go, pkg/common/providers/ocmprovider/cluster.go
=> feat: support ovn as a network provider

pkg/e2e/osd/ocm.go
=> fix: ensure quay test doesn't panic due to length

pkg/common/pagerduty/pagerduty.go, pkg/e2e/e2e.go
=> feat: auto-resolve pd incidents with no alerts within 30 hours

pkg/e2e/state/prometheus.go, pkg/e2e/verify/sccs.go
Added a check to ensure prometheus pods are up and running before executing extraction of prometheus data within the "collect-prometheus" pod
=> Added prometheus pod check for collect prometheus pod

pkg/e2e/verify/user-workload-monitoring.go, pkg/e2e/verify/user_webhook.go
Fixes [SDCICD-610](https://issues.redhat.com/browse/SDCICD-610)
=> fix: prevent race in user-workload-monitoring tests

pkg/e2e/osd/dedicatedadmin.go
In [OSD-7026](https://issues.redhat.com/browse/OSD-7026) the CI-Watcher identified a case where the `dedicated-admin permissions` test was irregularly failing. [0]
This test failure is the result of the `subscription` resource (retrieved early in the test) having being updated to a new `resourceVersion` before the test later attempts to perform an `Update` on it. Because the resource version on-cluster is newer than the version loaded into memory, the `Update()` request is rejected, failing the test.
This situation is easily handled through the use of the `RetryOnConflict` k8s helper. 
Previous to this PR change, I was able to replicate the test failure every few test runs. Since the proposed fix I have not been able to recreate the failure.
[0] …
=> OSD-7026 make dedicated-admin tests more robust

pkg/common/helper/state.go
=> Capture machine CR as part of e2e runs

pkg/e2e/routemonitors/routemonitors.go
This PR prevents the panic demonstrated in the below CI run by restructuring the logic some. It also renames a few variables to make them more idiomatic.
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/osde2e-stage-aws-e2e-upgrade-to-latest/1387436651533307904#1:build-log.txt%3A4304
=> fix: prevent index-out-of-range panic in routemonitor

pkg/e2e/operators/osdmetricsexporter.go
Both the `Service` object the HTTP endpoint are available only after the operator pod is running. So even though the CSV is present the endpoint and the service may be unavailable.
=> Poll the osd-metrics-exporter endpoint

pkg/e2e/operators/operators.go
Refactored the `checkClusterServiceVersion` function to use `gomega`'s `Eventually` helper. Also ensure that the CSV in the `Succeeded` state before proceeding.
=> Refactor the check CSV function to ensure succeeded state as well

Makefile
As a demonstration, the first CI run for this should fail, as the operators package has started directly importing viper. I'll push a fix after prow points this out for me.
=> feat: enforce the use of concurrentviper in CI

Makefile, pkg/e2e/operators/osdmetricsexporter.go
=> fix: fail make target if vipercheck fails

pkg/common/helper/clientsets.go, pkg/common/helper/helper.go, pkg/common/util/versionutil.go, pkg/e2e/verify/oauth_tokens.go
Tests for the presence of timeout values in the global oauth token config, and tests whether inactivity timeouts are working for oauthaccesstokens
Some of these tests are expected to fail until https://github.com/openshift/managed-cluster-config/pull/766 is in prod
=> OAuth token timeout tests

pkg/common/providers/rosaprovider/cluster.go
=> feat: allow upgrade testing for ROSA

pkg/common/util/versionutil.go, pkg/e2e/verify/oauth_tokens.go
=> feat: create ginkgo helper to skip by version

pkg/common/util/versionutil.go
=> fix: do not check version until running test

pkg/common/pagerduty/pagerduty.go
=> feat: consolidate pd alerts regardless of build phase

go.mod, go.sum, pkg/e2e/operators/customdomains.go
Adds test described at https://github.com/openshift/custom-domains-operator/blob/master/TESTING.md#live-testing to ensure custom domains operator is functioning as intended.
=> OSD-6949 - Add test for custom domains operator.

go.mod, go.sum, pkg/common/clusterproperties/statuses.go, pkg/common/config/config.go, pkg/common/providers/crc/crc.go, pkg/common/providers/mock/mock.go, pkg/common/providers/ocmprovider/cluster.go, pkg/common/spi/cluster.go, pkg/e2e/e2e.go
[SDCICD-666](https://issues.redhat.com/browse/SDCICD-666) (Cursed)
[SDCICD-667](https://issues.redhat.com/browse/SDCICD-667)
=> Hibernation improvements

pkg/e2e/state/prometheus.go, pkg/e2e/verify/sccs.go
=> Actually wait for prometheus to be restarted in SCC test

pkg/common/providers/rosaprovider/cluster.go
Retrieve and merge stable channel versions with other specified channel version list
=> SDCICD-669: Fix ROSA version selection with other channels

go.mod, go.sum, pkg/common/config/config.go, pkg/db/db_helpers.go, pkg/db/generate.go, pkg/db/migrations/002_testcase.up.sql, pkg/db/models.go, pkg/db/queries.sql.go, pkg/db/queries/queries.sql, pkg/db/sqlc.yaml, pkg/e2e/e2e.go
I have verified that this does actually store data inside of the db. Please make any tweaks you'd like and merge as soon as is reasonable.
=> Store test data

pkg/e2e/operators/customdomains.go
Addresses https://issues.redhat.com/browse/OSD-7231
When recreating the issue, the majority of errors I encountered appeared to stem from the customdomain's `.status.endpoint` "flapping" on startup. 
To better handle cases where the endpoint may resolve for only short periods of time on initialization, I modified the `wait.PollImmediate` loop that checks the endpoint's readiness to wait for a minimum number of consecutive successful resolves over the span of a few minutes. If any of the attempts fail, the counter restarts. 
In my opinion, if the endpoint fails to resolve beyond this loop, it likely indicates an issue with the customdomains operator or the underlying infrastructure which should be examined further; therefore I explicitly opted *not* to handle this case in later loops.
=> OSD-7231 - Make "Custom Domains Operator Should be resolvable by external services" test more robust

pkg/common/cluster/clusterutil.go, pkg/common/cluster/healthchecks/replicas.go, pkg/common/cluster/healthchecks/replicas_test.go
add the ds rs replica count check as part of the cluster health check
the managed upgrade will also be able to consume this
=> add ds/rs check for cluster health check

assets/upgrades/config.template
Fixing #855 to move ignore projects under healthcheck.
cc @mrbarge
=> Fixing #855 to ignore namespaces

pkg/common/cluster/healthchecks/replicas.go
This PR improves the output of the `daemonset` and `replicaset` health checks (introduced in #842) so that they now report a full list of what daemonsets and replicasets aren't satisfied.
Example output below:
```
2021/06/13 19:07:02 Error in PollClusterHealth: 3 errors occurred:                    
* Pending pod key-value entries still present in the pending pod counter map   
* replicaset splunk-forwarder-operator-86b954c66 has 0 out of 1 replicas ready 
* replicaset managed-velero-operator-98cd86bf has 0 out of 1 replicas ready
```
=> Improve output of replicaset and daemonset health checks

pkg/common/cluster/healthchecks/replicas.go
The saga of #842 continues. Since adding the additional logging in #859 I can see that the replicaset / daemonset health check fails post-upgrade because of a E2E test that leaves a daemonset in a deliberately bad state, so none of our cluster upgrades complete a health check.
This PR fixes that issue by ignoring the contents of the OSDE2E-created namespace for the replicaset/daemonset checks.
=> Ignore OSDE2E NS in replica health check

pkg/db/models.go, pkg/db/queries.sql.go, pkg/db/sqlc.yaml
=> fix: use proper column type even when nullable

pkg/e2e/e2e.go
=> feat: circuit-break builds with many failures to create special alerts

pkg/db/queries.sql.go, pkg/db/queries/queries.sql
=> fix: filter alertable tests to failing ones

cmd/ci-watcher-report/README.md, cmd/ci-watcher-report/main.go, go.mod, go.sum
=> feat: add simple reporting tool for ci-watchers

pkg/common/pagerduty/pagerduty.go, pkg/e2e/e2e.go
=> feat: use eventually-consistent pd incident merge strategy

pkg/db/README.md, pkg/db/db_helpers_test.go
=> Document the database package development flow

pkg/e2e/operators/customdomains.go
Increase DNS timeouts, break apart timeouts per operation, and improve maintainability.
https://issues.redhat.com/browse/OSD-7472
=> Stabilize CDO Test

README.md
=> docs: add README segment on the results db

pkg/common/concurrentviper/generated.go, pkg/db/db_helpers_test.go, pkg/db/migrations/003_add_upgrade_version.down.sql, pkg/db/migrations/003_add_upgrade_version.up.sql, pkg/db/models.go, pkg/db/queries.sql.go, pkg/db/queries/queries.sql, pkg/e2e/e2e.go
We need to track the upgrade version for jobs within the database.
=> fix: track upgrade versions within job database

pkg/e2e/osd/inhibitions.go
This fixes a test that has started breaking ever since the default SRE IDP has been removed from OSD clusters. It did not nicely handle the possibility that no identity providers could exist, and that's not really something do-able in a jsonpatch.
The test will now handle zero or more identity providers already configured and safely cleaning up afterwards.
=> Make AlertManager Inhibition test handle zero or more preconfigured IDPs

pkg/common/helper/helper.go, pkg/e2e/e2e.go, pkg/e2e/operators/customdomains.go, pkg/e2e/operators/managedupgrade.go, pkg/e2e/verify/oauth_tokens.go
This should clear up beforeSuite issues and insodoing also clear up the noisy stack traces within the logs.
=> SDCICD-489: refactor helper setup, remove stacktraces

pkg/e2e/operators/cloudingress/secondary_router.go
similarly to the remove, we need to wait for the reconcile right after updating the PublishingStrategy
=> fix for secondary_router test

pkg/e2e/operators/customdomains.go
Handle URL Error and DNS Error "no such host" during HTTP response test phase and adjust timeouts.
https://issues.redhat.com/browse/OSD-7472
=> Custom Domains: Handle DNS Errors During HTTP Response And Adjust Timeouts

pkg/e2e/osd/rebalance_infra_nodes.go, scripts/imbalance-infra-nodes.sh
This aims to test the rebalance cronjob. It includes:
1. Put the infra workloads to an imbalanced state
2. Run the job from cronjob to rebalance the cluster
3. Verify the infra nodes are rebalanced
Signed-off-by: Jing Zhang <jingzhan@redhat.com>
=> [OSD-7445] Added tests for the rebalance cronjob

pkg/e2e/verify/sccs.go
sshd will be removed, the tests I removed already covered by the upper monitoring pods tests in line 64
=> [OSD-8410]Update SCC test

pkg/e2e/verify/namespace_webhook.go
This adds the non-privileged namespace setup and tests back to the webhook namespace suite.
=> Add Non-Privileged Namespace Setup Back

pkg/e2e/operators/managedupgrade.go
Setting team ownership for MUO tests.
=> OSD-9330 muo owner update to team

pkg/e2e/operators/managedvelero.go
Setting team ownership for MVO tests.
=> OSD-9335 MVO owners update

pkg/e2e/operators/routemonitor.go
=> OSD-9339 updating orange ownership

pkg/e2e/operators/certman.go
This updates team ownership for certman-operator tests.
=> OSD-9331 certman-operator update owner

pkg/e2e/operators/customdomains.go
Setting team ownership for the CDO operator
=> OSD-9334 update CDO owners

pkg/common/cluster/healthchecks/operators.go, pkg/common/cluster/healthchecks/operators_test.go
=> Simplify operator healthchecks

cmd/osde2e/test/cmd.go, configs/pr-check.yaml, pkg/common/cluster/pr_check_queue.go, pkg/common/clusterproperties/properties.go, pkg/common/config/config.go, pkg/e2e/e2e.go, pkg/e2e/verify/pr_check_queue.go
Implemented config 'pr-check' which will allow a multiple osde2e prcheck jobs to not run on the same cluster
=> Pr-Check psudo queue

configs/dummy-suite.yaml, pkg/common/constants/constants.go
this only adds the suite
the way to use is to add 'dummy-suite' to your --config (instead of e2e or such)
and then add the SuiteDummy to the SuiteName
=> feat(local-testing): adds suite

pkg/e2e/osd/inhibitions.go
I noticed the AlertmanagerInhibitions test can start to perma-fail if a previous run of the test leaves behind the bad IDP it creates.
This most notably becomes a problem on the PR Check cluster where, if the bad IDP is ever left behind, every subsequent `osde2e` run will fail (as it currently is).
The test will now remove the bad IDP prior to running the test if it already exists.
A good test that this will work is if the PR check for this PR succeeds :)
=> Make AlertmanagerInhibitions test more robust

pkg/common/cluster/healthchecks/pods.go, pkg/common/cluster/healthchecks/pods_test.go
> As an SRE Platform on-call engineer, I do not want to receive alerts the `osd-cluster-ready` job for components that have had a successful retry or follow up.  The cluster ready job currently fails if an installer pod is listed in an Error state, despite retries succeeding.
osde2e tests should now account for installer pod retries. If the pod has no associated cronJob, it should check the Phase and return an error if needed.
I have tested the code in scenarios of the absence of a label, different labels/namespaces/states of pods, and combinations. If you see something that I have missed, please let me know.
=> OSD-8402 bug(pods.go): account for installer pod retries

pkg/e2e/verify/regularuser_webhook.go
Added explicit 150s timeout, removed some unused imports.
=> [OSD-9851] Updating regularuser_webhook osde2e timeout

pkg/common/providers/ocmprovider/cluster.go
The changes made in https://github.com/openshift/osde2e/commit/bbd8ba71866ce6298c210e9dba17de9a34417f61 caused an issue with other pipelines that don't define a vpc, added an else statement to run the old logic if the variable isn't defined.
=> Reverting a change that was made for ODF.

pkg/common/cluster/clusterutil.go, pkg/common/providers/ocmprovider/cluster.go, pkg/common/providers/rosaprovider/cluster.go, pkg/common/versions/version_selector.go, pkg/e2e/e2e.go
Added some comments to find areas to refactor later.
=> Housekeeping

pkg/e2e/operators/customdomains.go
Tests changes made for https://issues.redhat.com/browse/OSD-7562
---
Adds test to verify CustomDomain certificates can be replaced. Adds better logging to the test.
=> Adds test to verify certificate replacement

pkg/common/providers/rosaprovider/cluster.go
The rosaprovider code included the ability to make use of OVNKubernetes
by hacking the install-config.  rosa now accepts a `--network-type`
command line option to do this, so osde2e should make use of it.
Details on the new option can be found in the original PR to rosa:
https://github.com/openshift/rosa/pull/559
=> rosaprovider: Use new --network-type option

pkg/common/helper/helper.go
Also add more info on error description.
Signed-off-by: Alfonso Martínez <almartin@redhat.com>
=> helper: avoid test panic on CreateProject method

cmd/ci-watcher-report/main.go, go.mod, go.sum, pkg/common/pagerduty/pagerduty.go, pkg/e2e/e2e.go
Code changes needed to update go-pagerduty dependency
/assign @MrSantamaria
=> Update go-pagerduty dependency

pkg/e2e/proxy/postinstall.go
To close [OSD-11101](https://issues.redhat.com//browse/OSD-11101)
Tested locally with following
```
osde2e test --configs proxy-suite --kube-config $KUBECONFIG -e stage --skip-health-check
```
It will run the adding proxy firstly, and then run the removing proxy. Both succeeded.
=> [OSD-11101] add testing for remove proxy

pkg/e2e/verify/pods.go
This will reduce the failures of `Pods should not be Failed` test as we will ignore failed installer pods that are owned by revision-status configmaps.
=> Ignore failed pods that are owned by revision status

README.md
added one liner to run quick focus test files
=> adding skips for focus test

pkg/common/prometheus/connect.go
k8s 1.24 / OCP 4.11 introduces a change [0] which means that the `prometheus-k8s` ServiceAccount can no longer be used to look up the account token. As osde2e uses this method to fetch a token for talking to Prometheus, this will stop working when run on new 4.11 clusters.
This PR changes the method to just look for and use the `prometheus-k8s-token` Secret in `openshift-monitoring`, which will still be present.
[0] https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#urgent-upgrade-notes
=> Pull Prometheus token from Secret

pkg/e2e/verify/user-workload-monitoring.go
I added an if statement to check if user-workload-monitoring configmap is already in place to accommodate the changes in v.4.11
=> [OSD-12720] Update e2e test for user-workload-monitoring to account for default configmap

pkg/e2e/osd/machinehealthcheck.go
This PR removes the MachineHealthCheck test that tests node replacement, as it is broken.
The quest to remove flaky tests continues. The `should replace unhealthy nodes` fails regularly enough for me to look closely at it. It suffers from a number of problems that essentially requires a full rewrite, and it can't possibly have ever worked in the first place.
- the `Patch` return error is ignored. It's actually never worked. 
- this is because the JSON Merge patch is syntactically invalid (you can't patch an individual array element with JSON Merge, it's the whole array or nothing). And it should be passed a string, not a int.
- but even if all that is fixed, the runner pod doesn't do what it's supposed to (it's not a debug pod, there is no `/host` for it to chroot to)
- and lastly …
=> Remove MHC node replacement test

pkg/common/providers/rosaprovider/cluster.go, pkg/common/providers/rosaprovider/wrapped_calls.go
Handle deleting the additional STS resources created (operator-roles and oidc-providers) after the cluster has been deleted
depends on #1341
=> rosaprovider: delete additional sts resources

OWNERS
=> add jbpratt to reviewers/approvers

go.mod, pkg/common/runner/service.go
=> fix common/runner importing random log package

pkg/e2e/verify/prom_exporters.go
both `osd-managed-prometheus-exporter-stuck-ebs-vols` and `osd-managed-prometheus-exporter-ebs-iops-reporter` are disallowed on STS clusters according to the SSSs below
https://github.com/openshift/managed-prometheus-exporter-stuck-ebs-vols/blob/4e3513d71622f821020043639aadea25fa5879a6/hack/00-osd-managed-prometheus-exporter-stuck-ebs-vols.selectorsyncset.yaml.tmpl#L19
https://github.com/openshift/managed-prometheus-exporter-ebs-iops-reporter/blob/6aca1edab4bc0e6bee19743fb48203c97348dd91/hack/00-osd-managed-prometheus-exporter-ebs-iops-reporter.selectorsyncset.yaml.tmpl#L19
=> e2e/verify/prom_exporters: skip on STS

go.mod, go.sum, pkg/common/cluster/healthchecks/machines.go
We were using the wrong api here and it was causing additional deps to be imported that we didn't need
=> Use proper machine api

pkg/common/helper/helper.go
this cuts test runs down by 40 seconds in most cases
=> poll for rolebinding rather than sleep

go.mod, go.sum
go get github.com/onsi/ginkgo/v2/ginkgo@v2.5.1
=> misc: bump ginkgo (v2.3.1 -> v2.5.1)

pkg/e2e/operators/prunejob.go
While running the operator tests, the prune job tests were throwing warning messages about the batch/v1beta1 API being deprecated in kubernetes v1.25+. Fixes the tests to use batch/v1 API.
In addition, it also fixes the warning message about child pods being preserved by default. Now when the cron job resource is deleted, it will clean up any child pods associated to it.
Triggered by: [SDCICD-852](https://issues.redhat.com//browse/SDCICD-852)
*Original Behavior*
```
Will run 2 of 125 specs
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
W1202 12:31:21.767370 1020840 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
2022/12/02 12:31:21 Waiting 8h19m59.967851729s for deployments-pruner-sc5nw job to …
```
=> Fix the prune job tests to use batch/v1 api for cronjob config

pkg/e2e/verify/namespace_webhook.go
This PR is for prometheusrule webhook validation in managed namespaces. 
It will close [OSD-13302](https://issues.redhat.com/browse/OSD-13302)
=> Adds test for prometheusrule webhook in managed namespaces

pkg/e2e/operators/cloudingress/certificate.go, pkg/e2e/operators/cloudingress/deletetapps2.go, pkg/e2e/operators/cloudingress/dnsname.go, pkg/e2e/operators/cloudingress/public_private.go, pkg/e2e/operators/cloudingress/routeSelector.go, pkg/e2e/operators/cloudingress/secondary_router.go, pkg/e2e/operators/cloudingress/upgrade.go, pkg/e2e/operators/dvo.go, pkg/e2e/operators/managedupgrade.go, pkg/e2e/operators/ocmagent.go, pkg/e2e/operators/routemonitor.go, pkg/e2e/operators/splunkforwarder.go, pkg/e2e/osd/dedicatedadmin.go, pkg/e2e/osd/olm.go, pkg/e2e/osd/rebalance_infra_nodes.go, pkg/e2e/verify/check_workloads.go, pkg/e2e/verify/loadbalancers.go, pkg/e2e/verify/user-workload-monitoring.go
For [SDCICD-870](https://issues.redhat.com/browse/SDCICD-870)
=> Add informing label to existing informing test cases

pkg/common/config/config.go, pkg/common/providers/rosaprovider/cluster.go, pkg/e2e/e2e.go
https://issues.redhat.com/browse/SDCICD-881
Updates: 
1. Switched the default Channel to Stable
2. Removed pruning/appending channel name logic from the version. 
3. Modified the log print for the version to include the used channel.
=> OSDe2e Versions - Updates to version Picker

pkg/common/cluster/clusterutil.go
wait for the nodes to match what is found in ocm
```
...
2023/01/13 11:14:27 cluster.go:399: created OCM client
2023/01/13 11:14:28 events.go:30: Success event: InstallSuccessful
2023/01/13 11:14:28 e2e.go:94: CLUSTER_ID set to 217k5frcnghcvm1anhq4ulmid4v2h8ik from OCM.
2023/01/13 11:14:28 e2e.go:102: CLUSTER_NAME set to autumn1 from OCM.
2023/01/13 11:14:28 e2e.go:105: CLUSTER_VERSION set to openshift-v4.12.0-rc.8-candidate from OCM, for channel group candidate
2023/01/13 11:14:28 e2e.go:108: CLOUD_PROVIDER_ID set to aws from OCM.
2023/01/13 11:14:28 e2e.go:111: CLOUD_PROVIDER_REGION set to us-east-1 from OCM.
2023/01/13 11:14:28 cluster.go:1288: Successfully added property[UpgradeVersion] -
2023/01/13 11:14:28 clusterutil.go:100: Waiting 30 …
```
=> common/cluster: perform ready healthcheck for rosa hypershift

pkg/e2e/osd/daemonsets.go
HyperShift only has worker nodes available so we need to skip the infra role test.
This change refactors the test to use the e2e-framework and fixes the behavior to properly schedule onto the correct node based on label. Based on the documentation[1], `nodeSelector.role: worker` should allow for scheduling a daemonset onto only worker nodes, but the node does not actually have a `role: "worker"` label so nothing gets scheduled.
Taking a look at the node labels, there is the standard kubernetes role label but not the simple `role` label:
```
$ oc get nodes ip-10-0-224-45.ec2.internal -o json | jq .metadata.labels
{
"beta.kubernetes.io/arch": "amd64",
"beta.kubernetes.io/instance-type": "m5.xlarge",
"beta.kubernetes.io/os": "linux",
"failure-domain.beta.kubernetes.io/region": "us-east-1", …
```
=> SDCICD-889: e2e/osd: enable daemonsets on hypershift

pkg/e2e/verify/routes.go
the GET request is always going to fail if the deployment is not ready yet
```
...
2023/01/16 11:15:00 helper.go:139: Setting project name to osde2e-w6zf7
2023/01/16 11:15:00 helper.go:139: Setting project name to osde2e-w6zf7
2023/01/16 11:15:00 helper.go:139: Setting project name to osde2e-w6zf7
[1673888426] OSD e2e suite - 10/236 specs SSSSSSSSSSSSSSSSSSSSSSSSSSSS2023/01/16 11:15:00 helper.go:139: Setting project name to osde2e-w6zf7
•SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS2023/01/16 11:15:11 helper.go:139: Setting project name to osde2e-w6zf7
••SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS2023/01/16 11:15:22 helper.go:139: Setting project name to osde2e-w6zf7
••SSSSSSSSSSS2023/01/16 11:16:03 …
```
=> e2e/verify/routes: wait for respective deployment

pkg/e2e/operators/certman.go, pkg/e2e/operators/configurealertmanager.go, pkg/e2e/operators/customdomains.go, pkg/e2e/operators/dvo.go, pkg/e2e/operators/managedupgrade.go, pkg/e2e/operators/mustgather.go, pkg/e2e/operators/ocmagent/ocmagent.go, pkg/e2e/operators/osdmetricsexporter.go, pkg/e2e/operators/prunejob.go, pkg/e2e/operators/rbac.go, pkg/e2e/operators/routemonitor.go
https://issues.redhat.com/browse/SDCICD-900
Follow up to https://github.com/openshift/osde2e/pull/1521
=> SDCICD-900 Swap concurrentviper to use viper alias

pkg/common/providers/ocmprovider/cluster.go
https://issues.redhat.com/browse/SDCICD-848
=> SDCICD-848 - Fix OSD CCS Cluster Creation

pkg/e2e/verify/routes.go
the test keeps failing because the deployment isn't created yet but it gets created within 30 seconds of the test failing. Let's wait for it to exist and retry the GET request as it should _eventually_ succeed.
=> e2e/verify: wait for deployment to be created

pkg/e2e/verify/routes.go
=> SDCICD-905: e2e/verify/routes - skip on hypershift

pkg/e2e/operators/operators.go
Test failures have been observed for various operators when performing upgrades after a recent change to the implementation for determining the previous operator bundle channel to install as the base to upgrade from. These errors seen are HTTP 503 errors from the server side. It ranges, sometimes an operator upgrade test will work while other upgrade tests wont when running the entire suite.
This commit introduces retries to the grpc client query. The delay between retries is minimal and wont add unnecessary additional time to the test run. Which should resolve any intermittent errors when contacting the server.
In addition, switches out using the GinkgoIt wrapper and directly use ginkgo.It for the checkUpgrade function.
For [SDCICD-903](https://issues.redhat.com/browse/SDCICD-903)
- Ran …
=> SDCICD-903: Include retries when performing grpc query for operator bundle

pkg/e2e/osd/machinehealthcheck.go
closes [OSD-15140](https://issues.redhat.com//browse/OSD-15140)
=> update instance types for machinehealthchecks

pkg/common/providers/rosaprovider/cluster.go
Unable to delete the vpc due to osde2e was not able to locate the directory on the filesystem where the terraform state file is. In PR #1610 the check to get the report directory from ocm properties was moved. Which results in trying to get the property after the cluster no longer exists in ocm.
This commit fixes the issue and moves the check to get ocm property prior to cluster being destroyed.
=> Fix bug when attempting to delete aws vpc for hypershift clusters

pkg/e2e/e2e.go
This change modifies when the shared directory gets created. It will only be created when the SHARED_DIR environment variable is defined. This is primarily used when running osde2e within prow if a following step requires certain files (e.g. cluster-id).
* For [SDCICD-951](https://issues.redhat.com//browse/SDCICD-951)
* Triggered by #1696
=> Only create shared directory when env variable is defined

docs/Self-Service-MOPs/TRT-OCP-Release-Gating.md
This PR adds a new file explaining how to add/remove TRT jobs and their signal.
For [SDCICD-954](https://issues.redhat.com/browse/SDCICD-954)
=> Add documentation for TRT OCP release gate jobs

docs/Config.md
small readme change to reflect generic test harness config name per [sdcicd-717](https://issues.redhat.com//browse/sdcicd-717) changes
=> sdcicd-717 update suite name in readme

pkg/e2e/verify/sccs.go
Lately we see this test failing to find the dedicated-admins-cluster clusterrole once the cluster was provisioned. The clusterrole gets created as part of the helpers (e.g. test setup) but test fails being unable to find it. Its possible it could be a timing issue where its being created then test tries to locate it right after.
This commit hopes to resolve this by adding a wait to see if the clusterrole exists.
```
2023/04/05 12:29:10 helper.go:116: Setup called for osde2e-256cm
2023/04/05 12:29:10 helper.go:195: Created SA: dedicated-admin-project
2023/04/05 12:29:10 helper.go:205: Created SA: dedicated-admin-cluster
2023/04/05 12:29:11 helper.go:215: Created SA: cluster-admin
[1680696837] OSD e2e suite - 17/222 specs SSSSSSSSSSS••SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS …
```
=> Wait for dedicated-admins-cluster clusterrole to exists for scc tests

go.mod, go.sum, pkg/common/providers/rosaprovider/cluster.go, pkg/common/providers/rosaprovider/config.go
=> bump ocm-sdk-go to v0.1.330 and rosa to v1.2.16

pkg/common/helper/helper.go
Intermittently tests will fail to retrieve the namespace created for the test to use. This happens as pre-setup to the test execution. Sometimes it fails due to the projects api service is unavailable.
This commit adds a retry of 6 attempts (30 seconds total duration) to attempt to get the namespace from the server. This can help in the event there was a small hiccup in the network when the pre test setup attempts to contact the server.
Example from latest periodic job [run](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-osde2e-main-hypershift-stage-e2e-default/1646121169834741760)
=> helper: introduce retries when attempting to fetch namespace from server

scripts/parameterized-job.sh
adding more job params for osde2e ad hoc job 
[sdcicd-972](https://issues.redhat.com//browse/sdcicd-972)
=> adding more job params

pkg/e2e/verify/storage.go
This test has been flaky where it sometimes intermittently fails waiting for the pod to be succeeded. The underlying issue is the volume is still trying to be attached to the pod. Resulting in the timeout exceeded.
This commit aims to try to resolve the flakiness:
* Update the error message to include the storage class/provisioner being used
* Double the pod succeeded timeout from 2 to 4 minutes
=> verify/storage.go: minor refinements to pvc test

pkg/common/providers/rosaprovider/vpc.go
The terraform aws provider will load credentials in the same order as the aws cli/sdk does. The current implementation will likely fail when running in a prow job. As osde2e has not configured local credentials. It loads credentials into viper config and they would only be set as environment variables when using the `callAndSetAWSSession` function.
This commit wraps the terraform plan, apply and destroy operations for creating/deleting vpc with the call and set aws session function. Allowing aws credentials to be set and picked up accordingly by the terraform aws provider.
=> Set aws session when create/delete rosa hcp vpc

configs/complete-e2e.yaml
new test config contains same e2e tests  as e2e-suite + test harnesses.
=> sdcicd-955 added new test config

pkg/common/providers/rosaprovider/accountroles.go
This PR resolves a bug in the create/get account role methods. In the event of getting account roles fails, it should not attempt to create account roles. With this fix, account roles will only be created if they do not exist. Any other error wills will be raised back up to the caller function.
=> Do not attempt account role creation when unable to get account roles

Dockerfile.osde2e
```
[rywillia@t14s sdqe]$ podman images | grep "quay.io/app-sre/osde2e" | grep latest
quay.io/app-sre/osde2e                                      latest                             3cf86144e586  6 hours ago     224 MB
[rywillia@t14s sdqe]$ podman images | grep "quay.io/app-sre/osde2e" | grep e4b139e
quay.io/app-sre/osde2e                                      e4b139e                            b9f44bfbb534  11 minutes ago  389 MB
```
=> Install git as its required to use terraform-exec within a container

docs/Self-Service-MOPs/Ad-Hoc-E2E-Job.md, docs/Self-Service-MOPs/Region-Enablement.md, docs/Test-Harnesses.md
Added docs for
- jenkins job
- region enablement
- test harness
=> Docs for self service jobs

docs/Test-Harnesses.md
This includes slight modification from generic as well as operator test harness. Adding it here.
=> Blurb and link to addon test harness testing

scripts/parameterized-job.sh
allow TEST_HARNESSES and POLLING_TIMEOUT to be passed from jenkins job environment to osde2e
related jenkins job update https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/68438
=> added parameters to job script

scripts/parameterized-job.sh
adding 2 env vars brought about by region enablement job request
https://issues.redhat.com/browse/SDCICD-909
1. OCM_CCS
2. MULTI_AZ
jenkins template update
https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/70005
=> Jenkins ccs env var

pkg/common/providers/rosaprovider/oidcconfig.go
OSDe2e creates unmanaged oidc-configs
=> Adds managed false arg to oidc config create

pkg/e2e/workloads/workloads.go
this test is flakey and needs debugging to understand why the deployment doesn't come up ([SDCICD-1038](https://issues.redhat.com//browse/SDCICD-1038))
=> e2e/workloads: mark redmine test as pending

docs/Self-Service-MOPs/Region-Enablement.md
merge after https://github.com/openshift/ops-sop/pull/2609
=> Update Region-Enablement.md to include link to new jenkins SOP

docs/CI-Jobs.md
This PR updates the CI jobs doc to reflect the current active SD CICD jobs.
https://github.com/openshift/release/pull/40586
- [SDCICD-1019](https://issues.redhat.com//browse/SDCICD-1019)
=> SDCICD-1019: Update CI jobs doc to reflect current active jobs

pkg/common/providers/rosaprovider/cluster.go
This commit aims at resolving the issues with resources being left over in the aws account. Depending on at the time of cluster creation, if an oidc config id is provided. The options to remove the operator roles and oidc provider differ when no oidc config id is provided.
Implementation based on https://github.com/openshift/osde2e-common/pull/22/files to fix current osde2e rosa provider.
**ROSA HCP**
_Before_
```
2023/06/21 15:47:34 cluster.go:364: [operator-roles --cluster 24gc8g49ldu34e8g6n6kvqb8nins6kg0 --mode auto --yes]
2023/06/21 15:47:34 cluster.go:369: [oidc-provider --cluster 24gc8g49ldu34e8g6n6kvqb8nins6kg0 --mode auto --yes]
INFO: There are no operator roles to delete for cluster '24gc8g49ldu34e8g6n6kvqb8nins6kg0'
2023/06/21 15:48:46 cluster.go:375: Deleted operator roles for …
```
=> Modify ROSA options for delete operator roles and oidc provider

configs/stage.yaml
=> configs: set rosa.env to stage in stage config

cmd/osde2e/cleanup/cmd.go
This PR change, callers of `osde2e cleanup` now have the option to provide a specific cluster id to clean up. If one is not provided, it will default to the standard behavior to clean up clusters that are expired.
With this change, it will allow a user of osde2e to clean up a cluster if they left the cluster up (skip destroy cluster) when calling `osde2e test`.
Needed by [SDCICD-1058](https://issues.redhat.com//browse/SDCICD-1058)
=> Allow cleanup command to clean up a specific cluster by id

docs/Config.md
jira: https://issues.redhat.com/browse/SDCICD-946
syncing doc with updates to destroy-cluster flag and noting default value
=> update docs to reflect new skip-destroy-cluster env var

docs/Test-Harnesses.md
added missing step in harness testing doc
=> added step to create harness quay repo

pkg/e2e/harness_runner/harness_runner.go
Addon harness prow jobs are currently defining POLLING_TIMEOUT to time out their harness jobs
However, we can not usePOLLING TIMEOUT  to time out multiple harness jobs since this is usually quite high (2 hours). And POLLING TIMEOUT also applies to overall e2e job. So we have now specified SUITE_TIMEOUT variable to time out individual harnesses.
To ensure this doesn't affect current prow jobs, we will fall back to POLLING_TIMEOUT for harness jobs where SUITE_TIMEOUT is not specified.
=> use suite timeout config for harness if provided, otherwise generic pollingtimeout

pkg/e2e/harness_runner/harness_runner.go
This PR aims to address the issue seen recently with test harness jobs or add on jobs failing to have their images test suite.  When viewing osde2e logs, the timeout is set to 6 seconds. The new design is to use the `SUITE_TIMEOUT` set by osde2e. This currently defaults to `6` hours (not seconds) which is what ginkgo suite timeout looks for. When using this value for the test harness runner, it is not being converted into seconds, resulting in pods aborting quickly.
Error([job example](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/osde2e-int-aws-nvidia-gpu-addon/1685802673778987008)):
```
2023/07/31 01:06:24 harness_runner.go:57: ======= RUNNING HARNESS: quay.io/edge-infrastructure/ci-tools-nvidia-gpu-operator:osde2e =======
2023/07/31 01:06:24 runner.go:111: Using …
```
=> Test harness: fix handling the timeout for the harness pod

OWNERS
Onboarding Yiqin to Cicada as code reviewer
[SDCICD-1090](https://issues.redhat.com//browse/SDCICD-1090)
=> added yiqin to reviewers

go.mod, go.sum
This update includes the new changes from rosa for account role creation.
=> Update the osde2e-common dependency

pkg/e2e/operators/customdomains.go
with the deprecation[0] of CDO, the tests need to be skipped if the version is greater than or equal to 4.13.
The semver/v3 library doesn't seem to parse and compare the nightly versions correctly so just check the major/minor values.
[0]: https://github.com/openshift/custom-domains-operator/commit/63e002a5e9c999057e96b1f5ac46bcb7adb7f10b
[SDCICD-1133](https://issues.redhat.com//browse/SDCICD-1133)
=> e2e: skip customdomains on >= 4.13

pkg/common/versions/installselectors/triggered_nightlies.go
previously, using the job name safe only worked for the rosa-sts jobs due to the safe name being set differently than expected
```
package main
import (
"fmt"
"regexp"
)
func main() {
v1 := "4.14.0-0.nightly-2023-09-13-103011-openshift-dedicated"
r1 := `4.\d+.\d-\d.nightly-\d{4}-\d{2}-\d{2}-\d+`
reg := regexp.MustCompile(r1)
res := reg.FindStringSubmatch(v1)
fmt.Println(res[0])
}
```
=> installselectors: use regex to find nightly version from jobid

pkg/debug/diff.go
the page has changed since this code previously worked, it is now dynamically rendered on the client side so the value is not available in the HTML directly. Parse the last script block on the page for the JSON object used to render the page. Then look for the second item in the list, assuming it is the previously ran job.
Yes, this is extremely fragile.
```
x, err := debug.GetLastJobID("https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com", "periodic-ci-openshift-osde2e-main-nightly-4.14-rosa-classic-sts")
if err != nil {
panic(err)
}
fmt.Println(x)
```
```
❯ go run main.go
2023/09/21 09:47:47 Looking up job history from https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/job-history/gs/origin-ci-test/logs/periodic-ci-openshift-osde2e-main-nightly-4.14-rosa-classic-sts
1704653830467096576
``` …
=> debug: fix getLastJobID search for job ID

go.mod, go.sum, pkg/e2e/operators/configurealertmanager/configurealertmanager.go, pkg/e2e/operators/ocmagent/ocmagent.go, pkg/e2e/operators/operators.go
the old code is failing randomly for operators, try swapping to the common code to get down to one impl of operator upgrade
=> e2e/operators: use common operator upgrade function

pkg/e2e/osd/ocm.go
remove noisy log, it isn't providing much value
=> e2e/osd: remove firewall cmd log

go.mod, go.sum
go get github.com/openshift/osde2e-common@latest
=> misc: bump osde2e-common

pkg/e2e/osd/ocm.go
missed this one when removing the create log
=> osd: remove firewall delete log

go.mod, go.sum
go get github.com/openshift/osde2e-common@latest
=> go.mod: bump osde2e-common

pkg/e2e/e2e.go
this log is not necessarily correct
=> e2e: remove incorrect log

pkg/e2e/state/alerts.go
the alert logs aren't getting captured in the ginkgo stderr making it more difficult to see what alerts were triggered
imports are just being sorted
/cc @MrSantamaria @ritmun 
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-osde2e-main-nightly-4.15-rosa-classic-sts/1709442918114136064
=> e2e: write alert logs to ginkgologr

pkg/e2e/harness_runner/harness_runner.go
Why? 
currently if a harness test fails, the failed assertion skips uploading  of results files to s3
What?
move throwing error after saving/uploading result files to ensure results get uploaded despite test failures
=> move throwing error after uploading result files 

configs/blocking-suite.yaml
Added a blocking-suite config yaml to be used by prow jobs for new blocking jobs in osde2e
Card [SDCICD-1191](https://issues.redhat.com/browse/SDCICD-1191)
=> Add blocking-suite config

cmd/osde2e/test/cmd.go, pkg/common/config/config.go, pkg/e2e/e2e.go
added cmf flag "provision-only" to return osde2e without running tests
[SDCICD-1201](https://issues.redhat.com//browse/SDCICD-1201)
=> added cmd arg to skip all tests for provision-only step

cmd/osde2e/cleanup/cmd.go
`osde2e cleanup` will accept a time format string instead of number of days (eg 1h30m)
`osde2e cleanup --iam --iam-older-than 6h`
[SDCICD-1206](https://issues.redhat.com//browse/SDCICD-1206)
=> Accept duration format string instead of number of days for iam resource cleanup command. 

go.mod, go.sum
upgrade includes fix for prow job errors for semver parsing
https://github.com/openshift/osde2e-common/pull/62
=> upgrade osde2e-common

pkg/e2e/openshift/config.go
conformance pod command loads ca.crt and ocm token which isn't needed for prow job pod any more since osde2e will load them on test pods
These lines are failing on prow rehearse 
[SDCICD-1192](https://issues.redhat.com//browse/SDCICD-1192)
=> removing old auth args from conformance job command  

pkg/e2e/e2e.go
PollImmediate has been deprecated in recent k8s versions, and is behaving unexpectedly, i.e. returning error prematurely. 
Replacing with recommended polling PollUntilContextTimeout
[SDCICD-1192](https://issues.redhat.com//browse/SDCICD-1192)
When tested locally, PollImmediate loop is executed only once and breaks loop when err is returned. It used to wait for 5 minutes despite errors, but not since deprecation. 
PollUntilContextTimeout function loops for 5 minutes timeout and finds kubeconfig during the wait.
=> replaced deprecated PollImmediate with PollUntilContextTimeout

scripts/parameterized-job.sh
add GCP_CREDS_JSON from app interface secrets to osde2e job env
[sdcicd-1228](https://issues.redhat.com//browse/sdcicd-1228)
=> sdcicd-1228 pass gcp creds from self service job script

pkg/common/providers/ocmprovider/cluster.go, pkg/e2e/operators/cloudingress/certificate.go, pkg/e2e/operators/cloudingress/dnsname.go, pkg/e2e/operators/cloudingress/public_private.go, pkg/e2e/operators/cloudingress/rhapi_lb.go, pkg/e2e/operators/cloudingress/routeSelector.go
these boolean comparisons can be simplified
staticcheck lint S1002
[SDCICD-1266](https://issues.redhat.com//browse/SDCICD-1266)
=> misc: should omit comparison to bool constant

cmd/osde2e/cleanup/cmd.go
Update cleanup stage cluster log
[SDCICD-1240](https://issues.redhat.com/browse/SDCICD-1240l)
=> Update cleanup stage cluster log

pkg/common/runner/pod.go, pkg/common/runner/service.go
These instances directly affect prow jobs terminating abruptly while polling test pod, in [sdcicd-1198](https://issues.redhat.com//browse/sdcicd-1198) for example:
```"level"=0 "msg"="Waiting for test results using Endpoint 'osde2e-ueg2v/openshift-conformance-2zj9z'..."
"level"=0 "msg"="Waiting for test results using Endpoint 'osde2e-ueg2v/openshift-conformance-2zj9z'..."
"level"=0 "msg"="Waiting for test results using Endpoint 'osde2e-ueg2v/openshift-conformance-2zj9z'..."
"msg"="unable to get pod osde2e-ueg2v/openshift-conformance-oz8kx" "error"="pods \"openshift-conformance-oz8kx\" not found"
"level"=0 "msg"="Collecting logs from containers on openshift-conformance runner Pod..."
[38;5;9m[FAILED][0m in [It] - /go/src/github.com/openshift/osde2e/pkg/e2e/openshift/conformance.go:103 …
```
=> SDCICD-1266 deprecate more instances of pollImmediate

assets/tests/ocp-tests-runner.template, pkg/common/helper/helper.go, pkg/e2e/harness_runner/harness_runner.go, pkg/e2e/openshift/conformance.go
Use harness-like template to run conformance test
[SDCICD-1275](https://issues.redhat.com//browse/SDCICD-1275)
[SDCICD-1198](https://issues.redhat.com//browse/SDCICD-1198)
=> update ocp test pod templating to match harness template generation  

pkg/common/helper/helper.go
- change Immediate: true in pollUntilContextTimeout - this saves 5 seconds wait after each call. This logic is called 20+ times in average testing.
- added condition to poll h.proj only if h.proj is nil
=> speed up helper setup

pkg/common/versions/installselectors/triggered_nightlies.go
relying on "RELEASE_IMAGE_LATEST" is currently not taking effect. Use both eligible vars ro find version.
=> use "RELEASE_IMAGE_LATEST" or "PROW_JOB_ID" to find version for nightly jobs 

.tekton/osde2e-main-pull-request.yaml, .tekton/osde2e-main-push.yaml
=> .tekton: set build-source-image true

pkg/common/cluster/clusterutil.go, pkg/common/config/config.go, pkg/common/providers/mock/mock.go, pkg/common/providers/ocmprovider/cluster.go, pkg/common/providers/rosaprovider/wrapped_calls.go, pkg/common/spi/provider.go
this is dead code, osde2e isn't concerned with scale testing clusters anymore (there is a scale+performance team for that!)
=> misc: drop all cluster scaling code

.tekton/osde2e-main-pull-request.yaml, .tekton/osde2e-main-push.yaml
skip if anything else is changed not related to the binary build. This matches the same expression we use for prow
copied from https://github.com/openshift/hypershift/blob/2f6cfe21a0861dea3130f3bed0d3ae5553b8c28b/.tekton/hypershift-operator-main-pull-request.yaml#L13-L15
https://redhat-appstudio.github.io/docs.appstudio.io/Documentation/main/how-to-guides/configuring-builds/proc_preventing_redundant_rebuilds/
=> SDCICD-1306: only build on specific files

pkg/common/providers/ocmprovider/cluster.go
Expiration feature is unsupported in prod  and we get errors if we try to set it. 
Jobs running in prod fail due to returned errors.
Self service jobs are open to prod runs. It's also a good idea prevent failures for any future prod jobs.
=> SDCICD-1252 remove expiration date setting from prod clusters

pkg/common/providers/ocmprovider/cluster.go
allows region selection for random region for any cloud provider
GCP was previously excluded from random region, and aws region was found using aws creds. This isn't necessary since ocm client returns region list without provider creds.
=> change random region selector to provider-agnostic ocm client

.ci-operator.yaml, go.mod
=> go.mod: bump to go 1.22

test/sdn_migration/scripts/validate-sdn-ovn-migration-jobs.sh
Update sdn-migration script to pull images from released builds
=> Update Container Image

test/sdn_migration/sdn_migration_test.go
=> test/sdn_migration: rm unused func

osde2e.Dockerfile
=> dockerfile: set path and cache dependencies

pkg/common/runner/results.go, pkg/common/upgrade/managed.go, pkg/common/upgrade/upgrade.go, pkg/e2e/operators/certman.go, pkg/e2e/operators/managedvelero.go, pkg/e2e/osd/ocm.go, pkg/e2e/osd/rebalance_infra_nodes.go, pkg/e2e/proxy/postinstall.go, pkg/e2e/state/alerts.go, pkg/e2e/state/prometheus.go, pkg/e2e/verify/encrypted_storage.go, pkg/e2e/verify/user_workload_monitoring.go
replace with PollUntilContextTimeout using the local context or context.TODO
=> pkg/*: resolve PollImmediate deprecations

.tekton/fedramp-pull-request.yaml, .tekton/fedramp-push.yaml, .tekton/osde2e-main-pull-request.yaml, .tekton/osde2e-main-push.yaml, .tekton/sdn-migration-pull-request.yaml, .tekton/sdn-migration-push.yaml
EC is now failing due to this missing task
=> .tekton/*: add required rpms-signature-scan task

.tekton/fedramp-pull-request.yaml, .tekton/fedramp-push.yaml, .tekton/osde2e-main-pull-request.yaml, .tekton/osde2e-main-push.yaml, .tekton/sdn-migration-pull-request.yaml, .tekton/sdn-migration-push.yaml
this pipeline doesn't have the build-index-image task
=> .tekton/osde2e-main*: fix results ref

.ci-operator.yaml, Makefile, go.mod, osde2e.Dockerfile, test/fedramp/Dockerfile, test/sdn_migration/Dockerfile
1.22 is EOL as of Feb and 1.24 toolset isn't out yet
=> SDCICD-1498: bump to go 1.23

renovate.json
setting updateNotScheduled to true, hopefully allowing MM to rebase PRs when the button is checked
https://konflux.pages.redhat.com/docs/users/mintmaker/user.html#how-to-stop-prsmrs-from-being-updated-outside-of-schedule
https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1742306180364799?thread_ts=1742301894.253229&cid=C04PZ7H0VA8
=> misc: add custom renovate config

renovate.json
the rebase didn't happen with the previous setting, so this was suggested
=> misc: swap the setting to adjust the schedule

renovate.json
the global scheduler is overriding my global schedule setting
=> misc: use the gomod manager

pkg/common/config/config.go, pkg/common/prometheus/connect.go
we don't support connecting to external prometheus instances or dbs anymore
=> pkg/common: rm external prom and db config

configs/e2e-suite.yaml
This PR adds cad's E2E image to the e2e suite.
=> Feat(SDE-4821): add cad e2e

.golang-ci.yml, Makefile
and run `golangci-lint migrate`
=> misc: upgrade to golangci-lint v2

renovate.json
group k8s, openshift, and golang/x modules in PRs each respectfully
=> misc: update renovate config to group packages

go.mod, go.sum
=> bump osde2e-common

configs/e2e-suite.yaml
remove duplicate CIO image from e2e-suite
=> remove duplicate CIO image from suite

pkg/e2e/osd/inhibitions.go
All tests in the "should exist" unit test that has an expectedPresent value of true would fail because reflect.DeepEqual was comparing disparate types (slice of string and slice of
prometheusModel.LabelName).
The easiest way to fix this was to simply change the type in the table-based tests anonymous struct to []string. And, as a bonus, this replaces all of the instances of prometheusModel.LabelName with []string, which aligns with the fix needed for the breaking change (see below).
Here is the fella that caused the bug:
https://github.com/prometheus/alertmanager/commit/34115a78a3400a856021e995a70715f9703f25cb
https://pkg.go.dev/reflect#DeepEqual
This was tested locally. To test, you can follow these instructions:
https://gitlab.cee.redhat.com/insight-global/docs/-/blob/master/osde2e.md …
=> Test fails because reflect.DeepEqual is comparing different types

OWNERS
=> remove self from OWNERS
